
  require 'rubygems'

Gem::Specification.new {|s|
    s.name          = 'pkg35'
    s.version       = '0.0.1'
    s.author        = 'naresh'
    s.email         = 'nareshdevasani@gmail.com'
    s.homepage      = 'http://github.com/nareshdevasani'
    s.platform      = Gem::Platform::RUBY
    s.summary       = 'An empty gem that depends on every gem available'
    s.description   = s.summary

    s.add_dependency 'parse_packwerk'
    s.add_dependency 'brdata'
    s.add_dependency 'ltree_hierarchy'
    s.add_dependency 'nsa'
    s.add_dependency 'activerecord-mysql2-adapter'
    s.add_dependency 'aptible-resource'
    s.add_dependency 'actionwebservice'
    s.add_dependency 'skim'
    s.add_dependency 'tld'
    s.add_dependency 'wrest'
    s.add_dependency 'papers'
    s.add_dependency 'bosh_agent'
    s.add_dependency 'res'
    s.add_dependency 'watir-screenshot-stitch'
    s.add_dependency 'autotest-fsevent'
    s.add_dependency 'attachment_on_the_fly'
    s.add_dependency 'chef-server-api'
    s.add_dependency 'embulk-output-mysql'
    s.add_dependency 'rack-affiliates'
    s.add_dependency 'rubocop-govuk'
    s.add_dependency 'ean13'
    s.add_dependency 'flowcommerce'
    s.add_dependency 'engen'
    s.add_dependency 'msgpack_rails'
    s.add_dependency 'octiron'
    s.add_dependency 'rails_admin-i18n'
    s.add_dependency 'acts_as_singleton'
    s.add_dependency 'neverbounce-api'
    s.add_dependency 'bacon'
    s.add_dependency 'sysinfo'
    s.add_dependency 'remockable'
    s.add_dependency 'codersdojo'
    s.add_dependency 'p4ruby'
    s.add_dependency 'gstreamer'
    s.add_dependency 'nestegg'
    s.add_dependency 'verhoeff'
    s.add_dependency 'mls'
#    s.add_dependency 'IPinfo'
    s.add_dependency 'property_sets'
    s.add_dependency 'blather'
    s.add_dependency 'guard-migrate'
    s.add_dependency 'simp-beaker-helpers'
    s.add_dependency 'saucy'
#    s.add_dependency 'fluent-plugin-td'
    s.add_dependency 'jpostcode'
#    s.add_dependency 'filestack-rails'
    s.add_dependency 'twemoji'
    s.add_dependency 'passgen'
    s.add_dependency 'mackerel-client'
    s.add_dependency 'mongoid-enum'
    s.add_dependency 'fedux_org-stdlib'
    s.add_dependency 'base_x'
    s.add_dependency 'pry-auditlog'
    s.add_dependency 'kennel'
    s.add_dependency 'cuba'
#    s.add_dependency 'daengine'
    s.add_dependency 'opentelemetry-test-helpers'
    s.add_dependency 'chef-server-webui'
#    s.add_dependency 'roebe'
    s.add_dependency 'linefit'
    s.add_dependency 'marty'
    s.add_dependency 'rubocop-discourse'
    s.add_dependency 'will_paginate-foundation'
    s.add_dependency 'contour'
    s.add_dependency 'wilson_score'
    s.add_dependency 'fluent-plugin-dogstatsd'
    s.add_dependency 'pg-eyeballs'
    s.add_dependency 'logist'
    s.add_dependency 'sentient_user'
    s.add_dependency 'vcardigan'
    s.add_dependency 'starlark_compiler'
    s.add_dependency 'muck-users'
    s.add_dependency 'mailchimp'
    s.add_dependency 'gserver'
    s.add_dependency 'rushover'
    s.add_dependency 'capistrano-deploytags'
    s.add_dependency 'corn_starch'
#    s.add_dependency 'ghostplus'
    s.add_dependency 'php_serialize'
    s.add_dependency 'sane'
    s.add_dependency 'cacheable_flash'
    s.add_dependency 'monza'
#    s.add_dependency 'attachinary'
    s.add_dependency 'hello_fax'
    s.add_dependency 'fhir_stu3_models'
#    s.add_dependency 'goliath'
    s.add_dependency 'gchartrb'
    s.add_dependency 'fig'
#    s.add_dependency 'effective_orders'
    s.add_dependency 'refile'
    s.add_dependency 'paperclip-sftp'
#    s.add_dependency 'active_admin_paranoia'
#    s.add_dependency 'stbaldricks'
    s.add_dependency 'watir-webdriver-performance'
    s.add_dependency 'pact_broker'
    s.add_dependency 'rubocop-rubycw'
    s.add_dependency 'omniauth-constantcontact2'
    s.add_dependency 'fix_microsoft_links'
#    s.add_dependency 'social_stream-base'
#    s.add_dependency 'zendesk_apps_tools'
    s.add_dependency 'activerecord-jdbch2-adapter'
    s.add_dependency 'virtus_convert'
    s.add_dependency 'jbuilder_cache_multi'
    s.add_dependency 'sensu-plugins-chrony'
    s.add_dependency 'kibana_url'
    s.add_dependency 'brazilian-rails'
    s.add_dependency 'zapier_ruby'
    s.add_dependency 'sproutcore'
    s.add_dependency 'frameworks-capybara'
    s.add_dependency 'omniauth-azure-activedirectory'
    s.add_dependency 'resque-meta'
    s.add_dependency 'serialport'
    s.add_dependency 'compass-rgbapng'
#    s.add_dependency 'simple_captcha2'
    s.add_dependency 'auto_tagger'
    s.add_dependency 'logdna'
    s.add_dependency 'render_me_pretty'
    s.add_dependency 'htmldiff'
    s.add_dependency 'string-direction'
    s.add_dependency 'brcobranca'
#    s.add_dependency 'react-bootstrap-rails'
    s.add_dependency 'pdfjs_rails'
    s.add_dependency 'jsoneditor-rails'
#    s.add_dependency 'devise_lastseenable'
    s.add_dependency 'auto_increment'
    s.add_dependency 'spring-commands-testunit'
    s.add_dependency 'fastlane-plugin-cordova'
    s.add_dependency 'active_metadata'
    s.add_dependency 'bootstrap-filestyle-rails'
#    s.add_dependency 'lita-slack-karma-sync'
    s.add_dependency 'ruby-nuggets'
    s.add_dependency 'hash_dig_and_collect'
    s.add_dependency 'kpeg'
#    s.add_dependency 'commontator'
    s.add_dependency 'pnotify-rails'
    s.add_dependency 'enju_circulation'
    s.add_dependency 'jquery-ui-themes'
    s.add_dependency 'fancy_irb'
    s.add_dependency 'fastclick-rails'
    s.add_dependency 'runcible'
    s.add_dependency 'acts-as-taggable-array-on'
    s.add_dependency 'newgem'
    s.add_dependency 'relaton-bib'
    s.add_dependency 'fluent-plugin-json-in-json'
    s.add_dependency 'bootstrap-glyphicons'
    s.add_dependency 'allocation_stats'
    s.add_dependency 'caren-api'
    s.add_dependency 'govspeak'
    s.add_dependency 'json-patch'
    s.add_dependency 'sensu-plugins-hardware'
    s.add_dependency 'zendesk_apps_support'
    s.add_dependency 'flying-sphinx'
    s.add_dependency 'sterile'
#    s.add_dependency 'torquebox-web'
    s.add_dependency 'active_delivery'
    s.add_dependency 'govuk_app_config'
    s.add_dependency 'cocoapods-dependencies'
    s.add_dependency 'es6-promise-rails'
    s.add_dependency 'rubysl-resolv'
    s.add_dependency 'mandrill_dm'
    s.add_dependency 'xmlparser'
    s.add_dependency 'brighter_planet_layout'
    s.add_dependency 'chamber'
    s.add_dependency 'jquery-form-rails'
    s.add_dependency 'thor-rails'
    s.add_dependency 'webvalve'
    s.add_dependency 'authlete'
    s.add_dependency 'dnssd'
    s.add_dependency 'gruf-newrelic'
#    s.add_dependency 'megatron'
    s.add_dependency 'mina-multistage'
    s.add_dependency 'conjur-api'
    s.add_dependency 'ripper_ruby_parser'
    s.add_dependency 'git-smart'
    s.add_dependency 'cuke_slicer'
    s.add_dependency 'mini_scheduler'
#    s.add_dependency 'db-charmer'
    s.add_dependency 'postrank-uri'
    s.add_dependency 'webp-ffi'
#    s.add_dependency 'metanorma-standoc'
    s.add_dependency 'global_phone_dbgen'
    s.add_dependency 'simple_record'
    s.add_dependency 'old_sql'
    s.add_dependency 'fluent-plugin-input-gelf'
    s.add_dependency 'danger-slather'
    s.add_dependency 'batch_api'
    s.add_dependency 'hookup'
#    s.add_dependency 'fluent-plugin-multiline-parser'
    s.add_dependency 'wepay-rails'
    s.add_dependency 'birthday'
    s.add_dependency 'graphql-persisted_queries'
    s.add_dependency 'aead'
    s.add_dependency 'bert'
#    s.add_dependency 'rails3_acts_as_paranoid'
    s.add_dependency 'amalgalite'
    s.add_dependency 'omniauth-google'
    s.add_dependency 'salesforcebulk'
    s.add_dependency 'ruby-growl'
    s.add_dependency 'savon-multipart'
    s.add_dependency 'ferret'
    s.add_dependency 'rspec-power_assert'
    s.add_dependency 'support_table_data'
    s.add_dependency 'confstruct'
    s.add_dependency 'automatiek'
    s.add_dependency 'jekyll-tagging'
    s.add_dependency 'envkey'
    s.add_dependency 'oddb2xml'
    s.add_dependency 'bootstrap-typeahead-rails'
    s.add_dependency 'traco'
#    s.add_dependency 'riddl'
    s.add_dependency 'ghi'
    s.add_dependency 'vm_shepherd'
    s.add_dependency 'active_presenter'
    s.add_dependency 'xsv'
    s.add_dependency 'infusionsoft'
    s.add_dependency 'azure-storage-file'
    s.add_dependency 'correios-cep'
#    s.add_dependency 'gds-sso'
#    s.add_dependency 'lalala'
    s.add_dependency 'google-cloud-monitoring-dashboard-v1'
    s.add_dependency 'slick_rails'
    s.add_dependency 'action_subscriber'
    s.add_dependency 'ibm_db'
    s.add_dependency 'ruby_cowsay'
    s.add_dependency 'active-triples'
    s.add_dependency 'activerecord_where_assoc'
    s.add_dependency 'omniauth-tumblr'
    s.add_dependency 'omniauth-saml-cespi'
    s.add_dependency 'savon_model'
    s.add_dependency 'rubygems-tasks'
    s.add_dependency 'groonga-command-parser'
    s.add_dependency 'filesystem'
    s.add_dependency 'aptible-cli'
    s.add_dependency 'slugify'
    s.add_dependency 'logger-application'
    s.add_dependency 'code_teams'
    s.add_dependency 'graphiti_errors'
    s.add_dependency 'puppet-lint-file_source_rights-check'
    s.add_dependency 'sidekiq-bouncer'
    s.add_dependency 'mollie-api-ruby'
    s.add_dependency 'watirsome'
    s.add_dependency 'iStats'
    s.add_dependency 'valid_url'
    s.add_dependency 'bootstrap-email'
    s.add_dependency 'suspenders'
    s.add_dependency 'friendly_mime'
#    s.add_dependency 'lalala-assets'
    s.add_dependency 'acts_as_xlsx'
    s.add_dependency 'beanstalkd_view'
    s.add_dependency 'chef-server'
}
