
  require 'rubygems'

Gem::Specification.new {|s|
    s.name          = 'top-1800-to-2k-gems'
    s.version       = '0.0.1'
    s.author        = 'naresh'
    s.email         = 'nareshdevasani@gmail.com'
    s.homepage      = 'http://github.com/nareshdevasani'
    s.platform      = Gem::Platform::RUBY
    s.summary       = 'An empty gem that depends on every gem available'
    s.description   = s.summary

    s.add_dependency 'page_navigation'
    s.add_dependency 'tinymce-rails'
#    s.add_dependency 'logstash-codec-multiline'
    s.add_dependency 'unicorn-rails'
    s.add_dependency 'carrierwave-aws'
    s.add_dependency 'devise-authy'
    s.add_dependency 'apipie-rails'
    s.add_dependency 'fog-joyent'
    s.add_dependency 'prawn-svg'
    s.add_dependency 'mailgun-ruby'
    s.add_dependency 'rsync'
    s.add_dependency 'hiera-eyaml'
    s.add_dependency 'fluent-plugin-geoip-filter'
    s.add_dependency 'abstract'
    s.add_dependency 'chef-rewind'
#    s.add_dependency 'logstash-output-elasticsearch'
    s.add_dependency 'syslog_protocol'
    s.add_dependency 'ruby-protocol-buffers'
    s.add_dependency 'google-adwords-api'
    s.add_dependency 'sinatra-activerecord'
    s.add_dependency 'shrine'
    s.add_dependency 'seedbank'
    s.add_dependency 'pathspec'
    s.add_dependency 'angular_rails_csrf'
    s.add_dependency 'ckeditor'
    s.add_dependency 'guard-bundler'
#    s.add_dependency 'march_hare'
    s.add_dependency 'rspec-html-matchers'
    s.add_dependency 'webhdfs'
    s.add_dependency 'wannabe_bool'
    s.add_dependency 'pretender'
#    s.add_dependency 'logstash-input-tcp'
    s.add_dependency 'ci_reporter_rspec'
    s.add_dependency 'public_activity'
    s.add_dependency 'elastic-transport'
    s.add_dependency 'bootstrap3-datetimepicker-rails'
    s.add_dependency 'ar_transaction_changes'
    s.add_dependency 'teaspoon'
#    s.add_dependency 'logstash-output-amazon_es'
    s.add_dependency 'ejson'
    s.add_dependency 'minitest-spec-rails'
    s.add_dependency 'rdkafka'
    s.add_dependency 'simple-random'
    s.add_dependency 'jquery-turbolinks'
    s.add_dependency 'eco-source'
    s.add_dependency 'saml_idp'
#    s.add_dependency 'logstash-filter-mutate'
    s.add_dependency 'eco'
    s.add_dependency 'jsonapi-serializer'
    s.add_dependency 'varia_model'
#    s.add_dependency 'logstash-filter-geoip'
#    s.add_dependency 'logstash-input-http'
    s.add_dependency 'ione'
    s.add_dependency 'rubocop-checkstyle_formatter'
    s.add_dependency 'coverband'
    s.add_dependency 'buff-extensions'
#    s.add_dependency 'logstash-output-s3'
    s.add_dependency 'sensu-plugins-disk-checks'
    s.add_dependency 'nilify_blanks'
    s.add_dependency 'distribute_reads'
#    s.add_dependency 'logstash-input-elasticsearch'
    s.add_dependency 'fog-ovirt'
    s.add_dependency 'opentelemetry-api'
    s.add_dependency 'fabrication'
    s.add_dependency 'test-kitchen'
    s.add_dependency 'stimulus-rails'
    s.add_dependency 'mailcatcher'
    s.add_dependency 'badge'
    s.add_dependency 'acts_as_tree'
    s.add_dependency 'geokit-rails'
    s.add_dependency 'authority'
    s.add_dependency 'buff-shell_out'
    s.add_dependency 'buff-ruby_engine'
    s.add_dependency 'riemann-client'
    s.add_dependency 'buff-config'
#    s.add_dependency 'logstash-input-http_poller'
#    s.add_dependency 'logstash-input-s3'
    s.add_dependency 'rubocop-faker'
    s.add_dependency 'avl_tree'
    s.add_dependency 'devise-async'
    s.add_dependency 'ipecache'
    s.add_dependency 'api-pagination'
    s.add_dependency 'mtrc'
#    s.add_dependency 'logstash-codec-fluent'
    s.add_dependency 'postmark'
#    s.add_dependency 'logstash-codec-es_bulk'
    s.add_dependency 'progress'
    s.add_dependency 'validates_email_format_of'
    s.add_dependency 'necromancer'
    s.add_dependency 'bundle'
    s.add_dependency 'jekyll-paginate'
    s.add_dependency 'ar-octopus'
    s.add_dependency 'sendgrid-rails'
#    s.add_dependency 'logstash-patterns-core'
#    s.add_dependency 'logstash-filter-dissect'
    s.add_dependency 'inspec-core'
    s.add_dependency 'skinny'
    s.add_dependency 'buff-ignore'
    s.add_dependency 'avro_turf'
#    s.add_dependency 'logstash-filter-grok'
    s.add_dependency 'pond'
    s.add_dependency 'em-hiredis'
    s.add_dependency 'numbers_and_words'
#    s.add_dependency 'logstash-input-generator'
    s.add_dependency 'dentaku'
    s.add_dependency 'oj_mimic_json'
#    s.add_dependency 'logstash-filter-clone'
    s.add_dependency 'capistrano-sidekiq'
    s.add_dependency 'rack-livereload'
    s.add_dependency 'okcomputer'
    s.add_dependency 'aws-s3'
    s.add_dependency 'berkshelf'
    s.add_dependency 'maruku'
    s.add_dependency 'rspec_api_documentation'
    s.add_dependency 'content_disposition'
    s.add_dependency 'sax-machine'
    s.add_dependency 'bootstrap-will_paginate'
#    s.add_dependency 'logstash-filter-useragent'
    s.add_dependency 'write_xlsx'
    s.add_dependency 'easy_translate'
    s.add_dependency 'httpauth'
#    s.add_dependency 'dry-events'
    s.add_dependency 'pghero'
#    s.add_dependency 'logstash-input-syslog'
#    s.add_dependency 'logstash-filter-syslog_pri'
#    s.add_dependency 'logstash-filter-xml'
    s.add_dependency 'hirefire-resource'
    s.add_dependency 'cleanroom'
    s.add_dependency 'metadata-json-lint'
    s.add_dependency 'concurrent-ruby-ext'
    s.add_dependency 'rsolr'
#    s.add_dependency 'logstash-input-twitter'
#    s.add_dependency 'logstash-filter-date'
#    s.add_dependency 'logstash-input-exec'
    s.add_dependency 'dig_rb'
    s.add_dependency 'edn'
    s.add_dependency 'winrm-elevated'
    s.add_dependency 'tty-box'
    s.add_dependency 'rack-openid'
    s.add_dependency 'socketry'
    s.add_dependency 'fluent-plugin-throttle'
    s.add_dependency 'fluent-plugin-splunk-hec'
    s.add_dependency 'extlz4'
#    s.add_dependency 'logstash-input-pipe'
#    s.add_dependency 'logstash-input-snmptrap'
#    s.add_dependency 'logstash-input-unix'
    s.add_dependency 'rails_semantic_logger'
    s.add_dependency 'in_threads'
    s.add_dependency 'aws-sdk-ivschat'
    s.add_dependency 'lightly'
    s.add_dependency 'capybara-email'
#    s.add_dependency 'logstash-filter-aggregate'
    s.add_dependency 'inky-rb'
    s.add_dependency 'fastlane-plugin-versioning'
    s.add_dependency 'fspath'
#    s.add_dependency 'logstash-input-imap'
    s.add_dependency 'xmlenc'
    s.add_dependency 'stoplight'
    s.add_dependency 'soap4r-ruby1.9'
    s.add_dependency 'selectize-rails'
    s.add_dependency 'aws-sdk-gamesparks'
    s.add_dependency 'caxlsx_rails'
    s.add_dependency 'ruby-stemmer'
    s.add_dependency 'httmultiparty'
    s.add_dependency 'image_optim'
#    s.add_dependency 'logstash-output-sns'
    s.add_dependency 'time_difference'
    s.add_dependency 'split'
    s.add_dependency 'rubocop-sorbet'
    s.add_dependency 'persistent_http'
    s.add_dependency 'high_voltage'
    s.add_dependency 'parlour'
    s.add_dependency 'async-websocket'
    s.add_dependency 'active_link_to'
    s.add_dependency 'spdx-licenses'
    s.add_dependency 'fluent-plugin-out-http'
    s.add_dependency 'salesforce_bulk_query'
    s.add_dependency 'google-apis-sheets_v4'
    s.add_dependency 'pry-theme'
#    s.add_dependency 'logstash-mixin-http_client'
    s.add_dependency 'devise_token_auth'
#    s.add_dependency 'logstash-input-gelf'
    s.add_dependency 'ovirt-engine-sdk'
    s.add_dependency 'tapioca'
#    s.add_dependency 'logstash-input-sqs'
    s.add_dependency 'waterdrop'
    s.add_dependency 'minitest-rails'
    s.add_dependency 'azure_mgmt_resources'
}
