
  require 'rubygems'

Gem::Specification.new {|s|
    s.name          = 'top-1700-to-1800-gems'
    s.version       = '0.0.1'
    s.author        = 'naresh'
    s.email         = 'nareshdevasani@gmail.com'
    s.homepage      = 'http://github.com/nareshdevasani'
    s.platform      = Gem::Platform::RUBY
    s.summary       = 'An empty gem that depends on every gem available'
    s.description   = s.summary

    s.add_dependency 'actionpack-page_caching'
    s.add_dependency 'aws-sdk-backupgateway'
    s.add_dependency 'aws-sdk-inspector2'
    s.add_dependency 'fluent-plugin-newrelic'
    s.add_dependency 'delivery_boy'
    s.add_dependency 'daemon_controller'
    s.add_dependency 'exifr'
    s.add_dependency 'rr'
    s.add_dependency 'stomp'
    s.add_dependency 'authlogic'
    s.add_dependency 'memcache-client'
    s.add_dependency 'humanize'
    s.add_dependency 'omniauth_openid_connect'
    s.add_dependency 'cucumber-create-meta'
    s.add_dependency 'pronto'
#    s.add_dependency 'logstash-input-beats'
    s.add_dependency 'iso8601'
    s.add_dependency 'aws-sdk-workspacesweb'
    s.add_dependency 'archive-tar-minitar'
    s.add_dependency 'sd_notify'
    s.add_dependency 'active_utils'
    s.add_dependency 'json-diff'
    s.add_dependency 'stripe_event'
    s.add_dependency 'gmail_xoauth'
    s.add_dependency 'gene_pool'
    s.add_dependency 'ffi-libarchive'
    s.add_dependency 'data_magic'
    s.add_dependency 'undercover'
    s.add_dependency 'ruby-next-core'
    s.add_dependency 'jasmine'
    s.add_dependency 'language_server-protocol'
    s.add_dependency 'rubocop-rake'
    s.add_dependency 'libv8-node'
    s.add_dependency 'terminal-notifier-guard'
    s.add_dependency 'mongoid-compatibility'
    s.add_dependency 'beefcake'
    s.add_dependency 'active_storage_validations'
    s.add_dependency 'imagen'
    s.add_dependency 'barnes'
    s.add_dependency 'benchmark-perf'
    s.add_dependency 'tanuki_emoji'
    s.add_dependency 'react_on_rails'
    s.add_dependency 'pronto-rubocop'
    s.add_dependency 'cfn-nag'
    s.add_dependency 'yui-compressor'
    s.add_dependency 'jekyll-sitemap'
    s.add_dependency 'anyway_config'
    s.add_dependency 'launchdarkly-server-sdk'
    s.add_dependency 'twitter-bootstrap-rails'
    s.add_dependency 'timezone'
    s.add_dependency 'yml_reader'
    s.add_dependency 'rspec-benchmark'
    s.add_dependency 'aws-sdk-appconfigdata'
    s.add_dependency 'date_validator'
    s.add_dependency 'aws-sdk-amplifyuibuilder'
    s.add_dependency 'active_attr'
    s.add_dependency 'snmp'
    s.add_dependency 'xxhash'
    s.add_dependency 'docopt'
    s.add_dependency 'spork'
    s.add_dependency 'jekyll-seo-tag'
    s.add_dependency 'best_in_place'
    s.add_dependency 'aws-sdk-migrationhubstrategyrecommendations'
    s.add_dependency 'devise-security'
    s.add_dependency 'benchmark-trend'
    s.add_dependency 'html_tokenizer'
    s.add_dependency 'hamster'
    s.add_dependency 'cfn-model'
    s.add_dependency 'github_api'
    s.add_dependency 'benchmark-malloc'
    s.add_dependency 'aws-record'
    s.add_dependency 'capybara-webkit'
    s.add_dependency 'tender_hash'
    s.add_dependency 'net-http2'
    s.add_dependency 'rubocop-thread_safety'
    s.add_dependency 'minitest-retry'
    s.add_dependency 'rails-patch-json-encode'
    s.add_dependency 'rbnacl-libsodium'
    s.add_dependency 'omniauth-dingtalk-oauth2'
    s.add_dependency 'minitest-hooks'
    s.add_dependency 'aws-sdk-iottwinmaker'
    s.add_dependency 'cool.io'
    s.add_dependency 'ridley'
    s.add_dependency 'underscore-rails'
    s.add_dependency 'aws-sdk-cloudwatchrum'
    s.add_dependency 'mandrill-api'
    s.add_dependency 'tiny_tds'
    s.add_dependency 'hoe'
    s.add_dependency 'counter_culture'
    s.add_dependency 'aws-sdk-recyclebin'
    s.add_dependency 'hiera-dyml'
    s.add_dependency 'rack-pjax'
    s.add_dependency 'ougai'
    s.add_dependency 'libddwaf'
    s.add_dependency 'rails_admin'
    s.add_dependency 'pony'
    s.add_dependency 'roxml'
    s.add_dependency 'solve'
    s.add_dependency 'mongoid-paperclip'
    s.add_dependency 'stackdriver-core'
    s.add_dependency 'gmail'
}
