
  require 'rubygems'

Gem::Specification.new {|s|
    s.name          = 'pkg15'
    s.version       = '0.0.1'
    s.author        = 'Julio Capote'
    s.email         = 'jcapote@gmail.com'
    s.homepage      = 'http://github.com/capotej/trollface'
    s.platform      = Gem::Platform::RUBY
    s.summary       = 'An empty gem that depends on every gem available'
    s.description   = s.summary

    s.add_dependency 'chewy'
    s.add_dependency 'expgen'
    s.add_dependency 'image_optim_pack'
    s.add_dependency 'oink'
    s.add_dependency 'teaspoon-jasmine'
    s.add_dependency 'dpl-s3'
    s.add_dependency 'escalate'
    s.add_dependency 'active_material'
    s.add_dependency 'jemoji'
    s.add_dependency 'yaml-lint'
    s.add_dependency 'attr_comparable'
    s.add_dependency 'silencer'
    s.add_dependency 'proxies'
    s.add_dependency 'redis-session-store'
    s.add_dependency 'redis-prescription'
#    s.add_dependency 'aws-sdk-backupstorage'
    s.add_dependency 'js_cookie_rails'
    s.add_dependency 'di-ruby-lvm'
    s.add_dependency 'resque-cleaner'
    s.add_dependency 'email_address'
    s.add_dependency 'fig_leaf'
    s.add_dependency 'sunspot_rails'
    s.add_dependency 'google-apis-compute_v1'
    s.add_dependency 'facets'
    s.add_dependency 'iso-639'
    s.add_dependency 'arel-helpers'
    s.add_dependency 'opentelemetry-instrumentation-action_pack'
    s.add_dependency 'train-winrm'
    s.add_dependency 'http_tools'
    s.add_dependency 'jumphash'
    s.add_dependency 'chroma'
    s.add_dependency 'utf8-cleaner'
    s.add_dependency 'turnip'
    s.add_dependency 'attr_default'
#=begin
#    s.add_dependency 'logstash-input-jdbc'
    s.add_dependency 'fluent-plugin-rename-key'
    s.add_dependency 'azure-storage'
    s.add_dependency 'scrub_rb'
#    s.add_dependency 'logstash-filter-json_encode'
    s.add_dependency 'zeus'
    s.add_dependency 'servolux'
    s.add_dependency 'google-apis-sqladmin_v1beta4'
    s.add_dependency 'yaml_extend'
    s.add_dependency 'declare_schema'
    s.add_dependency 'slackistrano'
    s.add_dependency 'large_text_field'
    s.add_dependency 'activerecord-sqlserver-adapter'
#    s.add_dependency 'logstash-output-rabbitmq'
    s.add_dependency 'sorcery'
    s.add_dependency 'remote_syslog_logger'
    s.add_dependency 'exceptional_synchrony'
    s.add_dependency 'activerecord-mysql-enum'
    s.add_dependency 'constant_resolver'
    s.add_dependency 'openssl_pkcs8_pure'
    s.add_dependency 'amqp'
    s.add_dependency 'aws-xray-sdk'
    s.add_dependency 'fluent-plugin-group-exceptions'
#    s.add_dependency 'logstash-mixin-rabbitmq_connection'
    s.add_dependency 'capybara-selenium'
    s.add_dependency 'cloud_events'
    s.add_dependency 'spring-commands-cucumber'
    s.add_dependency 'did_you_mean'
    s.add_dependency 'easypost'
    s.add_dependency 'dpl-heroku'
    s.add_dependency 'google-apis-pubsub_v1'
    s.add_dependency 'graphlyte'
    s.add_dependency 'ruby_event_store'
#=begin
    s.add_dependency 'carrierwave-base64'
    s.add_dependency 'ruby-duration'
    s.add_dependency 'parameter_substitution'
    s.add_dependency 'bluecloth'
    s.add_dependency 'google-apis-monitoring_v3'
    s.add_dependency 'rpush'
    s.add_dependency 'paypal-sdk-core'
    s.add_dependency 'fastthread'
    s.add_dependency 'jsmin'
    s.add_dependency 'aws-sessionstore-dynamodb'
    s.add_dependency 'wkhtmltopdf-heroku'
    s.add_dependency 'fibered_mysql2'
#=begin
    s.add_dependency 'allure-cucumber'
    s.add_dependency 'her'
    s.add_dependency 'zonefile'
    s.add_dependency 'show_me_the_cookies'
    s.add_dependency 'har'
    s.add_dependency 'nexmo'
    s.add_dependency 'jschematic'
    s.add_dependency 'beaker'
#    s.add_dependency 'faraday-follow_redirects'
#    s.add_dependency 'aws-sdk-supportapp'
    s.add_dependency 'aggregate_root'
#    s.add_dependency 'logstash-output-pagerduty'
    s.add_dependency 'junit_merge'
    s.add_dependency 'http_router'
    s.add_dependency 'sorbet-static-and-runtime'
    s.add_dependency 'snitcher'
    s.add_dependency 'redic'
    s.add_dependency 'decent_exposure'
#    s.add_dependency 'logstash-filter-de_dot'
    s.add_dependency 'activerecord-jdbc-adapter'
    s.add_dependency 'ruby-trello'
#    s.add_dependency 'logstash-filter-cidr'
    s.add_dependency 'gretel'
    s.add_dependency 'nestful'
    s.add_dependency 'rails_event_store'
    s.add_dependency 'rails_event_store_active_record'
    s.add_dependency 'opentelemetry-instrumentation-active_record'
    s.add_dependency 'minitest-stub_any_instance'
    s.add_dependency 'powerbar'
    s.add_dependency 'gelfd'
}
