
  require 'rubygems'

Gem::Specification.new {|s|
    s.name          = 'pkg24'
    s.version       = '0.0.1'
    s.author        = 'naresh'
    s.email         = 'nareshdevasani@gmail.com'
    s.homepage      = 'http://github.com/nareshdevasani'
    s.platform      = Gem::Platform::RUBY
    s.summary       = 'An empty gem that depends on every gem available'
    s.description   = s.summary

    s.add_dependency 'html2slim'
    s.add_dependency 'hiera-eyaml-gpg'
    s.add_dependency 'jsonapi.rb'
    s.add_dependency 'toastr-rails'
    s.add_dependency 'act-fluent-logger-rails'
    s.add_dependency 'ffi-geos'
    s.add_dependency 'fancybox2-rails'
    s.add_dependency 'fastlane-plugin-get_version_name'
    s.add_dependency 'rails-perftest'
    s.add_dependency 'generator_spec'
    s.add_dependency 'mail_form'
    s.add_dependency 'ignorable'
    s.add_dependency 'hubspot-api-client'
    s.add_dependency 'duo_api'
    s.add_dependency 'minitest-matchers_vaccine'
    s.add_dependency 'ruby-ldap'
    s.add_dependency 'fastlane-plugin-json'
    s.add_dependency 'myslog'
    s.add_dependency 'etcd'
    s.add_dependency 'rspec_html_reporter'
    s.add_dependency 'vite_rails'
    s.add_dependency 'web_translate_it'
    s.add_dependency 'fastlane-plugin-xcconfig'
    s.add_dependency 'awsecrets'
    s.add_dependency 'zhong'
    s.add_dependency 'padrino-mailer'
    s.add_dependency 'jc-validates_timeliness'
    s.add_dependency 'ruby_audit'
    s.add_dependency 'presto-client'
    s.add_dependency 'activeresource-response'
    s.add_dependency 'logster'
    s.add_dependency 'latex-decode'
    s.add_dependency 'unicode-version'
    s.add_dependency 'jekyll-toc'
    s.add_dependency 'securerandom'
    s.add_dependency 'trailblazer-activity'
    s.add_dependency 'omnibus-ctl'
    s.add_dependency 'activejob-uniqueness'
    s.add_dependency 'padrino-gen'
    s.add_dependency 'maxmind-geoip2'
    s.add_dependency 'wirb'
    s.add_dependency 'fluent-plugin-mysqlslowquery'
    s.add_dependency 'switch_point'
    s.add_dependency 'google-cloud-datastore'
    s.add_dependency 'state_machines-audit_trail'
    s.add_dependency 'zaru'
    s.add_dependency 'guard-brakeman'
    s.add_dependency 'watchr'
    s.add_dependency 'dependabot-github_actions'
    s.add_dependency 'anbt-sql-formatter'
    s.add_dependency 'sextant'
    s.add_dependency 'forecast_io'
    s.add_dependency 'yabeda-puma-plugin'
    s.add_dependency 'padrino-admin'
    s.add_dependency 'onfido'
    s.add_dependency 'saddler-reporter-text'
    s.add_dependency 'saddler'
    s.add_dependency 'compact_index'
    s.add_dependency 'ruby-string-match-scorer'
    s.add_dependency 'database_cleaner-sequel'
    s.add_dependency 'sass-globbing'
    s.add_dependency 'slack-incoming-webhooks'
    s.add_dependency 'checkstyle_filter-git'
#    s.add_dependency 'logstash-input-log4j'
    s.add_dependency 'saddler-reporter-support-git'
    s.add_dependency 'raphael-rails'
    s.add_dependency 'minitest-rails-capybara'
    s.add_dependency 'google-cloud-speech'
    s.add_dependency 'dependency_checker'
    s.add_dependency 'netsuite'
    s.add_dependency 'saddler-reporter-github'
    s.add_dependency 'argon2'
    s.add_dependency 'pulpcore_client'
    s.add_dependency 'upsert'
    s.add_dependency 'minitest-capybara'
    s.add_dependency 'cronex'
    s.add_dependency 'cl'
    s.add_dependency 'knife-solo_data_bag'
    s.add_dependency 'browser-timezone-rails'
    s.add_dependency 'haml-edge'
#    s.add_dependency 'active_model-errors_details'
    s.add_dependency 'hoptoad_notifier'
    s.add_dependency 'declarative_authorization'
    s.add_dependency 'devise_masquerade'
    s.add_dependency 'easymon'
    s.add_dependency 'ember-rails'
    s.add_dependency 'graph'
    s.add_dependency 'cocoapods-generate'
    s.add_dependency 'spree_extension'
    s.add_dependency 'doorkeeper-mongodb'
    s.add_dependency 'fluent-plugin-array-spin'
    s.add_dependency 'rack-host-redirect'
    s.add_dependency 'saddler-reporter-support'
    s.add_dependency 'ibandit'
    s.add_dependency 'newrelic_plugin'
    s.add_dependency 'env_branch'
    s.add_dependency 'padrino'
    s.add_dependency 'carrot'
    s.add_dependency 'codacy-coverage'
    s.add_dependency 'trailblazer-context'
    s.add_dependency 'omniauth-instagram'
    s.add_dependency 'readline-history-restore'
    s.add_dependency 'tmuxinator'
    s.add_dependency 'google_contacts_api'
    s.add_dependency 'hrr_rb_ssh'
    s.add_dependency 'recurrence'
    s.add_dependency 'fork'
    s.add_dependency 'crypt_keeper'
    s.add_dependency 'active_scaffold'
    s.add_dependency 'rhcl'
    s.add_dependency 'dep_selector'
    s.add_dependency 'base32-crockford'
#    s.add_dependency 'prototype-rails'
    s.add_dependency 'popen4'
    s.add_dependency 'openssl-oaep'
    s.add_dependency 'command_runner_ng'
    s.add_dependency 'multiverse'
    s.add_dependency 'active_scheduler'
    s.add_dependency 'active_skin'
    s.add_dependency 'schema_plus_indexes'
    s.add_dependency 'zencoder'
    s.add_dependency 'postgres-copy'
    s.add_dependency 'knife-windows'
    s.add_dependency 'rails_email_preview'
    s.add_dependency 'command_line_reporter'
    s.add_dependency 'qiniu'
    s.add_dependency 'browserslist_useragent'
    s.add_dependency 'pry-meta'
#    s.add_dependency 'venice'
    s.add_dependency 'guard-jasmine'
    s.add_dependency 'sensu'
    s.add_dependency 'dice_bag'
    s.add_dependency 'search_object_graphql'
    s.add_dependency 'libnotify'
    s.add_dependency 'carrierwave_backgrounder'
    s.add_dependency 'subroutine'
    s.add_dependency 'jeff'
    s.add_dependency 'rbpdf-font'
    s.add_dependency 'sparkle_formation'
    s.add_dependency 'devise-bootstrap-views'
    s.add_dependency 'ffi-rzmq'
    s.add_dependency 'capistrano-stats'
    s.add_dependency 'sailthru-client'
    s.add_dependency 'rghost'
    s.add_dependency 'fitter-happier'
#    s.add_dependency 'logstash-input-lumberjack'
    s.add_dependency 'timestamped-scenarios'
    s.add_dependency 'tapp'
    s.add_dependency 'pry-inline'
    s.add_dependency 'singleton'
    s.add_dependency 'embulk-input-mysql'
    s.add_dependency 'cpf_validator'
    s.add_dependency 'ruby-augeas'
    s.add_dependency 'bootstrap-multiselect-rails'
    s.add_dependency 'unaccent'
    s.add_dependency 'puppet_pot_generator'
    s.add_dependency 'libarchive-ruby'
    s.add_dependency 'ci-queue'
#    s.add_dependency 'runoid'
    s.add_dependency 'win32-service'
    s.add_dependency 'semantic-ui-sass'
    s.add_dependency 'regstry'
    s.add_dependency 'font-awesome-sass-rails'
    s.add_dependency 'shakapacker'
    s.add_dependency 'anycable-core'
    s.add_dependency 'mutant'
    s.add_dependency 'unread'
    s.add_dependency 'store_model'
    s.add_dependency 'puppet-lint-undef_in_function-check'
    s.add_dependency 'state_machines-rspec'
    s.add_dependency 'nyan-cat-formatter'
    s.add_dependency 'lazy_priority_queue'
    s.add_dependency 'carrierwave_direct'
    s.add_dependency 'plissken'
    s.add_dependency 'fixture_builder'
    s.add_dependency 'activejob-traffic_control'
    s.add_dependency 'digest-murmurhash'
    s.add_dependency 'env_pull_request'
    s.add_dependency 'power-types'
#    s.add_dependency 'knife-solo'
    s.add_dependency 'minitest-junit'
    s.add_dependency 'metric_fu-Saikuro'
    s.add_dependency 'sewing_kit'
#    s.add_dependency 'rubocop-github'
    s.add_dependency 'bitcoin-ruby'
#    s.add_dependency 's3_website'
    s.add_dependency 'natural_number_string'
    s.add_dependency 'cascading.jruby'
    s.add_dependency 'working_hours'
    s.add_dependency 'gingerice'
    s.add_dependency 'google_visualr'
    s.add_dependency 'send_with_us'
    s.add_dependency 'event_bus'
    s.add_dependency 'webdriver-user-agent'
    s.add_dependency 'sidekiq-logging-json'
    s.add_dependency 'transaction-simple'
    s.add_dependency 'activerecord-mysql-index-hint'
    s.add_dependency 'zero_downtime_migrations'
    s.add_dependency 'danger-commit_lint'
    s.add_dependency 'knife-ec2'
#    s.add_dependency 'activerecord-mysql-awesome'
    s.add_dependency 'karafka-rdkafka'
    s.add_dependency 'fluent-plugin-grepcounter'
    s.add_dependency 'activestorage-validator'
    s.add_dependency 'google-cloud-dialogflow'
    s.add_dependency 'rlp'
#    s.add_dependency 'logstash-filter-elapsed'
    s.add_dependency 'p3p'
    s.add_dependency 'soapforce'
    s.add_dependency 'narray'
    s.add_dependency 'seed_migration'
    s.add_dependency 'oa-core'
    s.add_dependency 'jimson-temp'
    s.add_dependency 'semacode-ruby19'
    s.add_dependency 'SyslogLogger'
    s.add_dependency 'i18n-recursive-lookup'
    s.add_dependency 'resque-lock-timeout'
    s.add_dependency 'fixy'
    s.add_dependency 'filterrific'
    s.add_dependency 'jekyll-paginate-v2'
    s.add_dependency 'do_mysql'
#    s.add_dependency 'logstash-mixin-ecs_compatibility_support'
    s.add_dependency 'fluent-plugin-dedot_filter'
    s.add_dependency 'openssl-cmac'
    s.add_dependency 'bootbox-rails'
    s.add_dependency 'curses'
    s.add_dependency 'spring-commands-teaspoon'
    s.add_dependency 'sqreen-kit'
    s.add_dependency 'beaker-docker'
    s.add_dependency 'bosh_cpi'
    s.add_dependency 'rspec-example_steps'
    s.add_dependency 'era_ja'
    s.add_dependency 'kickbox'
    s.add_dependency 'csv_builder'
    s.add_dependency 'rakismet'
    s.add_dependency 'linecache19'
    s.add_dependency 'deepl-rb'
    s.add_dependency 'blockscore'
#    s.add_dependency 'rubocop-airbnb'
    s.add_dependency 'code_metrics'
    s.add_dependency 'cells-erb'
    s.add_dependency 'carrierwave-data-uri'
    s.add_dependency 'jasmine-jquery-rails'
    s.add_dependency 'otherinbox-crypt19'
    s.add_dependency 'peek-rblineprof'
    s.add_dependency 'blacklight'
    s.add_dependency 'google-cloud-firestore-v1'
#    s.add_dependency 'puppet_litmus'
    s.add_dependency 'mandrillus'
#    s.add_dependency 'gym'
    s.add_dependency 'canvas-api'
}
