
  require 'rubygems'

Gem::Specification.new {|s|
    s.name          = 'pkg29'
    s.version       = '0.0.1'
    s.author        = 'Naresh Devasani'
    s.email         = 'naresh@endor.ai'
    s.homepage      = 'http://github.com/capotej/trollface'
    s.platform      = Gem::Platform::RUBY
    s.summary       = 'An empty gem that depends on every gem available'
    s.description   = s.summary

    s.add_dependency 'jekyll-last-modified-at'
    s.add_dependency 'sparql-client'
    s.add_dependency 'dry-transformer'
    s.add_dependency 'bundler-leak'
    s.add_dependency 'gridster-rails'
    s.add_dependency 'wine_bouncer'
    s.add_dependency 'rmail'
    s.add_dependency 'fhir_models'
    s.add_dependency 'globalize3'
#    s.add_dependency 'bd_pod_extentions'
    s.add_dependency 'io-extra'
    s.add_dependency 'active_admin_import'
    s.add_dependency 'chozo'
#    s.add_dependency 'bandwidth-sdk'
    s.add_dependency 'queue_classic'
    s.add_dependency 'ruby-supervisor'
    s.add_dependency 'zscheduler'
    s.add_dependency 'bootstrap-sass-rails'
    s.add_dependency 'color-converter'
    s.add_dependency 'area'
#    s.add_dependency 'aws-es-transport'
    s.add_dependency 'webpack-assets'
    s.add_dependency 'populator'
    s.add_dependency 'jsonapi-utils'
    s.add_dependency 'marionette-rails'
    s.add_dependency 'phraseapp-in-context-editor-ruby'
    s.add_dependency 'moment-timezone-rails'
    s.add_dependency 'instana'
    s.add_dependency 'omniauth-oktaoauth'
    s.add_dependency 'sensu-plugins-docker'
    s.add_dependency 'hydra-head'
    s.add_dependency 'rubigen'
    s.add_dependency 'rschema'
    s.add_dependency 'ember-handlebars-template'
    s.add_dependency 'pgsync'
    s.add_dependency 'envied'
    s.add_dependency 'rekey'
    s.add_dependency 'encrypted_cookie_store-instructure'
    s.add_dependency 'pluckit'
#    s.add_dependency 'logstash-core'
#    s.add_dependency 'google-cloud-os_login'
    s.add_dependency 'permanent_records'
    s.add_dependency 'draper-cancancan'
    s.add_dependency 'rpush-redis'
    s.add_dependency 'symbol-fstring'
    s.add_dependency 'combined_time_select'
    s.add_dependency 'hogan_assets'
    s.add_dependency 'bitarray'
    s.add_dependency 'doorkeeper-grants_assertion'
    s.add_dependency 'hightop'
    s.add_dependency 'json-emitter'
    s.add_dependency 'solidus_braintree'
    s.add_dependency 'miasma-azure'
    s.add_dependency 'webmock-twirp'
    s.add_dependency 'nested_set'
#    s.add_dependency 'jenkins'
    s.add_dependency 'constantcontact'
    s.add_dependency 'guard-coffeescript'
    s.add_dependency 'bosh-director-core'
    s.add_dependency 'unsplash'
    s.add_dependency 'plu'
    s.add_dependency 'looksee'
    s.add_dependency 'confiner'
    s.add_dependency 'capistrano-resque'
    s.add_dependency 'clbustos-rtf'
#    s.add_dependency 'foursquare2'
    s.add_dependency 'exiftool'
    s.add_dependency 'sib-api-v3-sdk'
    s.add_dependency 'jquery-timepicker-rails'
    s.add_dependency 'ip3country'
    s.add_dependency 'debride'
    s.add_dependency 'adobe_connect'
    s.add_dependency 'i18n-timezones'
    s.add_dependency 'faraday_curl'
    s.add_dependency 'rubydraw'
    s.add_dependency 'rubocop-flexport'
    s.add_dependency 'ammeter'
    s.add_dependency 'iso-iban'
    s.add_dependency 'chatwork'
    s.add_dependency 'heap'
    s.add_dependency 'departure'
    s.add_dependency 'pronto-scss'
    s.add_dependency 'miasma-google'
    s.add_dependency 'awesome_bot'
    s.add_dependency 'scale_down'
    s.add_dependency 'aws-ssm-env'
    s.add_dependency 'bootstrap4-datetime-picker-rails'
    s.add_dependency 'chef-solr'
    s.add_dependency 'fluent-plugin-jq'
#    s.add_dependency 'logstash-mixin-deprecation_logger_support'
    s.add_dependency 'pry-awesome_print'
#    s.add_dependency 'middleman-minify-html'
    s.add_dependency 'base64'
    s.add_dependency 'rails_4_session_flash_backport'
    s.add_dependency 'good_job'
    s.add_dependency 'hprose'
    s.add_dependency 'memcached_store'
    s.add_dependency 'rspec_honeycomb_formatter'
    s.add_dependency 'pango'
    s.add_dependency 'gcra'
    s.add_dependency 'thor-scmversion'
    s.add_dependency 'miasma-terraform'
    s.add_dependency 'viewcumber'
    s.add_dependency 'jekyll-algolia'
    s.add_dependency 'configparser'
    s.add_dependency 'apiaryio'
    s.add_dependency 'parse-ruby-client'
    s.add_dependency 'wbconfigurator'
    s.add_dependency 'font-awesome-less'
#    s.add_dependency 'simple_blobstore_server'
    s.add_dependency 'hash_mapper'
    s.add_dependency 'mongoid_migrations'
    s.add_dependency 'em-postgres'
    s.add_dependency 'aws-sdk-ivsrealtime'
    s.add_dependency 'yinum'
    s.add_dependency 'phrase'
    s.add_dependency 'fluent-plugin-filter_keys'
    s.add_dependency 'graphql-anycable'
    s.add_dependency 'hippie_csv'
    s.add_dependency 'apparition'
    s.add_dependency 'notifications-ruby-client'
    s.add_dependency 'modular-scale'
    s.add_dependency 'pact-message'
    s.add_dependency 'rdf-vocab'
    s.add_dependency 'json-schema-generator'
    s.add_dependency 'wavefront-sdk'
    s.add_dependency 'aasm-diagram'
    s.add_dependency 'ztk'
    s.add_dependency 'net_tcp_client'
    s.add_dependency 'fastlane-plugin-huawei_appgallery_connect'
    s.add_dependency 'net-ftp-list'
    s.add_dependency 'toolkit'
    s.add_dependency 'eth'
    s.add_dependency 'java_properties'
    s.add_dependency 'valid_attribute'
    s.add_dependency 'minitest-profile'
    s.add_dependency 'api_matchers'
    s.add_dependency 'oai'
    s.add_dependency 'aws_data'
    s.add_dependency 'algolia_html_extractor'
    s.add_dependency 'picky-client'
    s.add_dependency 'stimulus_reflex'
    s.add_dependency 'sequel_enum'
    s.add_dependency 'fluent-plugin-redaction'
    s.add_dependency 'twiliolib'
    s.add_dependency 'singularitygs'
    s.add_dependency 'pulp_deb_client'
    s.add_dependency 'prawnto'
    s.add_dependency 'omniauth-cas'
    s.add_dependency 'engineyard-cloud-client'
    s.add_dependency 'graphql-preload'
    s.add_dependency 'aptible-api'
    s.add_dependency 'regexp-examples'
    s.add_dependency 'fluent-plugin-docker'
    s.add_dependency 'grape-roar'
    s.add_dependency 'email_verifier'
    s.add_dependency 'faraday-decode_xml'
    s.add_dependency 'forked'
    s.add_dependency 'loggability'
    s.add_dependency 'jira_ref_parser'
    s.add_dependency 'oop-interface'
    s.add_dependency 'morpher'
    s.add_dependency 'flag-icons-rails'
    s.add_dependency 'compass-normalize'
    s.add_dependency 'pulp_maven_client'
    s.add_dependency 'application_seeds'
    s.add_dependency 'pjax_rails'
    s.add_dependency 'kitchen-google'
    s.add_dependency 'multi-select-rails'
    s.add_dependency 'rVM'
#    s.add_dependency 'resque-metrics'
    s.add_dependency 'mongoid-simple-tags'
    s.add_dependency 'quaderno'
    s.add_dependency 'compass-blueprint'
    s.add_dependency 'effective_datatables'
    s.add_dependency 'rein'
    s.add_dependency 'time_with_zone'
#    s.add_dependency 'sinatra-asset-pipeline'
    s.add_dependency 'absolute_time'
    s.add_dependency 'minispec-metadata'
    s.add_dependency 'archer-rails'
    s.add_dependency 'rack-lineprof'
    s.add_dependency 'thread-local'
    s.add_dependency 'canvas_connect'
    s.add_dependency 'dm-mysql-adapter'
    s.add_dependency 'jstz-rails3-plus'
    s.add_dependency 'google-cloud-bigquery-data_transfer'
    s.add_dependency 'jar_wrapper'
    s.add_dependency 'ambry'
    s.add_dependency 'ftw'
    s.add_dependency 'lookbook'
    s.add_dependency 'redis-instrumentation'
    s.add_dependency 'nokogiri-xmlsec-instructure'
    s.add_dependency 'activeadmin_reorderable'
    s.add_dependency 'cloudformation-ruby-dsl'
    s.add_dependency 'ap'
    s.add_dependency 'haml-lint'
    s.add_dependency 'edge_rider'
    s.add_dependency 'minitest-spec-context'
    s.add_dependency 'gaffe'
    s.add_dependency 'verdict'
    s.add_dependency 'mysql2-aurora'
    s.add_dependency 'sensu-settings'
    s.add_dependency 'intuit-oauth'
    s.add_dependency 'puppet-lint-numericvariable'
    s.add_dependency 'vagrant-hostsupdater'
    s.add_dependency 'cvss'
#    s.add_dependency 'omniauth-ldap'
    s.add_dependency 'grape-swagger-ui'
    s.add_dependency 'albino'
    s.add_dependency 'jquery_file_download-rails'
    s.add_dependency 'bugsnag-capistrano'
    s.add_dependency 'ruby-jq'
    s.add_dependency 'refining'
#    s.add_dependency 'screengrab'
    s.add_dependency 'pry-git'
    s.add_dependency 'gcewinpass'
    s.add_dependency 'fluent-plugin-loggly'
    s.add_dependency 'json-ld-preloaded'
    s.add_dependency 'sinatra-health-check'
#    s.add_dependency 'krausefx-shenzhen'
    s.add_dependency 'easyrsa'
    s.add_dependency 'acts_as_indexed'
    s.add_dependency 'dynflow'
    s.add_dependency 'fluent-plugin-webhdfs'
#    s.add_dependency 'wisper-resque'
    s.add_dependency 'rightsignature'
    s.add_dependency 'hyperclient'
    s.add_dependency 'normalize_country'
    s.add_dependency 'good_migrations'
    s.add_dependency 'schema_plus_foreign_keys'
    s.add_dependency 'csv-safe'
    s.add_dependency 'ruby-geometry'
#    s.add_dependency 'inspec-bin'
    s.add_dependency 'sidekiq-cloudwatchmetrics'
    s.add_dependency 'justify'
    s.add_dependency 'resque-history'
    s.add_dependency 'opal'
    s.add_dependency 'lock_manager'
    s.add_dependency 'cli-format'
    s.add_dependency 'querly'
    s.add_dependency 'yaml_vault'
    s.add_dependency 'shopify-cli'
    s.add_dependency 'sugarcube'
    s.add_dependency 'tinymce-rails-langs'
    s.add_dependency 'hstore_translate'
    s.add_dependency 'kitchen-ansiblepush'
    s.add_dependency 'sidekiq-statsd'
    s.add_dependency 'embulk'
    s.add_dependency 'alchemy_cms'
}
