
  require 'rubygems'

Gem::Specification.new {|s|
    s.name          = 'pkg45'
    s.version       = '0.0.1'
    s.author        = 'Naresh Devasani'
    s.email         = 'naresh@endor.ai'
    s.homepage      = 'http://github.com/capotej/trollface'
    s.platform      = Gem::Platform::RUBY
    s.summary       = 'An empty gem that depends on every gem available'
    s.description   = s.summary

    s.add_dependency 'rails-instrumentation'
    s.add_dependency 'spring-commands-sidekiq'
    s.add_dependency 'resque-queue-priority'
    s.add_dependency 'clearbit-slack'
    s.add_dependency 'ltsvr'
    s.add_dependency 'effective_test_bot'
    s.add_dependency 'ams_lazy_relationships'
    s.add_dependency 'ratom'
    s.add_dependency 'almond-rails'
    s.add_dependency 'jekyll-livereload'
    s.add_dependency 'proxylocal'
    s.add_dependency 'vagrant-winnfsd'
    s.add_dependency 'pothoven-attachment_fu'
    s.add_dependency 'tubesock'
    s.add_dependency 'merb-param-protection'
    s.add_dependency 'google-cloud-automl'
    s.add_dependency 'shoulda-kept-assign-to'
    s.add_dependency 'jekyll-autoprefixer'
    s.add_dependency 'authentasaurus'
    s.add_dependency 'apicake'
    s.add_dependency 'devise_invalidatable'
    s.add_dependency 'winevt_c'
    s.add_dependency 'gem-ctags'
    s.add_dependency 'buffered-logger'
    s.add_dependency 'dpl-rubygems'
#    s.add_dependency 'decidim-admin'
    s.add_dependency 'ruby-vnc'
    s.add_dependency 'naturalsorter'
    s.add_dependency 'octopress-ink'
    s.add_dependency 'dockly'
#    s.add_dependency 'metanorma-itu'
    s.add_dependency 'geoip_city'
    s.add_dependency 'rbbt-sources'
    s.add_dependency 'fitgem'
    s.add_dependency 'cocoapods-patch'
    s.add_dependency 'shadow_puppet'
    s.add_dependency 'data_cleansing'
    s.add_dependency 'magic'
#    s.add_dependency 'fwtoolkit'
    s.add_dependency 'bind-it'
    s.add_dependency 'activesupport-inflector'
    s.add_dependency 'device_cloud'
#    s.add_dependency 'newrelic-faraday'
    s.add_dependency 'awesome_translations'
#    s.add_dependency 'jekyll-octicons_v2'
    s.add_dependency 'paquito'
    s.add_dependency 'flvtool2'
#    s.add_dependency 'decidim-system'
    s.add_dependency 'freetype'
    s.add_dependency 'cloudformer'
    s.add_dependency 'compare_linker'
    s.add_dependency 'cuke_linter'
    s.add_dependency 'effin_utf8'
    s.add_dependency '4info'
    s.add_dependency 'deltavista_crif_dva_interface'
    s.add_dependency 'timber-rack'
    s.add_dependency 'sync_attr'
    s.add_dependency 'experian'
    s.add_dependency 'yard-api'
    s.add_dependency 'tty-pie'
    s.add_dependency 'fluent-plugin-label-router'
    s.add_dependency 'forever_style_guide'
    s.add_dependency 'blazing'
    s.add_dependency 'async-http-cache'
    s.add_dependency 'merb-slices'
    s.add_dependency 'mspire'
    s.add_dependency 'delorean_lang'
    s.add_dependency 'gitlab-turbolinks-classic'
#    s.add_dependency 'mobilize-base'
    s.add_dependency 'hobo_fields'
    s.add_dependency 'train-rest'
    s.add_dependency 'jquery-modal-rails-assets'
    s.add_dependency 'kaminari-cells'
    s.add_dependency 'spec_cat'
    s.add_dependency 'obf'
    s.add_dependency 'rally_api'
    s.add_dependency 'system'
    s.add_dependency 'kasket'
#    s.add_dependency 'maremma'
    s.add_dependency 'cats_core'
    s.add_dependency 'dpl-cloud66'
    s.add_dependency 'toastr_rails'
    s.add_dependency 'pronto-slim_lint'
#    s.add_dependency 'simple-line-icons-rails'
    s.add_dependency 'angularjs-file-upload-rails'
    s.add_dependency 'bamboo-id'
    s.add_dependency 'mina-whenever'
    s.add_dependency 'niceogiri'
    s.add_dependency 'jekyll-import'
    s.add_dependency 'plain-david'
    s.add_dependency 'format_parser'
    s.add_dependency 'escher'
#    s.add_dependency 'html5-rails'
    s.add_dependency 'oulu'
    s.add_dependency 'filecluster'
    s.add_dependency 'apt_stage_artifacts'
    s.add_dependency 'query_relation'
    s.add_dependency 'roar-jsonapi'
    s.add_dependency 'addressabler'
    s.add_dependency 'O_o'
#    s.add_dependency 'gitcycle'
    s.add_dependency 'ups_shipping'
    s.add_dependency 'sambal'
    s.add_dependency 'relishable'
    s.add_dependency 'tidy_ffi'
    s.add_dependency 'nanoc-core'
    s.add_dependency 'sidekiq-debounce'
    s.add_dependency 'font-kit-rails'
    s.add_dependency 'rails-autoscale-sidekiq'
    s.add_dependency 'wechat'
    s.add_dependency 'flutter_analyze_parser'
    s.add_dependency 'hammer_cli'
    s.add_dependency 'double_entry'
    s.add_dependency 'xlsx_writer'
    s.add_dependency 'circleci-bundle-update-pr'
    s.add_dependency 'decoder'
    s.add_dependency 'fear-rspec'
    s.add_dependency 'traject'
#    s.add_dependency 'intercom-rubocop'
    s.add_dependency 'openstack'
    s.add_dependency 'link-header-parser'
    s.add_dependency 'active_storage_silent_logs'
    s.add_dependency 'qless'
    s.add_dependency 'boxer'
    s.add_dependency 'lita-whois'
#    s.add_dependency 'octicons_v2_helper'
    s.add_dependency 'exceptions_tree'
    s.add_dependency 'bcl'
    s.add_dependency 'coinbase'
    s.add_dependency 'ar-ondemand'
#    s.add_dependency 'ethereum.rb'
    s.add_dependency 'decidim-api'
    s.add_dependency 'red-datasets'
    s.add_dependency 'mongoid_auto_increment'
#    s.add_dependency 'flok'
    s.add_dependency 'tramway-landing'
    s.add_dependency 'retry_it'
    s.add_dependency 'fingerprintless'
    s.add_dependency 'excel_to_code'
#    s.add_dependency 'ramsey_cop'
    s.add_dependency 'vcr-archive'
    s.add_dependency 'gitlab-exporter'
    s.add_dependency 'armitage-rubocop'
    s.add_dependency 'rack-jsonp-middleware'
    s.add_dependency 'chef-provisioning-vsphere'
    s.add_dependency 'google-cloud-phishing_protection'
    s.add_dependency 'flavour_saver'
    s.add_dependency 'polymer-rails'
#    s.add_dependency 'dm-devise'
    s.add_dependency 'papermill'
    s.add_dependency 'alephant-broker'
#    s.add_dependency 'phctheme1'
    s.add_dependency 'Afip'
#    s.add_dependency 'rjack-icu'
    s.add_dependency 'cfn_camelizer'
    s.add_dependency 'git-revision'
    s.add_dependency 'ole-qa-framework'
    s.add_dependency 'formatted_rails_logger'
#    s.add_dependency 'medivo'
    s.add_dependency 'eassl2'
    s.add_dependency 'mturk'
    s.add_dependency 'teaspoon-qunit'
    s.add_dependency 'rack-session-sequel'
#    s.add_dependency 'simplecov-buildkite'
    s.add_dependency 'in_batches'
    s.add_dependency 'google-geocode'
    s.add_dependency 'send_nsca'
    s.add_dependency 'faraday-request-timer'
    s.add_dependency 'rudy'
    s.add_dependency 'ssl_requirement'
    s.add_dependency 'sinatra-jsonp'
    s.add_dependency 'dim'
    s.add_dependency 'rua'
    s.add_dependency 'redis-key_hash'
#    s.add_dependency 'buildr-as3'
    s.add_dependency 'markdown-tables'
    s.add_dependency 'acts_as_markup'
#    s.add_dependency 'linecook-gem'
    s.add_dependency 'mtg-db'
    s.add_dependency 'el_finder'
    s.add_dependency 'faceted'
    s.add_dependency 'flexbox-rails'
#    s.add_dependency 'rjack-jetty'
    s.add_dependency 'iev'
    s.add_dependency 'spidr'
    s.add_dependency 'nofxx-subtitle_it'
    s.add_dependency 'govuk-components'
    s.add_dependency 'missing_validators'
    s.add_dependency 'buildkite-builder'
    s.add_dependency 'ocunit2junit'
    s.add_dependency 'onstomp'
    s.add_dependency 'fredric'
    s.add_dependency 'classiccms'
    s.add_dependency 'ultracart_api'
    s.add_dependency 'ir_b'
    s.add_dependency 'rubocop-migration'
    s.add_dependency 'dirty_hashy'
    s.add_dependency 'identicon'
    s.add_dependency 'mysql2-cs-bind'
    s.add_dependency 'sunspot_stats'
    s.add_dependency 'youtube-dl.rb'
#    s.add_dependency 'meta_where'
    s.add_dependency 'simplecov-summary'
    s.add_dependency 'slyphon-log4j'
    s.add_dependency 'descartes'
    s.add_dependency 'activemessaging'
    s.add_dependency 'rspec-virtus'
    s.add_dependency 'asciidoctor-revealjs'
    s.add_dependency 'mash'
    s.add_dependency 'active_encode'
    s.add_dependency 'opal-rails'
    s.add_dependency 'simp-rspec-puppet-facts'
    s.add_dependency 'sapphire'
#    s.add_dependency 'quandl_client'
    s.add_dependency 'active_job_status'
    s.add_dependency 'extended_range'
    s.add_dependency 'dpl-deis'
#    s.add_dependency 'capybara-user_agent'
    s.add_dependency 'runby_pace'
    s.add_dependency 'library_stdnums'
    s.add_dependency 'bard-rake'
    s.add_dependency 'phpass-ruby'
    s.add_dependency 'ostruct-sanitizer'
    s.add_dependency 'omniauth-microsoft_v2_auth'
    s.add_dependency 'rails_dt'
    s.add_dependency 'require-prof'
    s.add_dependency 'zliby'
    s.add_dependency 'stella'
    s.add_dependency 'chartist-rails'
#    s.add_dependency 'arvados-login-sync'
    s.add_dependency 'brice'
    s.add_dependency 'fleetio_spark'
    s.add_dependency 'm-git'
    s.add_dependency 'devise_google_authenticator'
    s.add_dependency 'capistrano-ssh-doctor'
    s.add_dependency 'reactor'
    s.add_dependency 'beanstalker'
    s.add_dependency 'mina-unicorn'
    s.add_dependency 'fastlane-plugin-waldo'
    s.add_dependency 'embulk-output-postgresql'
    s.add_dependency 'ubuntu_ami'
    s.add_dependency 'google-apis-analyticsreporting_v4'
#    s.add_dependency 'actionmailer-callbacks'
    s.add_dependency 'epub-parser'
    s.add_dependency 'value_object-ruby'
    s.add_dependency 'tokenizer'
    s.add_dependency 'faml'
    s.add_dependency 'octopress-autoprefixer'
    s.add_dependency 'capistrano-hivequeen'
    s.add_dependency 'shrine-mongoid'

}
