
  require 'rubygems'

Gem::Specification.new {|s|
    s.name          = 'pkg42'
    s.version       = '0.0.1'
    s.author        = 'Naresh Devasani'
    s.email         = 'naresh@endor.ai'
    s.homepage      = 'http://github.com/capotej/trollface'
    s.platform      = Gem::Platform::RUBY
    s.summary       = 'An empty gem that depends on every gem available'
    s.description   = s.summary

    s.add_dependency 'dbd-pg'
    s.add_dependency 'mumuki-laboratory'
    s.add_dependency 'spin'
    s.add_dependency 'dor-services-client'
    s.add_dependency 'creditcard'
    s.add_dependency 'rturk'
    s.add_dependency 'sentimental'
    s.add_dependency 'iif-parser'
    s.add_dependency 'azure-loganalytics-datacollector-api'
    s.add_dependency 'opsmgr'
    s.add_dependency 'tickethub'
    s.add_dependency 'openpgp'
    s.add_dependency 'danger-prose'
    s.add_dependency 'opener-core'
    s.add_dependency 'omise'
    s.add_dependency 'procodile'
    s.add_dependency 'learn-co'
    s.add_dependency 'merb'
    s.add_dependency 'readapt'
    s.add_dependency 'carrierwave-postgresql'
    s.add_dependency 'es-reindex'
    s.add_dependency 'fluent-plugin-auto-typecast-filter'
    s.add_dependency 'jdoc'
    s.add_dependency 'dag'
    s.add_dependency 'knife-cookbook-doc'
    s.add_dependency 'markdown'
    s.add_dependency 'rails_stats'
    s.add_dependency 'kickstart_rails'
    s.add_dependency 'bookends'
    s.add_dependency 'mem'
    s.add_dependency 'gov_uk_date_fields'
    s.add_dependency 'redis-stat'
    s.add_dependency 'ember-es6_template'
    s.add_dependency 'carrierwave-serializable'
    s.add_dependency 'simpacker'
    s.add_dependency 'active_admin_scoped_collection_actions'
    s.add_dependency 'belzebuth'
    s.add_dependency 'rails-autoscale-core'
    s.add_dependency 'scribe'
    s.add_dependency 'fog-vcloud-director'
    s.add_dependency 'firebase_dynamic_link'
    s.add_dependency 'iron_worker'
    s.add_dependency 'utilrb'
    s.add_dependency 'gems-status'
    s.add_dependency 'googleajax'
    s.add_dependency 'log-me'
    s.add_dependency 'serfx'
    s.add_dependency 'rspectacular'
    s.add_dependency 'do_oracle'
#    s.add_dependency 'tn_s3_file_uploader'
    s.add_dependency 'lmdb'
    s.add_dependency 'google-apis-fcm_v1'
    s.add_dependency 'grape-attack'
    s.add_dependency 'robottelo_reporter'
    s.add_dependency 'zendesk_remote_auth'
    s.add_dependency 'garner'
    s.add_dependency 'radius'
    s.add_dependency 'guard-annotate'
    s.add_dependency 'jquery-countdown-rails'
    s.add_dependency 'relaton-ogc'
    s.add_dependency 'abiquo-etk'
    s.add_dependency 'guard-rubycritic'
#    s.add_dependency 'hotwire-livereload'
    s.add_dependency 'rails-autoscale-web'
    s.add_dependency 'embulk-output-salesforce'
    s.add_dependency 'xmpp4r_facebook'
    s.add_dependency 'annoy'
    s.add_dependency 'talentbox-delayed_job_sequel'
    s.add_dependency 'medea'
    s.add_dependency 'saml-kit'
    s.add_dependency 'grape-raketasks'
    s.add_dependency '360_services'
    s.add_dependency 'gengo'
    s.add_dependency 'country_state_select'
    s.add_dependency 'kmeans-clusterer'
    s.add_dependency 'danger-the_coding_love'
    s.add_dependency 'abstract_notifier'
    s.add_dependency 'gemwarrior'
    s.add_dependency 'rc-rest'
    s.add_dependency 'yard-tomdoc'
    s.add_dependency 'rubocop-inflector'
    s.add_dependency 'firewatir'
    s.add_dependency 'dpl-lambda'
    s.add_dependency 'ebayr'
    s.add_dependency 'logging-journald'
    s.add_dependency 'active_paypal_adaptive_payment'
    s.add_dependency 'wkhtmltopdf-binary-edge-alpine'
    s.add_dependency 'material_design_lite-sass'
    s.add_dependency 'compass-aurora'
    s.add_dependency 'puppetserver-ca'
    s.add_dependency 'spree_auth'
    s.add_dependency 'nps_sdk'
    s.add_dependency 'myreplicator'
    s.add_dependency 'jsonapi_compliable'
    s.add_dependency 'elastic-beanstalk'
    s.add_dependency 'activerecord-postgres-array'
#    s.add_dependency 'chef-bin'
    s.add_dependency 'lisbn'
#    s.add_dependency 'metadata_presenter'
    s.add_dependency 'fake_dynamo'
    s.add_dependency 'elastic_record'
    s.add_dependency 'activerecord-immutable'
    s.add_dependency 'protocol-websocket'
    s.add_dependency 'enju_event'
    s.add_dependency 'faraday_middleware-circuit_breaker'
    s.add_dependency 'yaml2json'
    s.add_dependency 'google-cloud-language-v1beta2'
    s.add_dependency 'omniauth-xero-oauth2'
    s.add_dependency 'cocoapods-rome'
    s.add_dependency 'mongoid_includes'
    s.add_dependency 'fastlane-plugin-git_tags'
    s.add_dependency 'capistrano-linked-files'
    s.add_dependency 'prettyprint'
    s.add_dependency 'magic_stylez'
    s.add_dependency 'terraspace-bundler'
#    s.add_dependency 'canvas_sync'
    s.add_dependency 'omniauth-odnoklassniki'
    s.add_dependency 'brief'
    s.add_dependency 'less-rails-semantic_ui'
    s.add_dependency 'harness'
#    s.add_dependency 'purecloudplatformclientv2'
    s.add_dependency 'barber-emblem'
    s.add_dependency 'color-tools'
    s.add_dependency 'dry-validation-matchers'
    s.add_dependency 'simple_states'
    s.add_dependency 'routes_lazy_routes'
    s.add_dependency 'google-cloud-language-v1'
    s.add_dependency 'breakout_parser'
    s.add_dependency 'jrmonitor'
    s.add_dependency 'trailblazer-test'
    s.add_dependency 'golf'
    s.add_dependency 'custom_fields'
    s.add_dependency 'sinatra_auth_github'
    s.add_dependency 'virtualbox'
    s.add_dependency 'acts_as_textcaptcha'
    s.add_dependency 'kiba-common'
    s.add_dependency 'danger-welcome_message'
    s.add_dependency 'rack-link_headers'
    s.add_dependency 'pack_stats'
    s.add_dependency 'tomparse'
    s.add_dependency 'tiller'
    s.add_dependency 'capistrano-unicorn-nginx'
#    s.add_dependency 'dm-rails'
    s.add_dependency 'tel_formatter'
    s.add_dependency 'turbo_tests'
#    s.add_dependency 'stretcher'
    s.add_dependency 'graphql_devise'
    s.add_dependency 'net-dns2'
#    s.add_dependency 'microsoft_graph'
    s.add_dependency 'multipart'
    s.add_dependency 'optout'
    s.add_dependency 'isoics'
#    s.add_dependency 'xcpretty-bb'
    s.add_dependency 'ey_api_hmac'
    s.add_dependency 'yt-support'
    s.add_dependency 'graphql-active_record'
    s.add_dependency 'puppet-lint-world_writable_files-check'
    s.add_dependency 'unicode-types'
    s.add_dependency 'sidekiq_status'
    s.add_dependency 'command_lion'
    s.add_dependency 'riiif'
#    s.add_dependency 'terrafying-components'
    s.add_dependency 'zero-rails_openapi'
    s.add_dependency 'malloc_trim'
    s.add_dependency 'freeswitcher'
    s.add_dependency 'text-format'
    s.add_dependency 'simple_sitemap'
    s.add_dependency 'win32-certstore'
    s.add_dependency 'spree_zone_pricing'
    s.add_dependency 'encrypto_signo'
    s.add_dependency 'rotoscope'
    s.add_dependency 'analyst'
#    s.add_dependency 'faraday-typhoeus'
    s.add_dependency 'finishing_moves'
    s.add_dependency 'puppet-lint-param-types'
#    s.add_dependency 'social_stream-documents'
    s.add_dependency 'ruby-magic-static'
#    s.add_dependency 'blacklight-access_controls'
    s.add_dependency 'its'
    s.add_dependency 'athena_health'
    s.add_dependency 'capistrano-bundle_rsync'
    s.add_dependency 'activejob-cancel'
    s.add_dependency 'bel_parser'
    s.add_dependency 'adops_report_scrapper'
    s.add_dependency 'reality-naming'
    s.add_dependency 'hakiri'
    s.add_dependency 'mock_search'
    s.add_dependency 'camaleon_cms'
    s.add_dependency 'spectator-validates_email'
    s.add_dependency 'cache_method'
    s.add_dependency 'pdfcrowd'
    s.add_dependency 'mongoid-paranoia'
    s.add_dependency 'capistrano-systemd-multiservice'
    s.add_dependency 'bootstrap-sass-extras'
#    s.add_dependency 'faraday-sunset'
    s.add_dependency 'card'
    s.add_dependency 'ruby_info'
    s.add_dependency 'squash_ruby'
    s.add_dependency 'xclarity_client'
    s.add_dependency 'viki-api'
    s.add_dependency 'reqres_rspec'
    s.add_dependency 'bigcommerce'
    s.add_dependency 'activerecord-shard_for'
    s.add_dependency 'image_optim_rails'
    s.add_dependency 'dns-zone'
    s.add_dependency 'BlueCloth'
    s.add_dependency 'google-maps'
#    s.add_dependency 'capdocker'
    s.add_dependency 'oni'
    s.add_dependency 'libxml4r'
    s.add_dependency 'vagrant-lxc'
    s.add_dependency 'rails_admin_rollincode'
    s.add_dependency 'groonga-query-log'
    s.add_dependency 'case_transform2'
    s.add_dependency 'diff_matcher'
    s.add_dependency 'ec2launcher'
    s.add_dependency 'upmark'
#    s.add_dependency 'actionview_precompiler'
    s.add_dependency 'random_token'
    s.add_dependency 'sensu-plugins-systemd'
    s.add_dependency 'pry-state'
    s.add_dependency 'rutie'
    s.add_dependency 'zpng'
#    s.add_dependency 'knife-vsphere'
    s.add_dependency 'minitest-sprint'
    s.add_dependency 'protor'
    s.add_dependency 'govuk_admin_template'
    s.add_dependency 'two_captcha'
    s.add_dependency 'scaleapi-ruby'
    s.add_dependency 'symbiont-ruby'
    s.add_dependency 'google_hash'
    s.add_dependency 'marathon-api'
#    s.add_dependency 'gemsmith'
    s.add_dependency 'gratan'
    s.add_dependency 'Saikuro'
    s.add_dependency 'dango'
    s.add_dependency 'extended_email_reply_parser'
    s.add_dependency 'rack-offline'
    s.add_dependency 'clever-ruby'
    s.add_dependency 'wxruby'
    s.add_dependency 'fluent-plugin-azure-loganalytics'
    s.add_dependency 'bootstrap-popover-rails'
    s.add_dependency 'aws-xray'
    s.add_dependency 'globalphone'
    s.add_dependency 'jquery_menu_aim-rails'
    s.add_dependency 'mailcatcher-api'
    s.add_dependency 'monadic'
    s.add_dependency 'chutney'
    s.add_dependency 'fluent-plugin-copy_ex'
    s.add_dependency 'eventq_rabbitmq'
}
