
  require 'rubygems'

Gem::Specification.new {|s|
    s.name          = 'pkg26'
    s.version       = '0.0.1'
    s.author        = 'naresh'
    s.email         = 'nareshdevasani@gmail.com'
    s.homepage      = 'http://github.com/nareshdevasani'
    s.platform      = Gem::Platform::RUBY
    s.summary       = 'An empty gem that depends on every gem available'
    s.description   = s.summary

    s.add_dependency 'mauth-client'
    s.add_dependency '2gis'
    s.add_dependency 'yabeda-sidekiq'
    s.add_dependency 'state_machines-mongoid'
    s.add_dependency 'amq-client'
    s.add_dependency 'Zzzzz'
    s.add_dependency 'data-confirm-modal'
    s.add_dependency 'google-dfp-api'
    s.add_dependency 'ember-cli-rails'
    s.add_dependency 'eslint-rails'
    s.add_dependency 'waypoints_rails'
    s.add_dependency 'nokogiri-diff'
    s.add_dependency 'semver2'
    s.add_dependency 'paper_trail-globalid'
    s.add_dependency 'hirb-unicode-steakknife'
#    s.add_dependency 'pulp_rpm_client'
    s.add_dependency 'php-serialize'
    s.add_dependency 'fluent-plugin-elasticsearch-timestamp-check'
    s.add_dependency 'testrail-ruby'
    s.add_dependency 'capistrano-file-permissions'
    s.add_dependency 'cairo-gobject'
    s.add_dependency 'vagrant-libvirt'
    s.add_dependency 'gem_config'
    s.add_dependency 'clockwork-test'
    s.add_dependency 'citeproc'
    s.add_dependency 'rack-tracer'
    s.add_dependency 'ohm-contrib'
    s.add_dependency 'parsley-rails'
    s.add_dependency 'pdf-writer'
    s.add_dependency 'git-pr-release'
    s.add_dependency 'jsduck'
    s.add_dependency 'corefoundation'
    s.add_dependency 'stronger_parameters'
    s.add_dependency 'agent_client'
    s.add_dependency 'peach'
    s.add_dependency 'gdk_pixbuf2'
    s.add_dependency 'tabs_on_rails'
    s.add_dependency 'fastlane-plugin-get_version_code'
    s.add_dependency 'onceover'
    s.add_dependency 'mobile-fu'
   s.add_dependency 'rforce'
    s.add_dependency 'migrations_watchdog'
    s.add_dependency 'spectrum-rails'
    s.add_dependency 'ember-cli-rails-assets'
    s.add_dependency 'mapbox-sdk'
    s.add_dependency 'sensu-plugins-logs'
    s.add_dependency 'extras'
    s.add_dependency 'n_plus_one_control'
    s.add_dependency 'sqlite_magic'
#    s.add_dependency 'aroi'
    s.add_dependency 'fastlane-plugin-yarn'
    s.add_dependency 'puppet-module-posix-default-r2.4'
    s.add_dependency 'fuelsdk'
    s.add_dependency 'ruby_jard'
    s.add_dependency 'after_transaction_commit'
    s.add_dependency 'peek-pg'
    s.add_dependency 'ruby-ntlm'
    s.add_dependency 'csl-styles'
    s.add_dependency 'resque-dynamic-queues'
    s.add_dependency 'angularjs-rails-resource'
    s.add_dependency 'newrelic-infinite_tracing'
    s.add_dependency 'sim_launcher'
    s.add_dependency 'peek-performance_bar'
#    s.add_dependency 'puppet-module-posix-dev-r2.4'
    s.add_dependency 'mongoid-active_merchant'
    s.add_dependency 'bumbler'
    s.add_dependency 'cheffish'
    s.add_dependency 'cfoundry'
    s.add_dependency 'baby_squeel'
    s.add_dependency 'linguistics'
    s.add_dependency 'store_base_sti_class'
    s.add_dependency 'slowpoke'
    s.add_dependency 'pycall'
    s.add_dependency 'vuejs-rails'
    s.add_dependency 'cli-ui'
#    s.add_dependency 'taps'
    s.add_dependency 'subcontractor'
    s.add_dependency 'redis-scripting'
    s.add_dependency 'autoproj'
    s.add_dependency 'rpm_contrib'
    s.add_dependency 'logger-colors'
    s.add_dependency 'rails-sass-images'
    s.add_dependency 'html_truncator'
    s.add_dependency 'tunemygc'
    s.add_dependency 'fluent-plugin-flowcounter'
    s.add_dependency 'google-cloud-profiler-v2'
    s.add_dependency 'paperclip-meta'
    s.add_dependency 'shopify-money'
    s.add_dependency 'semi_semantic'
    s.add_dependency 'vagrant-hostmanager'
    s.add_dependency 'anemone'
    s.add_dependency 'rom-sql'
    s.add_dependency 'gem-licenses'
    s.add_dependency 'hominid'
    s.add_dependency 'activerecord-postgres-hstore'
    s.add_dependency 'rails-footnotes'
    s.add_dependency 'resque-lock'
    s.add_dependency 'strftime-rails'
    s.add_dependency 'win32-security'
    s.add_dependency 'google-qr'
    s.add_dependency 'stal'
    s.add_dependency 'sinatra-reloader'
    s.add_dependency 'bzip2-ffi'
    s.add_dependency 'ostruct'
    s.add_dependency 'kindlerb'
    s.add_dependency 'inst-jobs'
    s.add_dependency 'font_awesome5_rails'
    s.add_dependency 'dynarex'
    s.add_dependency 'exponential-backoff'
    s.add_dependency 'sensu-plugins-redis'
    s.add_dependency 'uk_postcode'
    s.add_dependency 'simpleconfig'
    s.add_dependency 'puppet-module-posix-default-r2.5'
    s.add_dependency 'rubinius-core-api'
    s.add_dependency 'bogo-cli'
    s.add_dependency 'prawn-qrcode'
    s.add_dependency 'webcomponentsjs-rails'
    s.add_dependency 'prawn-format'
    s.add_dependency 'fog-azure-rm'
    s.add_dependency 'lazyload-rails'
    s.add_dependency 'ar_lazy_preload'
    s.add_dependency 'prawn-labels'
    s.add_dependency 'sorbet-struct-comparable'
    s.add_dependency 'rubinius-actor'
    s.add_dependency 'activerecord4-redshift-adapter'
    s.add_dependency 'hstore_accessor'
    s.add_dependency 'ffi-rzmq-core'
    s.add_dependency 'rom-repository'
    s.add_dependency 'puppet-lint-strict_indent-check'
    s.add_dependency 'i18n_generators'
    s.add_dependency 'elftools'
    s.add_dependency 'google-cloud'
    s.add_dependency 'ruby-mcrypt'
    s.add_dependency 'jquery-livetype-rails'
    s.add_dependency 'language_filter'
    s.add_dependency 'google-cloud-kms'
#    s.add_dependency 'puppet-module-posix-dev-r2.5'
    s.add_dependency 'mutant-rspec'
    s.add_dependency 'iron_core'
    s.add_dependency 'robotex'
    s.add_dependency 'windows-api'
    s.add_dependency 'will_paginate-bootstrap4'
    s.add_dependency 'chart-horizontalbar-rails'
#    s.add_dependency 'flights_gui_tests'
    s.add_dependency 'bootswatch-rails'
    s.add_dependency 'perf_check'
#    s.add_dependency 'faraday-mashify'
    s.add_dependency 'resque-scheduler-web'
    s.add_dependency 'inline_forms'
#    s.add_dependency 'pulp_certguard_client'
    s.add_dependency 'cloudflare'
    s.add_dependency 'flagship'
#    s.add_dependency 'prawnto_2'
#    s.add_dependency 'activeadmin-searchable_select'
#    s.add_dependency 'rails_real_favicon'
    s.add_dependency 'classy_enum'
    s.add_dependency 'iostreams'
#    s.add_dependency 'konduto-ruby'
#    s.add_dependency 'gruf-rspec'
#    s.add_dependency 'pulp_2to3_migration_client'
    s.add_dependency 'verbal_expressions'
    s.add_dependency 'json-compare'
    s.add_dependency 'kitchen-ansible'
    s.add_dependency 'paypal-express'
    s.add_dependency 'omniauth-microsoft-office365'
    s.add_dependency 'trailblazer-activity-dsl-linear'
    s.add_dependency 'capistrano-slackify'
    s.add_dependency 'angular-ui-bootstrap-rails'
    s.add_dependency 'rspec-prof'
    s.add_dependency 'culerity'
    s.add_dependency 'groupify'
#    s.add_dependency 'sensu-plugins-elasticsearch'
    s.add_dependency 'rcsv'
#    s.add_dependency 'backbone-on-rails'
    s.add_dependency 'mobileesp_converted'
    s.add_dependency 'identikal'
    s.add_dependency 'plivo'
    s.add_dependency 'material_icons'
    s.add_dependency 'i18n_yaml_sorter'
    s.add_dependency 'redis-elasticache'
    s.add_dependency 'mongo_session_store'
    s.add_dependency 'once-ler'
#    s.add_dependency 'MailchimpMarketing'
    s.add_dependency 'spreadsheet_architect'
    s.add_dependency 'brotli'
#    s.add_dependency 'kms_encrypted'
#    s.add_dependency 'xero-ruby'
    s.add_dependency 'danger-auto_label'
    s.add_dependency 'rserve-client'
    s.add_dependency 'kaminari-grape'
    s.add_dependency 'autobuild'
    s.add_dependency 'file-utils'
    s.add_dependency 'fluent-plugin-nginx-error-multiline'
    s.add_dependency 'ruby-hl7'
    s.add_dependency 'msfrpc-client'
    s.add_dependency 'filepicker-rails'
    s.add_dependency 'kmts'
    s.add_dependency 'ultrahook'
    s.add_dependency 'gherkin3'
    s.add_dependency 'flipper-api'
#    s.add_dependency 'pem'
    s.add_dependency 'qbo_api'
    s.add_dependency 'sass-embedded'
    s.add_dependency 'bounded_context'
    s.add_dependency 'htmltoword'
    s.add_dependency 'fresh_connection'
    s.add_dependency 'active_frontend'
    s.add_dependency 'omniauth-okta'
    s.add_dependency 'hiera-puppet'
    s.add_dependency 'capybara-mechanize'
    s.add_dependency 'ruby-debug-base19'
    s.add_dependency 'rails-dev-tweaks'
    s.add_dependency 'activerecord-pg_enum'
#    s.add_dependency 'caracal'
    s.add_dependency 'sprockets-commoner'
    s.add_dependency 'generate_method'
#    s.add_dependency 'spinjs-rails'
#    s.add_dependency 'bosh-stemcell'
    s.add_dependency 'schema_plus'
    s.add_dependency 'saml2'
#    s.add_dependency 'bosh-registry'
    s.add_dependency 'delocalize'
    s.add_dependency 'veracode'
    s.add_dependency 'collapsium'
    s.add_dependency 'google-authenticator-rails'
    s.add_dependency 'picasawebalbums'
#    s.add_dependency 'resque-rollbar'
#    s.add_dependency 'spree_gateway'
    s.add_dependency 'rubocop-sequel'
    s.add_dependency 'sidekiq-worker-killer'
    s.add_dependency 'activerecord-refresh_connection'
    s.add_dependency 'jekyll-archives'
    s.add_dependency 'cranky'
#    s.add_dependency 'phcmemberspro'
    s.add_dependency 'gitlab-peek'
#    s.add_dependency 'backbone-rails'
    s.add_dependency 'auto_html'
    s.add_dependency 'leaflet-rails'
    s.add_dependency 'aws-healthcheck'
    s.add_dependency 'gem_update_checker'
    s.add_dependency 'pipetree'
    s.add_dependency 'tddium_client'
    s.add_dependency 'yelp'
    s.add_dependency 'insensitive_hash'
    s.add_dependency 'ruby-handlebars'
    s.add_dependency 'extpp'
#    s.add_dependency 'open_api_parser'
#    s.add_dependency 'solidus_gateway'
#    s.add_dependency 'cable_ready'
#    s.add_dependency 'cert'
}
