
  require 'rubygems'

Gem::Specification.new {|s|
    s.name          = 'pkg39'
    s.version       = '0.0.1'
    s.author        = 'naresh'
    s.email         = 'nareshdevasani@gmail.com'
    s.homepage      = 'http://github.com/nareshdevasani'
    s.platform      = Gem::Platform::RUBY
    s.summary       = 'An empty gem that depends on every gem available'
    s.description   = s.summary

    s.add_dependency 'json-schema_builder'
    s.add_dependency 'recipiez'
    s.add_dependency 'aws-flow-core'
    s.add_dependency 'activerecord-hierarchical_query'
    s.add_dependency 'runit-man'
    s.add_dependency 'responds_to_parent'
    s.add_dependency 'apcera-stager-api'
    s.add_dependency 'balanced'
#    s.add_dependency 'k8s-client'
    s.add_dependency 'jettywrapper'
    s.add_dependency 'katello'
    s.add_dependency 'cistern'
    s.add_dependency 'PriorityQueue'
    s.add_dependency 'gnista'
    s.add_dependency 'jekyll-admin'
    s.add_dependency 'netzke-core'
    s.add_dependency 'bxslider-rails'
    s.add_dependency 'annex_29'
    s.add_dependency 'octopress-hooks'
    s.add_dependency 'flights_gui_henry_tests'
    s.add_dependency 'clam_scan'
    s.add_dependency 'scrivito_content_browser'
    s.add_dependency 'remove_bg'
    s.add_dependency 'has_permalink'
    s.add_dependency 'newrelic_api'
#    s.add_dependency 'manageiq-smartstate'
    s.add_dependency 'git-up'
    s.add_dependency 'docker-fluent-logger'
    s.add_dependency 'crowdin-cli'
    s.add_dependency 'rconf'
    s.add_dependency 'jquery_pwstrength_bootstrap_4'
    s.add_dependency 'swagger_yard'
    s.add_dependency 'timerange'
    s.add_dependency 'danger-regexp'
    s.add_dependency 'e20_ops_middleware'
    s.add_dependency 'mjml-ruby'
    s.add_dependency 'user_mgmt'
    s.add_dependency 'markaby'
    s.add_dependency 'docx_replace'
    s.add_dependency 'fastest-csv'
    s.add_dependency 'ffi-hunspell'
    s.add_dependency 'text_helpers'
    s.add_dependency 'jekyll-menus'
    s.add_dependency 'watobo'
    s.add_dependency 'packagecloud-ruby'
    s.add_dependency 'ec2-metadata'
    s.add_dependency 'google-cloud-bigtable-admin-v2'
    s.add_dependency 'rspec-dns'
    s.add_dependency 'cal-heatmap-rails'
    s.add_dependency 'puppetdb-ruby'
    s.add_dependency 'sunspot-rails-tester'
    s.add_dependency 'hydra-editor'
    s.add_dependency 'percy-cli'
    s.add_dependency 'simple_worker'
    s.add_dependency 'engine_cart'
    s.add_dependency 'fusion_tables'
    s.add_dependency 'noodall-ui'
    s.add_dependency 'smt_rails'
    s.add_dependency 'scim-query-filter-parser'
#    s.add_dependency 'html5shiv-rails'
    s.add_dependency 'ruby-imagespec'
    s.add_dependency 'dpl-cloud_foundry'
    s.add_dependency 'scrivito'
    s.add_dependency 'fastlane-plugin-property_file_read'
    s.add_dependency 'compass-validator'
    s.add_dependency 'le1t0-deprec'
    s.add_dependency 'rspec-steps'
    s.add_dependency 'support'
    s.add_dependency 'cppjieba_rb'
    s.add_dependency 'msgr'
    s.add_dependency 'vagrant-scp'
    s.add_dependency 'diskcached'
    s.add_dependency 'vx-builder'
    s.add_dependency 'theme-juice'
    s.add_dependency 'ean'
    s.add_dependency 'sessionm-cassandra_object'
    s.add_dependency 'jira4r'
    s.add_dependency 'debugger-xml'
    s.add_dependency 'days360'
    s.add_dependency 'normailize'
    s.add_dependency 'jit_preloader'
    s.add_dependency 'smbhash'
    s.add_dependency 'ruby-recaptcha'
    s.add_dependency 'icu_tournament'
    s.add_dependency 'notes'
    s.add_dependency 'gtksourceview2'
    s.add_dependency 'firebase_id_token'
#    s.add_dependency 'fullstack-cms'
    s.add_dependency 'boson'
    s.add_dependency 'fastlane-plugin-synx'
    s.add_dependency 'hipchat-api'
    s.add_dependency 'praxis-blueprints'
#    s.add_dependency 'test-unit-minitest'
    s.add_dependency 'permalink_fu'
    s.add_dependency 'e164'
    s.add_dependency 'github-authentication'
    s.add_dependency 'xero_gateway'
    s.add_dependency 'lightbox2-rails'
    s.add_dependency 'console_table'
    s.add_dependency 'wavefront-client'
    s.add_dependency 'active_remote'
    s.add_dependency 'rubocop-packs'
    s.add_dependency 'sorbet-progress'
#    s.add_dependency 'ironfan'
    s.add_dependency 'ymdp'
    s.add_dependency 'random_bell'
    s.add_dependency 'jquery-hotkeys-rails'
    s.add_dependency 'cucumber-api-steps'
    s.add_dependency 'google-cloud-bigtable-v2'
    s.add_dependency 'sensu-plugins-uchiwa'
    s.add_dependency 'watir-classic'
    s.add_dependency 'pingpp'
    s.add_dependency 'bigquery'
    s.add_dependency 'sorted'
    s.add_dependency 'curl'
    s.add_dependency 'knife-reporting'
    s.add_dependency 'scrivener'
    s.add_dependency 'rsence-pre'
    s.add_dependency 'eycap'
#    s.add_dependency 'ezcater_matchers'
    s.add_dependency 'procore'
    s.add_dependency 'puppet-lint-template_file_extension-check'
#    s.add_dependency 'danger-ios_logs'
#    s.add_dependency 'bioroebe'
    s.add_dependency 'relaton-nist'
    s.add_dependency 'net-hippie'
    s.add_dependency 'gemdiff'
    s.add_dependency 'furi'
    s.add_dependency 'google-cloud-scheduler'
    s.add_dependency 'lamian'
    s.add_dependency 'stylus-source'
    s.add_dependency 'monkey-patch'
    s.add_dependency 'zxcvbn'
    s.add_dependency 'dynect_rest'
    s.add_dependency 'rspec-deep-ignore-order-matcher'
    s.add_dependency 'ruby2js'
    s.add_dependency 'spyke'
    s.add_dependency 'tanker-core'
    s.add_dependency 'weekdays'
#    s.add_dependency 'pliny'
#    s.add_dependency 'puppet-module-posix-dev-r2.1'
    s.add_dependency 'capistrano-scm-copy'
    s.add_dependency 'turbulence'
#    s.add_dependency 'fastlane-plugin-diawi'
    s.add_dependency 'openseadragon'
#    s.add_dependency 'middleman-pagination'
    s.add_dependency 'letter_avatar'
    s.add_dependency 'civo'
    s.add_dependency 'capistrano-measure'
    s.add_dependency 'guard-unicorn'
#    s.add_dependency 'torquebox-naming'
    s.add_dependency 'minitest-power_assert'
    s.add_dependency 'dpl-packagecloud'
    s.add_dependency 'jist'
#    s.add_dependency 'canzea'
    s.add_dependency 'rets'
    s.add_dependency 'ruby-jss'
    s.add_dependency 'centrifuge'
    s.add_dependency 'tramway-core'
    s.add_dependency 'maskedinput-rails'
    s.add_dependency 'bonethug'
    s.add_dependency 'schema_validations'
    s.add_dependency 'breadcrumbs'
    s.add_dependency 'hammerspace'
    s.add_dependency 'attached'
    s.add_dependency 'dsl_evaluator'
    s.add_dependency 'to_xls-rails'
    s.add_dependency 'mortar'
#    s.add_dependency 'metanorma-iso'
    s.add_dependency 'fudge'
    s.add_dependency 'bastion'
    s.add_dependency 'bootstrap_tokenfield_rails'
#    s.add_dependency 'cloudstack-cli'
    s.add_dependency 'bddfire'
    s.add_dependency 'sqsrun'
    s.add_dependency 'requestanimationframe_polyfill-rails'
    s.add_dependency 'mumboe-soap4r'
    s.add_dependency 'aptible-billing'
    s.add_dependency 'zbar'
    s.add_dependency 'anchored'
    s.add_dependency 'foundation-datepicker-rails'
    s.add_dependency 'postgresql'
    s.add_dependency 'curb-fu'
    s.add_dependency 'gem-open'
#    s.add_dependency 'active_support'
    s.add_dependency 'csv-importer'
    s.add_dependency 'lono'
    s.add_dependency 'words_counted'
    s.add_dependency 'macros4cuke'
#    s.add_dependency 'rocketjob'
#    s.add_dependency 'beautiful_url'
    s.add_dependency 'azure_key_vault'
    s.add_dependency 'self_data'
    s.add_dependency 'lorem_ipsum_amet'
    s.add_dependency 'fluent-plugin-numeric-monitor'
    s.add_dependency 'state_machine-audit_trail'
    s.add_dependency 'rucaptcha'
    s.add_dependency 'ts-delayed-delta'
    s.add_dependency 'statesman-events'
    s.add_dependency 'jekyll-compose'
    s.add_dependency 'mushin'
    s.add_dependency 'thread-parent'
    s.add_dependency 'atlas_assets'
    s.add_dependency 'hydra-file_characterization'
    s.add_dependency 'grizzly_ber'
    s.add_dependency 'PlayRockPaperScissorsGame'
    s.add_dependency 'token_phrase'
    s.add_dependency 'mm_eager_includer'
    s.add_dependency 'active_mocker'
    s.add_dependency 'dpl-gae'
    s.add_dependency 'uk_account_validator'
    s.add_dependency 'simple-spreadsheet'
    s.add_dependency 'pathname'
    s.add_dependency 'awesome_rails_console'
    s.add_dependency 'marked-rails'
    s.add_dependency 'rspec-rails-mocha'
    s.add_dependency 'kensa'
#    s.add_dependency 'riana'
    s.add_dependency 'mail-notify'
    s.add_dependency 'cloudconvert-ruby'
    s.add_dependency 'chai-jquery-rails'
    s.add_dependency 'nom-xml'
    s.add_dependency 'braintreehttp'
    s.add_dependency 'relaton-iso'
    s.add_dependency 'middleman-more'
    s.add_dependency 'dust-deploy'
#    s.add_dependency 'vmware_web_service'
    s.add_dependency 'minfraud'
    s.add_dependency 'html2doc'
    s.add_dependency 'ovirt_metrics'
    s.add_dependency 'qa'
    s.add_dependency 'puppet-parse'
    s.add_dependency 'dtk_crd_parser'
    s.add_dependency 'relaton-itu'
    s.add_dependency 'capybara-webmock'
    s.add_dependency 'talkable'
    s.add_dependency 'i18n-inflector'
    s.add_dependency 'pikaday-gem'
    s.add_dependency 'outrigger'
    s.add_dependency 'str_enum'
#    s.add_dependency 'logstash-codec-cloudtrail'
    s.add_dependency 'splunk-client'
    s.add_dependency 'status-page'
    s.add_dependency 'danger-slack'
    s.add_dependency 'osm'
    s.add_dependency 'log_buddy'
    s.add_dependency 'validation_reflection'
    s.add_dependency 'varint'
    s.add_dependency 'capistrano-safe-deploy-to'
#    s.add_dependency 'phcmembers'

}
