
  require 'rubygems'

Gem::Specification.new {|s|
    s.name          = 'top-1600-to-1700-gems'
    s.version       = '0.0.1'
    s.author        = 'naresh'
    s.email         = 'nareshdevasani@gmail.com'
    s.homepage      = 'http://github.com/nareshdevasani'
    s.platform      = Gem::Platform::RUBY
    s.summary       = 'An empty gem that depends on every gem available'
    s.description   = s.summary

    s.add_dependency 'fast_jsonapi'
    s.add_dependency 'gelf'
    s.add_dependency 'aws-sdk-panorama'
    s.add_dependency 'platform-api'
    s.add_dependency 'swagger-blocks'
    s.add_dependency 'activerecord-postgis-adapter'
    s.add_dependency 'aws-sdk-cloudcontrolapi'
    s.add_dependency 'rack-utf8_sanitizer'
    s.add_dependency 'resque-retry'
    s.add_dependency 'non-stupid-digest-assets'
    s.add_dependency 'whois'
    s.add_dependency 'pry-shell'
    s.add_dependency 'aws-sdk-kafkaconnect'
    s.add_dependency 'csv'
    s.add_dependency 'aws-sdk-managedgrafana'
    s.add_dependency 'gitlab-license_finder'
    s.add_dependency 'mysql'
    s.add_dependency 'dead_end'
    s.add_dependency 'creek'
    s.add_dependency 'standard'
    s.add_dependency 'azure-core'
    s.add_dependency 'cassandra-driver'
    s.add_dependency 'handlebars_assets'
    s.add_dependency 'snappy'
    s.add_dependency 'descriptive_statistics'
    s.add_dependency 'devise-i18n'
    s.add_dependency 'zookeeper'
    s.add_dependency 'sucker_punch'
    s.add_dependency 'site_prism-all_there'
    s.add_dependency 'simplecov-json'
    s.add_dependency 'options'
    s.add_dependency 'pmap'
    s.add_dependency 'tty-markdown'
    s.add_dependency 'ace-rails-ap'
    s.add_dependency 'aws-sdk-resiliencehub'
    s.add_dependency 'google-cloud-logging'
    s.add_dependency 'aws-sdk-drs'
    s.add_dependency 'ssh_data'
    s.add_dependency 'truncate_html'
    s.add_dependency 'fluent-plugin-kinesis'
    s.add_dependency 'kas-grpc'
#    s.add_dependency 'ld-eventsource'
    s.add_dependency 'email_validator'
    s.add_dependency 'google-ads-common'
    s.add_dependency 'bootstrap-datepicker-rails'
    s.add_dependency 'oily_png'
    s.add_dependency 'amazing_print'
    s.add_dependency 'aws-sdk-sso'
    s.add_dependency 'ZenTest'
    s.add_dependency 'axlsx_rails'
    s.add_dependency 'racecar'
    s.add_dependency 'active_hash'
    s.add_dependency 'paper_trail-association_tracking'
    s.add_dependency 'appsignal'
    s.add_dependency 'fog-internet-archive'
    s.add_dependency 'redis-objects'
    s.add_dependency 'phony_rails'
    s.add_dependency 'callsite'
    s.add_dependency 'astrolabe'
    s.add_dependency 'gitlab-omniauth-openid-connect'
    s.add_dependency 'em-synchrony'
    s.add_dependency 'rake-compiler'
    s.add_dependency 'image_size'
    s.add_dependency 'iso_country_codes'
    s.add_dependency 'strip_attributes'
    s.add_dependency 'fluent-plugin-forest'
    s.add_dependency 'sprockets-es6'
    s.add_dependency 'globalize'
    s.add_dependency 'prometheus_exporter'
    s.add_dependency 'origin'
    s.add_dependency 'knapsack_pro'
#    s.add_dependency 'blankslate'
#    s.add_dependency 'cap-ec2'
    s.add_dependency 'slather'
    s.add_dependency 'rack_session_access'
    s.add_dependency 'aws-sdk-cloudwatchevidently'
    s.add_dependency 'open_uri_redirections'
#    s.add_dependency 'faraday_middleware-aws-signers-v4'
    s.add_dependency 'grape-swagger-entity'
    s.add_dependency 'ruby-openid'
    s.add_dependency 'google-ads-savon'
    s.add_dependency 'american_date'
    s.add_dependency 'codeclimate-engine-rb'
    s.add_dependency 'rubycritic'
    s.add_dependency 'benchmark'
    s.add_dependency 'sneakers'
    s.add_dependency 'protobuf'
    s.add_dependency 'ejs'
    s.add_dependency 'turbo-rails'
    s.add_dependency 'elasticsearch-extensions'
#    s.add_dependency 'logstash-mixin-aws'
    s.add_dependency 'foreman-upstart-scaling'
#    s.add_dependency 'manticore'
    s.add_dependency 'aws-sdk-migrationhubrefactorspaces'
    s.add_dependency 'devise-encryptable'
    s.add_dependency 'skylight'
}
