
  require 'rubygems'

Gem::Specification.new {|s|
    s.name          = 'pkg33'
    s.version       = '0.0.1'
    s.author        = 'Naresh Devasani'
    s.email         = 'naresh@endor.ai'
    s.homepage      = 'http://github.com/capotej/trollface'
    s.platform      = Gem::Platform::RUBY
    s.summary       = 'An empty gem that depends on every gem available'
    s.description   = s.summary

    s.add_dependency 'request_exception_handler'
    s.add_dependency 'netsoft-danger'
    s.add_dependency 'tty-editor'
    s.add_dependency 'rspec_around_all'
    s.add_dependency 'rusage'
    s.add_dependency 'plek'
    s.add_dependency 'capistrano-rbenv-install'
    s.add_dependency 'guard-reek'
    s.add_dependency 'active_admin_role'
    s.add_dependency 'fluent-plugin-statsd'
    s.add_dependency 'fake_braintree'
    s.add_dependency 'constant_table_saver'
    s.add_dependency 'twine-rails'
    s.add_dependency 'sprockets-export'
    s.add_dependency 'blade-qunit_adapter'
    s.add_dependency 'image_voodoo'
    s.add_dependency 'awesome_nested_fields'
    s.add_dependency 'steak'
    s.add_dependency 'button'
    s.add_dependency 'ripper-tags'
    s.add_dependency 'rectify'
    s.add_dependency 'activerecord-redshift-adapter'
    s.add_dependency 'groonga-command'
    s.add_dependency 'namecase'
    s.add_dependency 'pocketsphinx-ruby'
    s.add_dependency 'rails_pwnerer'
    s.add_dependency 'codeclimate'
    s.add_dependency 'syntax_tree-rbs'
    s.add_dependency 'vagrant-vsphere'
    s.add_dependency 'appbundle-updater'
    s.add_dependency 'static_model'
    s.add_dependency 'ruby-box'
    s.add_dependency 'google-cloud-dialogflow-v2'
    s.add_dependency 'km'
    s.add_dependency 'custom_configuration'
    s.add_dependency 'trinidad_jars'
#    s.add_dependency 'logstash-filter-range'
    s.add_dependency 'sensu-plugins-consul'
    s.add_dependency 'mailosaur'
    s.add_dependency 'fluent-plugin-datacounter'
    s.add_dependency 'kakurenbo-puti'
    s.add_dependency 'yard-sinatra'
    s.add_dependency 'twine'
    s.add_dependency 'fun_sftp'
    s.add_dependency 'nbtfile'
    s.add_dependency 'vonage'
    s.add_dependency 'vertica'
    s.add_dependency 'measured-rails'
    s.add_dependency 'geo_point'
    s.add_dependency 'translate_enum'
    s.add_dependency 'rack-statsd'
    s.add_dependency 'ecdsa'
    s.add_dependency 'c_geohash'
    s.add_dependency 'prawn-grouping'
    s.add_dependency 'abstract_class'
    s.add_dependency 'zoom_rb'
    s.add_dependency 'rspec-http'
    s.add_dependency 'stellar-base'
    s.add_dependency 'aftership'
    s.add_dependency 'candy_check'
    s.add_dependency 'resque-throttler'
    s.add_dependency 'nokogiri-plist'
    s.add_dependency 'sparsify'
    s.add_dependency 'activerecord-cte'
    s.add_dependency 'facebook-messenger'
    s.add_dependency 'heroku_san'
    s.add_dependency 'onering-client'
    s.add_dependency 'cukeforker'
    s.add_dependency 'c21e'
    s.add_dependency 'jsonschema'
    s.add_dependency 'slack-ruby-bot'
    s.add_dependency 'placeholder-gem'
    s.add_dependency 'activerecord-cockroachdb-adapter'
#    s.add_dependency 'logstash-mixin-ca_trusted_fingerprint_support'
    s.add_dependency 'vinbot'
    s.add_dependency 'capybara-lockstep'
    s.add_dependency 'phaxio'
    s.add_dependency 'ooxml_parser'
    s.add_dependency 'templater'
    s.add_dependency 'flores'
    s.add_dependency 'mix_tape'
    s.add_dependency 'horza'
    s.add_dependency 'ruby'
    s.add_dependency 'graphql_schema'
    s.add_dependency 'sensu-plugins-slack'
    s.add_dependency 'test-helpers'
    s.add_dependency 'faye-redis'
    s.add_dependency 'icheck-rails'
    s.add_dependency 'image_info'
    s.add_dependency 'bh'
    s.add_dependency 'tribute'
    s.add_dependency 'prawn_shapes'
    s.add_dependency 'canvas_statsd'
    s.add_dependency 'translit'
    s.add_dependency 'credit_card_sanitizer'
    s.add_dependency 'em-http-server'
    s.add_dependency 'transloadit'
    s.add_dependency 'just-the-docs'
    s.add_dependency 'brnumeros'
#    s.add_dependency 'pact-messages'
    s.add_dependency 'carrierwave-processing'
    s.add_dependency 'brcep'
    s.add_dependency 'mail_interceptor'
    s.add_dependency 'blade-sauce_labs_plugin'
    s.add_dependency 'cacheflow'
    s.add_dependency 'rapporteur'
    s.add_dependency 'resolv-srv'
    s.add_dependency 'ibm_cloud_sdk_core'
    s.add_dependency 'datamapper'
    s.add_dependency 'syntax_tree-haml'
    s.add_dependency 'Text'
    s.add_dependency 'instrumental_agent'
    s.add_dependency 'amountable'
    s.add_dependency 'imperium'
    s.add_dependency 'rinruby'
    s.add_dependency 'dry-initializer-rails'
#    s.add_dependency 'schema_plus_enums'
    s.add_dependency 'dress_code'
    s.add_dependency 'brcpfcnpj'
    s.add_dependency 'travis_dedup'
    s.add_dependency 'unicode_scanner'
    s.add_dependency 'dashing'
    s.add_dependency 'sensu-json'
    s.add_dependency 'webshims-rails'
    s.add_dependency 'azure-armrest'
    s.add_dependency 'deacon'
#    s.add_dependency 'logstash-output-datadog'
    s.add_dependency 'vagrant-omnibus'
    s.add_dependency 'runeblog'
    s.add_dependency 'sensu-plugins-pagerduty'
#    s.add_dependency 'librarian-chef'
    s.add_dependency 'sensu-cli'
    s.add_dependency 'knife-lastrun'
    s.add_dependency 'espeak-ruby'
    s.add_dependency 'vin_bank'
    s.add_dependency 'sidekiq-client-cli'
    s.add_dependency 'fluent-plugin-mutate_filter'
#    s.add_dependency 'linaro-jekyll-theme'
    s.add_dependency 'nido'
    s.add_dependency 'pdk'
#    s.add_dependency 'sensu-plugins-mailer'
    s.add_dependency 'home_run'
    s.add_dependency 'get'
    s.add_dependency 'sshkit-sudo'
    s.add_dependency 'prawn-markup'
    s.add_dependency 'custom_error_message'
#    s.add_dependency 'activerecord-postgres-json'
    s.add_dependency 'dejunk'
    s.add_dependency 'data_miner'
    s.add_dependency 'whiny_validation'
    s.add_dependency 'query_diet'
    s.add_dependency 'youtube_it'
    s.add_dependency 'prop'
    s.add_dependency 'thinreports-rails'
    s.add_dependency 'minitest-bang'
    s.add_dependency 'safer_rails_console'
    s.add_dependency 'linux_admin'
    s.add_dependency 'naether'
    s.add_dependency 'capistrano-multiconfig'
    s.add_dependency 'storable'
    s.add_dependency 'cucumber_characteristics'
    s.add_dependency 'pg_ltree'
#    s.add_dependency 'logstash-output-influxdb'
    s.add_dependency 'rails_weak_etags'
    s.add_dependency 'ParseTree'
    s.add_dependency 'capitalize-names'
    s.add_dependency 'r2'
    s.add_dependency 'resque-delayed'
    s.add_dependency 'json-schema-rspec'
    s.add_dependency 'solrizer'
    s.add_dependency 'evalhook'
#    s.add_dependency 'logstash-input-s3-sns-sqs'
    s.add_dependency 'open_gem'
    s.add_dependency 'random_data'
    s.add_dependency 'rails_db'
    s.add_dependency 'owlcarousel-rails'
    s.add_dependency 'gdata_19'
    s.add_dependency 'pgslice'
    s.add_dependency 'prawn-fast-png'
    s.add_dependency 'chef-helpers'
    s.add_dependency 'js_assets'
    s.add_dependency 'hypershield'
    s.add_dependency 'jasminerice'
    s.add_dependency 'wistia-api'
    s.add_dependency 'requests'
    s.add_dependency 'redactor-rails'
    s.add_dependency 'lhs'
    s.add_dependency 'simplycop'
    s.add_dependency 'fastlane-plugin-upload_symbols_to_new_relic'
    s.add_dependency 'time_zone_ext'
    s.add_dependency 'govuk_design_system_formbuilder'
    s.add_dependency 'wtf_lang'
    s.add_dependency 'effective_resources'
    s.add_dependency 'pay'
    s.add_dependency 'surus'
    s.add_dependency 'lita-karma'
    s.add_dependency 'consistency_fail'
    s.add_dependency 'us_bank_holidays'
    s.add_dependency 'gc_ruboconfig'
    s.add_dependency 'cowsay'
    s.add_dependency 'action_mailer_cache_delivery'
    s.add_dependency 'mothership'
    s.add_dependency 'quilt_rails'
    s.add_dependency 'textutils'
    s.add_dependency 'accountingjs-rails'
    s.add_dependency 'email_data'
    s.add_dependency 'hanami-helpers'
    s.add_dependency 'localized_country_select'
    s.add_dependency 'gitlab_meta'
    s.add_dependency 'gotime-cassandra_object'
    s.add_dependency 'luhnacy'
    s.add_dependency 'hooker'
    s.add_dependency 'fhir_dstu2_models'
    s.add_dependency 'hanami-assets'
    s.add_dependency 'auto-session-timeout'
    s.add_dependency 'groonga-client'
    s.add_dependency 'geordi'
    s.add_dependency 'cloudsponge'
    s.add_dependency 'tradesman'
    s.add_dependency 'rdf-reasoner'
    s.add_dependency 'packnga'
    s.add_dependency 'inst-jobs-autoscaling'
    s.add_dependency 'ffi-aspell'
    s.add_dependency 'square_connect'
    s.add_dependency 'gritter'
    s.add_dependency 'remote_lock'
#    s.add_dependency 'rspec-default_http_header'
    s.add_dependency 'aweber'
    s.add_dependency 'websocket-native'
    s.add_dependency 'schema_plus_default_expr'
    s.add_dependency 'knockoutjs-rails'
    s.add_dependency 'friendly_id-globalize'
#    s.add_dependency 'rspec-json_matchers'
    s.add_dependency 'omniauth-keycloak'
    s.add_dependency 'embulk-output-s3'
    s.add_dependency 'code-formatter'
    s.add_dependency 'puppet-lint-alias-check'
#    s.add_dependency 'jenkins2'
    s.add_dependency 'smart_todo'
    s.add_dependency 'uservoice-ruby'
    s.add_dependency 'mysql_import'
    s.add_dependency 'payment_icons'
    s.add_dependency 'circuit_breaker'
    s.add_dependency 'graphite-api'
    s.add_dependency 'clowne'
    s.add_dependency 'rltk'
    s.add_dependency 'sup'
    s.add_dependency 'totp'
    s.add_dependency 'sentry-resque'
    s.add_dependency 'carrierwave-video-thumbnailer'

}
