
  require 'rubygems'

Gem::Specification.new {|s|
    s.name          = 'pkg27'
    s.version       = '0.0.1'
    s.author        = 'naresh'
    s.email         = 'nareshdevasani@gmail.com'
    s.homepage      = 'http://github.com/nareshdevasani'
    s.platform      = Gem::Platform::RUBY
    s.summary       = 'An empty gem that depends on every gem available'
    s.description   = s.summary

    s.add_dependency 'plupload-rails'
    s.add_dependency 'engineyard-serverside-adapter'
    s.add_dependency 'ladle'
    s.add_dependency 'ffprober'
    s.add_dependency 'mrkt'
    s.add_dependency 'handlebars'
    s.add_dependency 'memery'
    s.add_dependency 'zuora_connect'
    s.add_dependency 'nfe-paulistana'
    s.add_dependency 'braid'
    s.add_dependency 'i18n-debug'
    s.add_dependency 'produce'
    s.add_dependency 'jruby-pageant'
    s.add_dependency 'service'
    s.add_dependency 'permessage_deflate'
    s.add_dependency 'statemachine'
    s.add_dependency 'semver'
    s.add_dependency 'bogo-ui'
    s.add_dependency 'resque-multi-job-forks'
    s.add_dependency 'text-hyphen'
    s.add_dependency 'guard-zeus'
#    s.add_dependency 'hiptest-publisher'
#    s.add_dependency 'bosh_cli_plugin_micro'
    s.add_dependency 'sensu-plugins-rabbitmq'
    s.add_dependency 'rails-ujs'
    s.add_dependency 'gc_tracer'
    s.add_dependency 'bounce_email'
    s.add_dependency 'fluent-plugin-beats'
    s.add_dependency 'logify'
#    s.add_dependency 'senti'
    s.add_dependency 'field_test'
    s.add_dependency 'natto'
    s.add_dependency 'fullcontact'
    s.add_dependency 'sidekiq-prometheus-exporter'
    s.add_dependency 'celerity'
    s.add_dependency 'ceedling'
    s.add_dependency 'devise_zxcvbn'
    s.add_dependency 'capybara-chromedriver-logger'
#    s.add_dependency 'maintenance_tasks'
    s.add_dependency 'log_formatter'
    s.add_dependency 'telegram-bot-ruby'
#    s.add_dependency 'activerecord-opentracing'
    s.add_dependency 'rack-tracker'
    s.add_dependency 'spawnling'
    s.add_dependency 'workflow-activerecord'
    s.add_dependency 'trailblazer-developer'
    s.add_dependency 'cequel'
    s.add_dependency 'crummy'
    s.add_dependency 'kiba'
    s.add_dependency 'graphql_playground-rails'
    s.add_dependency 'unitwise'
#    s.add_dependency 'base2_cms'
    s.add_dependency 'nanoc'
    s.add_dependency 'rake-progressbar'
    s.add_dependency 'jquery_mobile_rails'
    s.add_dependency 'middleman-blog'
    s.add_dependency 'bosh-core'
    s.add_dependency 'google-cloud-container'
    s.add_dependency 'bootstrap4-kaminari-views'
    s.add_dependency 'yard-activerecord'
    s.add_dependency 'strongdm'
    s.add_dependency 'devise-pwned_password'
    s.add_dependency 'puppet-lint-spaceship_operator_without_tag-check'
#    s.add_dependency 'logstash-integration-rabbitmq'
    s.add_dependency 'appoptics_apm'
    s.add_dependency 'autotest-rails'
    s.add_dependency 'ruby-terraform'
    s.add_dependency 'travis-artifacts'
    s.add_dependency 'intl-tel-input-rails'
#    s.add_dependency 'attributes_sanitizer'
    s.add_dependency 'pivotal_git_scripts'
    s.add_dependency 'sweet_notifications'
    s.add_dependency 'columns_on_demand'
    s.add_dependency 'yomu'
    s.add_dependency 'acts_as_api'
    s.add_dependency 'artii'
    s.add_dependency 'trailblazer-cells'
    s.add_dependency 'stub_env'
    s.add_dependency 'danger-kotlin_detekt'
    s.add_dependency 'moodle2cc'
    s.add_dependency 'gender_detector'
    s.add_dependency 'ckeditor_rails'
    s.add_dependency 'socket.io-emitter'
    s.add_dependency 'cells-haml'
    s.add_dependency 'yamllint'
    s.add_dependency 'remove_emoji'
    s.add_dependency 'milia'
    s.add_dependency 'restore_bundled_with'
    s.add_dependency 'viewpoint'
    s.add_dependency 'krane'
    s.add_dependency 'scruffy'
    s.add_dependency 'async-rest'
    s.add_dependency 'fluent-plugin-serialize-nested-json'
    s.add_dependency 'string_undump'
    s.add_dependency 'ruby-lokalise-api'
    s.add_dependency 'ffi-icu'
#    s.add_dependency 'logstash-devutils'
    s.add_dependency 'currency'
    s.add_dependency 'pqueue'
    s.add_dependency 'database_consistency'
    s.add_dependency 'rack-jsonp'
    s.add_dependency 'rantly'
    s.add_dependency 'elastic-app-search'
#    s.add_dependency 'frameit'
    s.add_dependency 'autonumeric-rails'
    s.add_dependency 'rspec-graphql_matchers'
    s.add_dependency 'capybara-slow_finder_errors'
#    s.add_dependency 'supply'
    s.add_dependency 'fluent-plugin-splunkhec'
    s.add_dependency 'sepa_king'
    s.add_dependency 'nested-hstore'
    s.add_dependency 'pulp_npm_client'
    s.add_dependency 'process-group'
    s.add_dependency 'mobvious'
#    s.add_dependency 'wells_fargo_retail'
    s.add_dependency 'exiftool_vendored'
    s.add_dependency 'mustermann-contrib'
    s.add_dependency 'react-source'
    s.add_dependency 'translation'
    s.add_dependency 'powder'
    s.add_dependency 'hotwire-rails'
    s.add_dependency 'erb'
    s.add_dependency 'aerospike'
    s.add_dependency 'net'
    s.add_dependency 'packable'
    s.add_dependency 'alias_scope'
#    s.add_dependency 'logstash-output-syslog'
    s.add_dependency 'trix-rails'
    s.add_dependency 'verbs'
    s.add_dependency 'naughty_or_nice'
    s.add_dependency 'prosopite'
    s.add_dependency 'mongoid-encrypted-fields'
    s.add_dependency 'flipflop'
    s.add_dependency 'rack-timeout-puma'
    s.add_dependency 'swot'
    s.add_dependency 'pokitdok-ruby'
    s.add_dependency 'adyen-ruby-api-library'
#    s.add_dependency 'bosh-director'
    s.add_dependency 'chef-handler-mail'
    s.add_dependency 'google-cloud-tasks'
    s.add_dependency 'subprocess'
    s.add_dependency 'gem_publisher'
    s.add_dependency 'neo4j-core'
    s.add_dependency 'vmail'
    s.add_dependency 'newrelic-grape'
    s.add_dependency 'redis_rate_limiter'
    s.add_dependency 'gepub'
    s.add_dependency 'percy-client'
    s.add_dependency 'flickraw'
    s.add_dependency 'gctime'
    s.add_dependency 'choria-mcorpc-support'
    s.add_dependency 'active_zuora'
    s.add_dependency 'fastlane-plugin-emerge'
    s.add_dependency 'pivotal-tracker'
    s.add_dependency 'castle-rb'
    s.add_dependency 'montrose'
    s.add_dependency 'patchelf'
    s.add_dependency 'mongoid-locker'
    s.add_dependency 'vacuum'
    s.add_dependency 'active_record_migrations'
    s.add_dependency 'classy_hash'
    s.add_dependency 'rspec-instrumentation-matcher'
    s.add_dependency 'capistrano-rake'
    s.add_dependency 'dapp'
    s.add_dependency 'open-uri'
    s.add_dependency 'hansi'
    s.add_dependency 'rash'
    s.add_dependency 'yardstick'
    s.add_dependency 'dwradcliffe_test_gem_push'
    s.add_dependency 'metamagic'
    s.add_dependency 'luhn_checksum'
    s.add_dependency 'goodcheck'
    s.add_dependency 'graphviz'
    s.add_dependency 'rsa-pem-from-mod-exp'
    s.add_dependency 'puppet-lint-legacy_facts-check'
    s.add_dependency 'steep'
    s.add_dependency 'cocoapods-acknowledgements'
    s.add_dependency 'power_enum'
#    s.add_dependency 'bosh-release'
    s.add_dependency 'dkim'
    s.add_dependency 'avalanche-rails'
    s.add_dependency 'globby'
    s.add_dependency 'griddler-mailgun'
    s.add_dependency 'azure-storage-table'
#    s.add_dependency 'rails-decorators'
    s.add_dependency 'peek-host'
    s.add_dependency 'jquery-unique-clone-rails'
    s.add_dependency 'liner'
#    s.add_dependency 'bosh-monitor'
    s.add_dependency 'htransform'
    s.add_dependency 'mailhandler'
    s.add_dependency 'fedex'
    s.add_dependency 'safemode'
    s.add_dependency 'bitters'
#    s.add_dependency 'bosh_cli_plugin_aws'
    s.add_dependency 'faraday-gzip'
    s.add_dependency 'jazz_fingers'
    s.add_dependency 'featurejs_rails'
    s.add_dependency 'mongoid-sample'
    s.add_dependency 'cache_digests'
    s.add_dependency 'mongoid-document_path'
    s.add_dependency 'guess_html_encoding'
    s.add_dependency 'localeapp'
    s.add_dependency 'mprelude'
#    s.add_dependency 'eb_deployer'
    s.add_dependency 'em_aws'
    s.add_dependency 'sprout'
    s.add_dependency 'chartjs-ror'
    s.add_dependency 'fake_ftp'
    s.add_dependency 'active_data'
#    s.add_dependency 'gqli'
    s.add_dependency 'deprecation'
    s.add_dependency 'signed_multiset'
#    s.add_dependency 'logstash-mixin-event_support'
    s.add_dependency 'avatax-ruby'
    s.add_dependency 'rhc'
    s.add_dependency 'xmlcanonicalizer'
    s.add_dependency 'rtesseract'
    s.add_dependency 'chinese_pinyin'
    s.add_dependency 'redshift-client'
    s.add_dependency 'minitest-fail-fast'
    s.add_dependency 'iterable-api-client'
    s.add_dependency 'mixpanel'
    s.add_dependency 'fastlane-plugin-xchtmlreport'
#    s.add_dependency 'dpl-code_deploy'
    s.add_dependency 'firebase_token_generator'
    s.add_dependency 'bogo-config'
    s.add_dependency 'join_dependency'
    s.add_dependency 'retina_tag'
    s.add_dependency 'iso'
    s.add_dependency 'embulk-output-bigquery'
    s.add_dependency 'ruby-pg-extras'
    s.add_dependency 'ruby_version'
    s.add_dependency 'simplecov-csv'
    s.add_dependency 'delayed_job_recurring'
    s.add_dependency 'albacore'
    s.add_dependency 'flot-rails'
    s.add_dependency 'poppler'
    s.add_dependency 'cucumber_factory'
#    s.add_dependency 'unidom-common'
    s.add_dependency 'faraday-conductivity'
    s.add_dependency 'rb_sys'
    s.add_dependency 'dlegr250_material_design'
    s.add_dependency 'message_format'
    s.add_dependency 'stemmer'
    s.add_dependency 'stream-ruby'
    s.add_dependency 'people'
    s.add_dependency 'picky'
    s.add_dependency 'hanami-router'
}
