
  require 'rubygems'

Gem::Specification.new {|s|
    s.name          = 'pkg43'
    s.version       = '0.0.1'
    s.author        = 'Naresh Devasani'
    s.email         = 'naresh@endor.ai'
    s.homepage      = 'http://github.com/capotej/trollface'
    s.platform      = Gem::Platform::RUBY
    s.summary       = 'An empty gem that depends on every gem available'
    s.description   = s.summary

    s.add_dependency 'kitchen-digitalocean'
    s.add_dependency 'sandi_meter'
    s.add_dependency 'atk_toolbox'
    s.add_dependency 'danger-ktlint'
#    s.add_dependency 'encrypted-cookies'
    s.add_dependency 'pebblebed'
    s.add_dependency 'iobuffer'
    s.add_dependency 'ai4r'
    s.add_dependency 'veewee'
    s.add_dependency 'qtip2-jquery-rails'
    s.add_dependency 'rspec_json_schema_matcher'
    s.add_dependency 'knife'
    s.add_dependency 'compath'
    s.add_dependency 'wheels'
    s.add_dependency 'dpl-bluemix_cloud_foundry'
    s.add_dependency 'stream_rails'
#    s.add_dependency 'pg_ha_migrations'
    s.add_dependency 'dot_hash'
    s.add_dependency 'cupertino'
    s.add_dependency 'slack-ruby-block-kit'
    s.add_dependency 'access'
#    s.add_dependency 'conduit-sprint'
    s.add_dependency 'chandler'
    s.add_dependency 'wedge'
    s.add_dependency 'propono'
    s.add_dependency 'email_prefixer'
    s.add_dependency 'speculation'
    s.add_dependency 'chanko'
    s.add_dependency 'bummr'
    s.add_dependency 'dependabot-pub'
    s.add_dependency 'bootstrap-social-rails'
    s.add_dependency 'lita-default-handlers'
    s.add_dependency 'dotgpg'
    s.add_dependency 'challah'
    s.add_dependency 'terraspace_plugin_aws'
    s.add_dependency 'fdoc'
    s.add_dependency 'rgviz-rails'
    s.add_dependency 'factual-api'
    s.add_dependency 'string-cases'
    s.add_dependency 'zebra-zpl'
    s.add_dependency 'colsole'
    s.add_dependency 'activeadmin-mongoid'
    s.add_dependency 'ncursesw'
    s.add_dependency 'admin_data'
#    s.add_dependency 'fluent-plugin-sql'
    s.add_dependency 'email'
#    s.add_dependency 'opener-webservice'
#    s.add_dependency 'dpl-ops_works'
    s.add_dependency 'webvtt-ruby'
    s.add_dependency 'madmimi'
    s.add_dependency 'resque-mock'
    s.add_dependency 'gce-metadata'
    s.add_dependency 'rufus-treechecker'
    s.add_dependency 'sequel_secure_password'
    s.add_dependency 'renum'
    s.add_dependency 'omniauth-fitbit'
    s.add_dependency 'approximately'
    s.add_dependency 'prawn-gmagick'
#    s.add_dependency 'instagram-continued'
    s.add_dependency 'puma-heroku'
    s.add_dependency 'rack-console'
    s.add_dependency 'contacts'
    s.add_dependency 'timecode'
    s.add_dependency 'string-obfuscator'
    s.add_dependency 'rspec-request_snapshot'
#    s.add_dependency 'right_agent'
    s.add_dependency 'facebooker'
    s.add_dependency 'active_cmis'
    s.add_dependency 'cbeta'
    s.add_dependency 'dpl-azure_webapps'
    s.add_dependency 'holder_rails'
    s.add_dependency 'cmess'
    s.add_dependency 'synapse_pay_rest'
    s.add_dependency 'tiny_segmenter'
    s.add_dependency 'threaded_logging'
    s.add_dependency 'reality-core'
    s.add_dependency 'resolv-replace'
    s.add_dependency 'asetus'
    s.add_dependency 'bootswatch_rails'
    s.add_dependency 'jsonapi_spec_helpers'
#    s.add_dependency 'phcaccountspro'
    s.add_dependency 'rollout_ui'
    s.add_dependency 'docman'
#    s.add_dependency 'firebase_cloud_messenger'
    s.add_dependency 'prefixed_ids'
    s.add_dependency 'haml2slim'
    s.add_dependency 'chingu'
    s.add_dependency 'detect_language'
#    s.add_dependency 'locomotive_cms'
    s.add_dependency 'i18n-inflector-rails'
    s.add_dependency 'cnccs'
    s.add_dependency 'fluent-plugin-config-expander'
    s.add_dependency 'hammer_cli_foreman'
    s.add_dependency 'sendgrid4r'
    s.add_dependency 'google-cloud-talent'
    s.add_dependency 'motor-admin'
    s.add_dependency 'page_title_helper'
    s.add_dependency 'xmlhasher'
    s.add_dependency 'slideshow'
    s.add_dependency 'ruby-jing'
    s.add_dependency 'capistrano-rails-tail-log'
    s.add_dependency 'opentelemetry-propagator-b3'
    s.add_dependency 'webmachine'
    s.add_dependency 'devfile'
    s.add_dependency 'jstree-rails-4'
    s.add_dependency 'taskjuggler'
    s.add_dependency 'crimp'
    s.add_dependency 'merb_datamapper'
    s.add_dependency 'steno'
    s.add_dependency 'safe_redirect'
    s.add_dependency 'sandal'
    s.add_dependency 'earthquake'
#    s.add_dependency 'logstash-output-opentsdb'
    s.add_dependency 'render_parent'
    s.add_dependency 'unbutton'
    s.add_dependency 'resque-heroku'
    s.add_dependency 'migration_tools'
    s.add_dependency 'idiom'
    s.add_dependency 'danger-xcodebuild'
    s.add_dependency 'ish_models'
#    s.add_dependency 'acts_as_assets'
    s.add_dependency 'colorbox-rails'
    s.add_dependency 'luban'
    s.add_dependency 'assert'
    s.add_dependency 'deputy'
    s.add_dependency 'fastlane-plugin-gradle_properties'
    s.add_dependency 'code'
    s.add_dependency 'zencoder-fetcher'
    s.add_dependency 'gb-agencies'
    s.add_dependency 'devise_uid'
    s.add_dependency 'goran'
#    s.add_dependency 'modernizr'
    s.add_dependency 'webfontloader'
    s.add_dependency 'rake-remote_task'
    s.add_dependency 'crossroads_capistrano'
    s.add_dependency 'ruby_vcloud_sdk'
    s.add_dependency 'rails_compatibility'
    s.add_dependency 'quokkadb'
    s.add_dependency 'reconnect_ar_rails'
    s.add_dependency 'pexels'
    s.add_dependency 'structure'
    s.add_dependency 'dnsimple-ruby'
    s.add_dependency 'jquery-monthpicker-rails'
    s.add_dependency 'image_science'
    s.add_dependency 'shrine-url'
    s.add_dependency 'towerdata_api'
#    s.add_dependency 'middleman-dato'
    s.add_dependency 'softlayer_api'
    s.add_dependency 'omniauth-orcid'
    s.add_dependency 'cd'
#    s.add_dependency 'bookyt_projects'
    s.add_dependency 'minitest-optional_retry'
    s.add_dependency 'sensu-plugins-supervisor'
    s.add_dependency 'enju_message'
    s.add_dependency 'meterpreter_bins'
    s.add_dependency 'hiredis-client'
    s.add_dependency 'onlyoffice_logger_helper'
    s.add_dependency 'conekta'
    s.add_dependency 'rubocop-require_tools'
    s.add_dependency 'pmd_translate_checkstyle_format'
    s.add_dependency 'zabbix_manager'
    s.add_dependency 'eldritch'
    s.add_dependency 'rdoc-data'
    s.add_dependency 'acts-as-joinable'
    s.add_dependency 'html_press'
#    s.add_dependency 'rjack-jackson'
#    s.add_dependency 'gazer'
    s.add_dependency 'zaif'
    s.add_dependency 'thin-rails'
#    s.add_dependency 'mobilize-ssh'
    s.add_dependency 'alexa'
    s.add_dependency 'rmate'
    s.add_dependency 'enju_ndl'
    s.add_dependency 'jqtools-rails'
    s.add_dependency 'gcal4ruby'
    s.add_dependency 'xsys'
    s.add_dependency 'google-cloud-security_center'
    s.add_dependency 'puppet-lint-no_file_path_attribute-check'
    s.add_dependency 'awssume'
    s.add_dependency 'foreman_remote_execution'
#    s.add_dependency 'jruby-httpclient'
    s.add_dependency 'minisyntax'
    s.add_dependency 'premailer-rails3'
    s.add_dependency 'cadenza'
    s.add_dependency 'vsphere-automation-cis'
    s.add_dependency 'pg-dsn_parser'
    s.add_dependency 'dryml'
    s.add_dependency 'polytexnic'
    s.add_dependency 'vsphere-automation-vcenter'
    s.add_dependency 'reentrant_mutex'
    s.add_dependency 'fluent-plugin-file-alternative'
    s.add_dependency 'event_machine'
    s.add_dependency 'uri-js-rails'
    s.add_dependency 'redirector'
    s.add_dependency 'maxmind'
    s.add_dependency 'activeadmin-cancan'
    s.add_dependency 'showoff'
    s.add_dependency 'atv'
#    s.add_dependency 'metanorma-ogc'
#    s.add_dependency 'omniauth-box2'
    s.add_dependency 'fuubar-cucumber'
    s.add_dependency 'filigree'
    s.add_dependency 'attr_vault'
    s.add_dependency 'merb-haml'
#    s.add_dependency 'bookbindery'
    s.add_dependency 'sidecloq'
    s.add_dependency 'flexyear'
    s.add_dependency 'google-apis-people_v1'
#    s.add_dependency 'azure_sdk'
    s.add_dependency 'tinnef'
    s.add_dependency 'active_record-updated_at'
    s.add_dependency 'chef-handler-elapsed-time'
    s.add_dependency 'emblem-rails'
    s.add_dependency 'eventq_base'
    s.add_dependency 'rom-factory'
    s.add_dependency 'doing'
    s.add_dependency 's3-secure'
    s.add_dependency 'sidekiq-instrument'
#    s.add_dependency 'ey-scp'
#    s.add_dependency 'zillabyte'
    s.add_dependency 'active_admin_editor'
    s.add_dependency 'promiscuous'
    s.add_dependency 'hcl-checker'
#    s.add_dependency 'fullstack-admin'
    s.add_dependency 'blacklight_advanced_search'
    s.add_dependency 'rainforest-cli'
#    s.add_dependency 'jekyll-target-blank'
    s.add_dependency 'vsphere-automation-runtime'
    s.add_dependency 'cape'
    s.add_dependency 'panda_pal'
    s.add_dependency 'ruby_speech'
    s.add_dependency 'ceaser-easing'
    s.add_dependency 'activeadmin-xls'
    s.add_dependency 'active_rest_client'
#    s.add_dependency 'middleman-deploy'
    s.add_dependency 'morlock'
    s.add_dependency 'trestle-active_storage'
    s.add_dependency 'cloud66_agent'
    s.add_dependency 'omniauth-bigcommerce'
#    s.add_dependency 's3mpi'
    s.add_dependency 'em-hot_tub'
    s.add_dependency 'fastlane-plugin-download_file'
    s.add_dependency 'request_profiler'
#    s.add_dependency 'opener-callback-handler'
    s.add_dependency 'configlet'
    s.add_dependency 'ui_bibz'
    s.add_dependency 'arachni-reactor'
#    s.add_dependency 'turbo-sprockets-rails5'
    s.add_dependency 'sqeduler'
    s.add_dependency 'edtf'
}
