
  require 'rubygems'

Gem::Specification.new {|s|
    s.name          = 'pkg25'
    s.version       = '0.0.1'
    s.author        = 'Naresh Devasani'
    s.email         = 'naresh@endor.ai'
    s.homepage      = 'http://github.com/capotej/trollface'
    s.platform      = Gem::Platform::RUBY
    s.summary       = 'An empty gem that depends on every gem available'
    s.description   = s.summary

    s.add_dependency 'accentless'
    s.add_dependency 'quantified'
    s.add_dependency 'capistrano-locally'
    s.add_dependency 'td'
    s.add_dependency 'schmooze'
    s.add_dependency 'json_logic'
    s.add_dependency 'graphql-rails_logger'
    s.add_dependency 'orchestrator_client'
    s.add_dependency 'circleci'
    s.add_dependency 'filewatcher'
    s.add_dependency 'bootscale'
    s.add_dependency 'enumerable-lazy'
    s.add_dependency 'legato'
    s.add_dependency 'buildkite-test_collector'
    s.add_dependency 'predictor'
    s.add_dependency 'yard-activesupport-concern'
    s.add_dependency 'sigh'
    s.add_dependency 'active_admin_theme'
    s.add_dependency 'elastic-enterprise-search'
    s.add_dependency 'prmd'
    s.add_dependency 'nifty-generators'
    s.add_dependency 'aescrypt'
    s.add_dependency 'citeproc-ruby'
    s.add_dependency 'influxdb-client'
    s.add_dependency 'd2l-valence'
    s.add_dependency 'deprecated'
    s.add_dependency 'to-bool'
    s.add_dependency 'prawn_rails'
    s.add_dependency 'govuk_publishing_components'
    s.add_dependency 'em-proxy'
    s.add_dependency 'puppet-debugger'
    s.add_dependency 'amazon-ec2'
    s.add_dependency 'rubocop-packaging'
    s.add_dependency 'cocoapods-disable-podfile-validations'
    s.add_dependency 'datagrid'
    s.add_dependency 'rest'
    s.add_dependency 'animate-rails'
    s.add_dependency 'mustermann19'
    s.add_dependency 'traces'
    s.add_dependency 'solargraph-rails'
    s.add_dependency 'padrino-cache'
    s.add_dependency 'etcd-rb'
    s.add_dependency 'sablon'
    s.add_dependency 'scatter_swap'
    s.add_dependency 'daru'
    s.add_dependency 'csl'
    s.add_dependency 'action_policy-graphql'
    s.add_dependency 'm3u8'
    s.add_dependency 'libreconv'
    s.add_dependency 'fork_break'
    s.add_dependency 'echoe'
#    s.add_dependency 'storext'
    s.add_dependency 'activerecord-typedstore'
    s.add_dependency 'trailblazer-macro'
    s.add_dependency 'where-or'
    s.add_dependency 'ruby-terminfo'
    s.add_dependency 'wheretz'
    s.add_dependency 'grape-swagger-representable'
    s.add_dependency 'yamler'
    s.add_dependency 'stamp'
    s.add_dependency 'sentry-delayed_job'
    s.add_dependency 'fluent-plugin-suppress'
    s.add_dependency 'cnpj_validator'
    s.add_dependency 'bogo'
    s.add_dependency 'minitest-tagz'
    s.add_dependency 'google-cloud-debugger'
    s.add_dependency 'resque-heroku-signals'
    s.add_dependency 'dpl-elastic_beanstalk'
    s.add_dependency 'sfn'
    s.add_dependency 'eyes_core'
    s.add_dependency 'polaris_tokens'
    s.add_dependency 'commonthread-rails'
    s.add_dependency 'peek-redis'
    s.add_dependency 'omniauth-mailchimp'
    s.add_dependency 'pronto-stylelint'
    s.add_dependency 'attribute_struct'
    s.add_dependency 'ruby-plsql'
    s.add_dependency 'resque_solo'
    s.add_dependency 'exponent-server-sdk'
    s.add_dependency 'string-similarity'
    s.add_dependency 'soap4r'
#    s.add_dependency 'logstash-output-slack'
#    s.add_dependency 'msgpack-jruby'
    s.add_dependency 'fluent-plugin-splunk-enterprise'
    s.add_dependency 'omniauth-slack'
#    s.add_dependency 'konacha'
    s.add_dependency 'bcp47'
    s.add_dependency 'yabeda-rails'
    s.add_dependency 'peddler'
    s.add_dependency 'mangopay'
    s.add_dependency 'lorekeeper'
    s.add_dependency 'pg_lock'
    s.add_dependency 'puppet-lint-absolute_template_path'
    s.add_dependency 'daemon-spawn'
    s.add_dependency 'kitchen-dokken'
    s.add_dependency 'json-canonicalization'
    s.add_dependency 'fingerprintjs-rails'
    s.add_dependency 'sqreen-backport'
    s.add_dependency 'stateful_enum'
    s.add_dependency 'persistent_httparty'
    s.add_dependency 'launchdarkly_api'
    s.add_dependency 'barkick'
    s.add_dependency 'grover'
    s.add_dependency 'synx'
    s.add_dependency 'neo4j'
    s.add_dependency 'classifier'
    s.add_dependency 'jquery-placeholder-rails'
    s.add_dependency 'global'
    s.add_dependency 'raddocs'
    s.add_dependency 'olive_branch'
    s.add_dependency 'sequenced'
    s.add_dependency 'mongoid-audit_log'
    s.add_dependency 'railsless-deploy'
    s.add_dependency 'docker-sync'
    s.add_dependency 'docsplit'
    s.add_dependency 'csvlint'
#    s.add_dependency 'chef-cli'
    s.add_dependency 'action_args'
    s.add_dependency 'coveralls_reborn'
    s.add_dependency 'bloomfilter-rb'
#    s.add_dependency 'aws-sdk-tnb'
    s.add_dependency 'nested_form_fields'
    s.add_dependency 'cached_resource'
    s.add_dependency 'puppet-lint-classes_and_types_beginning_with_digits-check'
    s.add_dependency 'carrierwave-imageoptimizer'
    s.add_dependency 'tooltipster-rails'
#    s.add_dependency 'logstash-output-xmpp'
    s.add_dependency 'basecrm'
    s.add_dependency 'authtrail'
    s.add_dependency 'google-cloud-video_intelligence'
    s.add_dependency 'capybara-select-2'
#    s.add_dependency 'engineyard'
    s.add_dependency 'google-apis-calendar_v3'
#    s.add_dependency 'logstash-input-irc'
#    s.add_dependency 'logstash-input-xmpp'
    s.add_dependency 'google-cloud-spanner'
    s.add_dependency 'modis'
    s.add_dependency 'pronto-coffeelint'
    s.add_dependency 'newrelic_moped'
#    s.add_dependency 'pronto-prettier'
    s.add_dependency 'sprockets-svg'
    s.add_dependency 'file-dependencies'
    s.add_dependency 'opentelemetry-exporter-jaeger'
    s.add_dependency 'jquery-datatables'
    s.add_dependency 'kapnismology'
    s.add_dependency 'active_record-acts_as'
#    s.add_dependency 'wysihtml-rails'
#    s.add_dependency 'logstash-output-irc'
    s.add_dependency 'transitions'
    s.add_dependency 'td-logger'
    s.add_dependency 'request-log-analyzer'
    s.add_dependency 'gosu'
    s.add_dependency 'hash_diff'
    s.add_dependency 'approvals'
    s.add_dependency 'html_page'
    s.add_dependency 'unirest'
    s.add_dependency 'json-streamer'
#    s.add_dependency 'activerecord6-redshift-adapter'
    s.add_dependency 'zonebie'
    s.add_dependency 'flipper-dalli'
    s.add_dependency 'sidekiq-middleware'
    s.add_dependency 'rack-heartbeat'
    s.add_dependency 'coffee-rails-source-maps'
    s.add_dependency 'peek-gc'
    s.add_dependency 'cucumber-timecop'
#    s.add_dependency 'gemfury'
    s.add_dependency 'sequel-rails'
    s.add_dependency 'fast_trie'
    s.add_dependency 'sneaky-save'
    s.add_dependency 'trailblazer-macro-contract'
#    s.add_dependency 'rails-forward_compatible_controller_tests'
    s.add_dependency 'atoulme-Antwrap'
    s.add_dependency 'miasma-aws'
    s.add_dependency 'rtf'
    s.add_dependency 'oat'
    s.add_dependency 'kitchen-sync'
    s.add_dependency 'dm-postgres-adapter'
    s.add_dependency 'workers'
    s.add_dependency 'rspec-request_describer'
#    s.add_dependency 'treye-semaphore_test_boosters'
    s.add_dependency 'beaker-vagrant'
#    s.add_dependency 'treye-semaphore_cucumber_booster_config'
    s.add_dependency 'chargify_api_ares'
    s.add_dependency 'airrecord'
    s.add_dependency 'slack-notify'
    s.add_dependency 'scan'
    s.add_dependency 'dep-selector-libgecode'
    s.add_dependency 'guard-sidekiq'
    s.add_dependency 'tilt-jbuilder'
    s.add_dependency 'net_http_ssl_fix'
    s.add_dependency 'migration-lock-timeout'
    s.add_dependency 'google-cloud-dns'
    s.add_dependency 'rambulance'
    s.add_dependency 'pulp_ansible_client'
    s.add_dependency 'mandrill-api-json'
    s.add_dependency 'puppet-lint-trailing_newline-check'
    s.add_dependency 'pilot'
    s.add_dependency 'deadlock_retry'
    s.add_dependency 'spree_auth_devise'
    s.add_dependency 'rom'
    s.add_dependency 'ruby-openai'
    s.add_dependency 'zabbixapi'
    s.add_dependency 'fxruby'
    s.add_dependency 'dbi'
    s.add_dependency 'configure-s3-website'
    s.add_dependency 'stupidedi'
    s.add_dependency 'daybreak'
    s.add_dependency 'paranoia_uniqueness_validator'
    s.add_dependency 'scout'
    s.add_dependency 'modulejs-rails'
    s.add_dependency 'route_downcaser'
    s.add_dependency 'mysql-binuuid-rails'
    s.add_dependency 'nilio'
    s.add_dependency 'formulaic'
    s.add_dependency 'puppet-lint-resource_reference_syntax'
    s.add_dependency 'break'
    s.add_dependency 'google-cloud-vision-v1'
#    s.add_dependency 'aws-sdk-internetmonitor'
    s.add_dependency 'ruby_protobuf'
#    s.add_dependency 'match'
    s.add_dependency 'phonie'
    s.add_dependency 'noticed'
    s.add_dependency 'open-uri-cached'
    s.add_dependency 'tdiff'
    s.add_dependency 'fancybox-rails'
    s.add_dependency 'rodf'
#    s.add_dependency 'sensu-plugins-chef'
    s.add_dependency 'fluent-plugin-rabbitmq'
    s.add_dependency 'google-cloud-vision-v1p3beta1'
    s.add_dependency 'query_reviewer'
#    s.add_dependency 'bootstrap-slider-rails'
    s.add_dependency 'rails_warden'
    s.add_dependency 'prerender_rails'
    s.add_dependency 'google-cloud-resource_manager'
#    s.add_dependency 'jquery-cookie-rails'
    s.add_dependency 'actionmailer-text'
    s.add_dependency 'nokogiri-styles'
    s.add_dependency 'opentelemetry-resource_detectors'
    s.add_dependency 'patternfly-sass'
    s.add_dependency 'grape-route-helpers'
    s.add_dependency 'screw_driver'
    s.add_dependency 'jquery_mask_rails'
#    s.add_dependency 'logstash-output-datadog_logs'
    s.add_dependency 'to_words'
#    s.add_dependency 'airbrake_handler'
    s.add_dependency 'erb2haml'
    s.add_dependency 'miasma'
    s.add_dependency 'tracker_api'
    s.add_dependency 'chef-api'
    s.add_dependency 'marco-polo'
}
