
  require 'rubygems'

Gem::Specification.new {|s|
    s.name          = 'pkg38'
    s.version       = '0.0.1'
    s.author        = 'naresh'
    s.email         = 'nareshdevasani@gmail.com'
    s.homepage      = 'http://github.com/nareshdevasani'
    s.platform      = Gem::Platform::RUBY
    s.summary       = 'An empty gem that depends on every gem available'
    s.description   = s.summary

    s.add_dependency 'pp'
    s.add_dependency 'administrate-field-enum'
    s.add_dependency 'scrivito_editors'
    s.add_dependency 'unobtainium-multiwait'
    s.add_dependency 'active_scaffold_vho'
    s.add_dependency 'oci'
    s.add_dependency 'formatter-number'
    s.add_dependency 'dwc-archive'
    s.add_dependency 'auto_test'
    s.add_dependency 'jquery-tmpl-rails'
    s.add_dependency 'kredis'
    s.add_dependency 'sys-uptime'
    s.add_dependency 'spree_dash'
    s.add_dependency 'oa-more'
    s.add_dependency 'shellwords'
    s.add_dependency 'dartsass-rails'
#    s.add_dependency 'sparkpost_rails'
    s.add_dependency 'fastly-rails'
    s.add_dependency 'coupon_code'
    s.add_dependency 'acceptance_test'
    s.add_dependency 'pheme'
    s.add_dependency 'ruby-sox'
#    s.add_dependency 'opener-daemons'
    s.add_dependency 'doc_to_dash'
#    s.add_dependency 'kitchen-terraform'
    s.add_dependency 'relaton-ietf'
    s.add_dependency 'async-await'
    s.add_dependency 'remarkable'
    s.add_dependency 'html2markdown'
    s.add_dependency 'eyes_appium'
    s.add_dependency 'mysql_stay_connected'
    s.add_dependency 'omniauth-github-team-member'
    s.add_dependency 'fluent-plugin-fields-autotype'
    s.add_dependency 'activerecord-jdbcmssql-adapter'
    s.add_dependency 'konacha-chai-matchers'
    s.add_dependency 'sweet-alert-confirm'
    s.add_dependency 'yotpo'
    s.add_dependency 'smartcloud'
#    s.add_dependency 'puppet-doc-lint'
    s.add_dependency 'nameable'
    s.add_dependency 'ws-style'
    s.add_dependency 'ffi-vix_disk_lib'
    s.add_dependency 'graphiti-rails'
    s.add_dependency 'assignable_values'
    s.add_dependency 'rails_admin_history_rollback'
    s.add_dependency 'goshortener'
    s.add_dependency 'brI18n'
    s.add_dependency 'Active'
    s.add_dependency 'test-spec'
    s.add_dependency 'easyoptions'
    s.add_dependency 'verbalize'
    s.add_dependency 'formatter-date'
    s.add_dependency 'tainbox'
    s.add_dependency 'detabulator'
    s.add_dependency 'torid'
    s.add_dependency 'yard-rails'
    s.add_dependency 'outbound'
    s.add_dependency 'statsmix'
    s.add_dependency 'livingstyleguide'
    s.add_dependency 'multi_logger'
    s.add_dependency 'slack-poster'
    s.add_dependency 'hydra'
    s.add_dependency 'view_component_storybook'
    s.add_dependency 'omniauth-quickbooks'
    s.add_dependency 'fastlane-plugin-update_xcodeproj'
    s.add_dependency 'csso-rails'
    s.add_dependency 'fluent-plugin-filter'
    s.add_dependency 'sensu-extensions-deregistration'
    s.add_dependency 'canistor'
    s.add_dependency 'rack-app'
    s.add_dependency 'decent_decoration'
    s.add_dependency 'unobtrusive_flash'
    s.add_dependency 'cobweb'
    s.add_dependency 'graphql-cache'
    s.add_dependency 'acts-as-dag'
    s.add_dependency 'img2zpl'
    s.add_dependency 'canonix'
    s.add_dependency 'watu_table_builder'
    s.add_dependency 'fluent-plugin-loki'
    s.add_dependency 'heroku_rails_deflate'
    s.add_dependency 'markerb'
    s.add_dependency 'hash_to_hidden_fields'
#    s.add_dependency 'grape-entity-matchers'
    s.add_dependency 'canard'
    s.add_dependency 'rb-libsvm'
    s.add_dependency 'sensu-plugins-memcached'
    s.add_dependency 'touchpunch-rails'
#    s.add_dependency 'buweb_content_models'
    s.add_dependency 'yam'
    s.add_dependency 'spring-commands-thor'
    s.add_dependency 'test-unit-notify'
    s.add_dependency 'scout_rails'
    s.add_dependency 'kramdown-rfc2629'
    s.add_dependency 'formatter'
    s.add_dependency 'navigasmic'
    s.add_dependency 'repman'
#    s.add_dependency 'rocket_cms'
#    s.add_dependency 'logstash-input-cloudwatch_logs'
    s.add_dependency 'pact-provider-verifier'
    s.add_dependency 'jquery-inputmask-rails'
#    s.add_dependency 'ddr-models'
    s.add_dependency 'ruby_deep_clone'
    s.add_dependency 'evergreen'
    s.add_dependency 'opentelemetry-sdk-experimental'
    s.add_dependency 'messengerjs-rails'
    s.add_dependency 'respec'
    s.add_dependency 'asset_cloud'
    s.add_dependency 'jsonapi-resources-matchers'
    s.add_dependency 'carrierwave-sequel'
    s.add_dependency 'minitest-proveit'
    s.add_dependency 'postcodeanywhere'
    s.add_dependency 'waistband'
    s.add_dependency 'jquery-easing-rails'
    s.add_dependency 'unicode-scripts'
    s.add_dependency 'async-container'
    s.add_dependency 'restrainer'
    s.add_dependency 'netsnmp'
    s.add_dependency 's3cp'
    s.add_dependency 'fluent-plugin-parser-logfmt'
    s.add_dependency 'auser-poolparty'
    s.add_dependency 'capones_recipes'
    s.add_dependency 'flipper-cloud'
    s.add_dependency 'websocket-rails'
    s.add_dependency 'fastlane-plugin-telegram'
#    s.add_dependency 'phcpress'
    s.add_dependency 'lightstep'
    s.add_dependency 'bank-contact'
    s.add_dependency 'nexus_cli'
    s.add_dependency 'sinatra-content-for2'
    s.add_dependency 'clutter'
    s.add_dependency 'rspec-todo'
    s.add_dependency 'time_for_a_boolean'
    s.add_dependency 'data-anonymization'
    s.add_dependency 'fluent-plugin-docker_metadata_filter'
    s.add_dependency 'active_reload'
    s.add_dependency 'btce'
    s.add_dependency 'google_url_shortener'
    s.add_dependency 'aws-mfa-secure'
    s.add_dependency 'jasmine_selenium_runner'
    s.add_dependency 'arcanus'
    s.add_dependency 'restfully'
    s.add_dependency 'wordmove'
#    s.add_dependency 'resque-smtp'
    s.add_dependency 'unicode-confusable'
    s.add_dependency 'greenhouse_io'
    s.add_dependency 'rack-request-id'
    s.add_dependency 'ruco'
    s.add_dependency 'nagios_check'
#    s.add_dependency 'linkedin-oauth2'
    s.add_dependency 'ar-extensions'
    s.add_dependency 'utf8_utils'
    s.add_dependency 'google_plus'
    s.add_dependency 'opengraph_parser'
    s.add_dependency 'aquarium'
    s.add_dependency 'table_sync'
    s.add_dependency 'secrets-manager'
    s.add_dependency 'fui'
    s.add_dependency 'kubernetes-deploy'
    s.add_dependency 'paypal-recurring'
    s.add_dependency 'selenium_remote_control'
    s.add_dependency 'ruby-debug-base19x'
    s.add_dependency 'sportdb'
    s.add_dependency 'jekyll-data'
    s.add_dependency 'fpm-cookery'
    s.add_dependency 'socialization'
    s.add_dependency 'ldp'
    s.add_dependency 'ecs-logging'
#    s.add_dependency 'hydra-derivatives'
    s.add_dependency 'paloma'
    s.add_dependency 'bootstrap-colorpicker-rails'
    s.add_dependency 'ru_propisju'
    s.add_dependency 'azure_mgmt_monitor'
    s.add_dependency 'multipart-parser'
    s.add_dependency 'rspec-webservice_matchers'
    s.add_dependency 'branch_io'
    s.add_dependency 'wovnrb'
    s.add_dependency 'clutter-gtk'
    s.add_dependency 'puppet-lint-appends-check'
    s.add_dependency 'brakeman-min'
    s.add_dependency 'labelary'
    s.add_dependency 'tf-idf-similarity'
    s.add_dependency 'flipper-activerecord'
    s.add_dependency 'rubyflare'
    s.add_dependency 'blimpy'
    s.add_dependency 'omniauth-windowslive'
    s.add_dependency 'memoized'
    s.add_dependency 'martile'
    s.add_dependency 'jshint'
    s.add_dependency 'zabbix'
    s.add_dependency 'asciidoctor-jenkins-extensions'
    s.add_dependency 'border_patrol'
    s.add_dependency 'arturo'
    s.add_dependency 'enumerated_type'
    s.add_dependency 'sequel-annotate'
    s.add_dependency 'ama_layout'
    s.add_dependency 'cli_markdown'
    s.add_dependency 'kitchen-openstack'
    s.add_dependency 'ProMotion'
#    s.add_dependency 'phccontentpack'
    s.add_dependency 'sniff'
    s.add_dependency 'private_pub'
    s.add_dependency 'ingreedy'
#    s.add_dependency 'torquebox'
    s.add_dependency 'wikipedia-client'
    s.add_dependency 'administrate-field-jsonb'
    s.add_dependency 'pact-provider-proxy'
    s.add_dependency 'databasedotcom-rails'
    s.add_dependency 'refinerycms-settings'
    s.add_dependency 'omniauth-steam'
    s.add_dependency 'active_record_bulk_insert'
    s.add_dependency 'gtksourceview3'
    s.add_dependency 'mparticle'
    s.add_dependency 'active_record_slave'
    s.add_dependency 'global_session'
    s.add_dependency 'base62-rb'
    s.add_dependency 'jekyll-minifier'
    s.add_dependency 'string-to-bool'
    s.add_dependency 'relation_to_struct'
    s.add_dependency 'authpwn_rails'
    s.add_dependency 'double_restraint'
    s.add_dependency 'dike'
    s.add_dependency 'confetti'
    s.add_dependency 'mustache-js-rails'
    s.add_dependency 'azure-storage-queue'
    s.add_dependency 'PoParser'
#    s.add_dependency 'marketingcloudsdk'
#    s.add_dependency 'torquebox-messaging'
    s.add_dependency 'negative_captcha'
    s.add_dependency 'contentful-webhook-listener'
    s.add_dependency 'todonotes'
    s.add_dependency 'facebook_ads'
    s.add_dependency 'fastlane-plugin-settings_bundle'
    s.add_dependency 'pronto-json'
    s.add_dependency 'tire-contrib'
    s.add_dependency 'errplane'
    s.add_dependency 'binding.repl'
    s.add_dependency 'no_peeping_toms'
    s.add_dependency 'ansible_tower_client'
    s.add_dependency 'blitline'
    s.add_dependency 'cssminify'
    s.add_dependency 'openscap'
    s.add_dependency 'coffee-filter'
    s.add_dependency 'new_google_recaptcha'
    s.add_dependency 'randumb'
    s.add_dependency 'fast_xor'
    s.add_dependency 'omniauth-wsfed'
    s.add_dependency 'fancy-buttons'
    s.add_dependency 'thor-zsh_completion'
    s.add_dependency 'adsf'
    s.add_dependency 'cheat'

}
