
  require 'rubygems'

Gem::Specification.new {|s|
    s.name          = 'pkg12'
    s.version       = '0.0.1'
    s.author        = 'Julio Capote'
    s.email         = 'jcapote@gmail.com'
    s.homepage      = 'http://github.com/capotej/trollface'
    s.platform      = Gem::Platform::RUBY
    s.summary       = 'An empty gem that depends on every gem available'
    s.description   = s.summary

    s.add_dependency 'jquery-datatables-rails'
    s.add_dependency 'histogram'
    s.add_dependency 'jls-grok'
    s.add_dependency 'padrino-helpers'
    s.add_dependency 'rerun'
    s.add_dependency 'fluent-plugin-gelf-hs'
    s.add_dependency 'debugger'
    s.add_dependency 'aliyun-sdk'
    s.add_dependency 'gem-wrappers'
    s.add_dependency 'rubocop-git'
    s.add_dependency 'opentelemetry-semantic_conventions'
    s.add_dependency 'algoliasearch-rails'
    s.add_dependency 'deface'
    s.add_dependency 'aws-sdk-redshiftserverless'
    s.add_dependency 'ruby-prof-flamegraph'
    s.add_dependency 'request_store-sidekiq'
#    s.add_dependency 'rbovirt'
#    s.add_dependency 'librato-metrics'
#    s.add_dependency 'jsonapi-resources'
#    s.add_dependency 'opentelemetry-instrumentation-rack'
#    s.add_dependency 'rails-settings-cached'
    s.add_dependency 'chosen-rails'
    s.add_dependency 'houston'
    s.add_dependency 'shoulda-callback-matchers'
    s.add_dependency 'opentelemetry-instrumentation-base'
#    s.add_dependency 'logstash-codec-line'
    s.add_dependency 'url_safe_base64'
    s.add_dependency 'capistrano3-puma'
    s.add_dependency 'fastlane-plugin-sentry'
    s.add_dependency 'fluent-plugin-record-reformer'
    s.add_dependency 'rubocop-shopify'
    s.add_dependency 'jgrep'
    s.add_dependency 'gooddata-dss-jdbc'
    s.add_dependency 'ahoy_matey'
#    s.add_dependency 'logstash-input-stdin'
#    s.add_dependency 'aws-sdk-connectcampaignservice'
    s.add_dependency 'erb_lint'
#    s.add_dependency 'aws-sdk-pinpointsmsvoicev2'
    s.add_dependency 'sensu-plugins-http'
#    s.add_dependency 'logstash-codec-json'
#    s.add_dependency 'logstash-codec-json_lines'
    s.add_dependency 'fasterer'
    s.add_dependency 'puppet-resource_api'
    s.add_dependency 'jekyll-gist'
    s.add_dependency 'streamio-ffmpeg'
    s.add_dependency 'simple-graphite'
    s.add_dependency 'rack-ssl-enforcer'
    s.add_dependency 'guard-minitest'
    s.add_dependency 'librarian-puppet'
    s.add_dependency 'google-cloud-trace'
    s.add_dependency 'simple_enum'
    s.add_dependency 'libdatadog'
    s.add_dependency 'syntax_tree'
    s.add_dependency 'aws-sdk-mainframemodernization'
    s.add_dependency 'railroady'
    s.add_dependency 'dbus-systemd'
    s.add_dependency 'telephone_number'
#    s.add_dependency 'logstash-codec-netflow'
    s.add_dependency 'rvm-capistrano'
#    s.add_dependency 'logstash-input-udp'
#    s.add_dependency 'logstash-output-file'
#    s.add_dependency 'logstash-codec-rubydebug'
#    s.add_dependency 'logstash-filter-json'
    s.add_dependency 'redis-classy'
#    s.add_dependency 'logstash-filter-http'
#    s.add_dependency 'logstash-input-redis'
    s.add_dependency 'dnsbl-client'
    s.add_dependency 'neatjson'
    s.add_dependency 'redis-mutex'
    s.add_dependency 'hashid-rails'
    s.add_dependency 'pandoc-ruby'
    s.add_dependency 'grape-swagger-rails'
#    s.add_dependency 'logstash-filter-csv'
    s.add_dependency 'prettier_print'
    s.add_dependency 'sorbet-rails'
    s.add_dependency 'report_builder'
    s.add_dependency 'jsonapi-parser'
    s.add_dependency 'sysrandom'
#    s.add_dependency 'logstash-output-udp'
    s.add_dependency 'angularjs-rails'
    s.add_dependency 'god'
    s.add_dependency 'rubocop-capybara'
#    s.add_dependency 'logstash-codec-collectd'
    s.add_dependency 'wirble'
    s.add_dependency 'sensu-plugins-network-checks'
}
