
  require 'rubygems'

Gem::Specification.new {|s|
    s.name          = 'pkg40'
    s.version       = '0.0.1'
    s.author        = 'Naresh Devasani'
    s.email         = 'naresh@endor.ai'
    s.homepage      = 'http://github.com/capotej/trollface'
    s.platform      = Gem::Platform::RUBY
    s.summary       = 'An empty gem that depends on every gem available'
    s.description   = s.summary

    s.add_dependency 'miga-base'
    s.add_dependency 'autotest-rails-pure'
    s.add_dependency 'papercrop'
    s.add_dependency 'eslintrb'
    s.add_dependency 'hobo_support'
#    s.add_dependency 'cookbooks'
    s.add_dependency 'signalfx-tracing'
    s.add_dependency 'pstore'
    s.add_dependency 'bpm_manager'
#    s.add_dependency 'fanforce-plugin-factory'
    s.add_dependency 'ruby-push-notifications'
    s.add_dependency 'cybrid_api_bank_ruby'
    s.add_dependency 'determinator'
    s.add_dependency 'zuora-ruby'
    s.add_dependency 'rubocop-config-umbrellio'
    s.add_dependency 'mobvious-rails'
    s.add_dependency 'bounding_boxes'
    s.add_dependency 'rak'
    s.add_dependency 'bettercap'
    s.add_dependency 'cybrid_api_id_ruby'
    s.add_dependency 'jekyll-email-protect'
    s.add_dependency 'journaled'
    s.add_dependency 'puppet-lint-package_ensure-check'
    s.add_dependency 'http_configuration'
    s.add_dependency 'merb-core'
    s.add_dependency 'jquery-cropper'
    s.add_dependency 'trestle-search'
    s.add_dependency 'rspec-system'
    s.add_dependency 'validates_existence'
    s.add_dependency 'getoptlong'
    s.add_dependency 'memo_wise'
    s.add_dependency 'azure-signature'
    s.add_dependency 'google-cloud-asset'
    s.add_dependency 'abundance'
    s.add_dependency 'hawkular-client'
    s.add_dependency 'webpay'
    s.add_dependency 'rabbit_messaging'
    s.add_dependency 'omniauth-multi-provider'
    s.add_dependency 'rb-gsl'
    s.add_dependency 'tlattr_accessors'
    s.add_dependency 'alphabetical_paginate'
    s.add_dependency 'ae_page_objects'
    s.add_dependency 'detect_timezone_rails'
    s.add_dependency 'tweetstream'
    s.add_dependency 'riposte'
    s.add_dependency 'softwear-lib'
    s.add_dependency 'quirc'
    s.add_dependency 'pinterest-api'
    s.add_dependency 'comfy_bootstrap_form'
    s.add_dependency 'ufo'
    s.add_dependency 'fastlane-plugin-run_tests_firebase_testlab'
    s.add_dependency 'pngdefry'
    s.add_dependency 'progress_job'
    s.add_dependency 'clutter-gstreamer'
    s.add_dependency 'appscms-tools-theme'
    s.add_dependency 'morpheus-cli'
    s.add_dependency 'puppet-module-posix-default-r2.7'
    s.add_dependency 'wunderground'
    s.add_dependency 'more_possessive'
    s.add_dependency 'relish'
    s.add_dependency 'url2png'
    s.add_dependency 'mailcvt'
    s.add_dependency 'chainable_methods'
    s.add_dependency 'scraped'
    s.add_dependency 'expeditor'
    s.add_dependency 'routemaster-drain'
    s.add_dependency 'gorillib'
    s.add_dependency 'paul_bunyan'
    s.add_dependency 'ordinalize_full'
    s.add_dependency 'textilize'
    s.add_dependency 'structured'
    s.add_dependency 'paleta'
    s.add_dependency 'lever_postings'
    s.add_dependency 'r7insight'
    s.add_dependency 'dip'
    s.add_dependency 'google_calendar'
#    s.add_dependency 'mas-rad_core'
    s.add_dependency 'guard-compass'
    s.add_dependency 'acts-as-messageable'
    s.add_dependency 'dm-active_model'
    s.add_dependency 'hammerjs-rails'
    s.add_dependency 'relaton-iso-bib'
    s.add_dependency 'cybrid_api_organization_ruby'
#    s.add_dependency 'hydra-works'
    s.add_dependency 'blacklight-spotlight'
    s.add_dependency 'zotplus-rakehelper'
    s.add_dependency 'daemon-kit'
    s.add_dependency 'paypal-sdk-adaptiveaccounts'
    s.add_dependency 'et_full_system'
    s.add_dependency 'svg-graph'
    s.add_dependency 'shindo'
    s.add_dependency 'google-search'
#    s.add_dependency 'chef-provisioning-aws'
    s.add_dependency 'system_cat'
    s.add_dependency 'fast_haversine'
    s.add_dependency 'sidekiq-pool'
#    s.add_dependency 'logstash-output-mongodb'
    s.add_dependency 'app_conf'
    s.add_dependency 'mandy'
    s.add_dependency 'svg_optimizer'
#    s.add_dependency 'aws_security_viz'
    s.add_dependency 'convert_api'
    s.add_dependency 'giphy'
    s.add_dependency 'attr_encryptor'
    s.add_dependency 'fcgi'
#    s.add_dependency 'torquebox-transactions'
    s.add_dependency 'keycloak'
#    s.add_dependency 'vulcan'
    s.add_dependency 'gdata'
    s.add_dependency 'svgeez'
    s.add_dependency 'monit'
    s.add_dependency 'dorsale'
    s.add_dependency 'munin-ruby'
    s.add_dependency 'subdomain-fu'
    s.add_dependency 'delayed-plugins-airbrake'
    s.add_dependency 'bootstrap-datetimepicker-rails'
    s.add_dependency 'gmetric'
    s.add_dependency 'market_bot'
    s.add_dependency 'xray'
    s.add_dependency 'minitest-silence'
    s.add_dependency 'bipbip'
    s.add_dependency 'api-versions'
    s.add_dependency 'confg'
    s.add_dependency 'cssminify2'
    s.add_dependency 'sugar-rails'
    s.add_dependency 'ori'
    s.add_dependency 'linux_block_device'
    s.add_dependency 'stoplight-admin'
    s.add_dependency 'google-cloud-recaptcha_enterprise'
    s.add_dependency 'cocoapods-fix-react-native'
    s.add_dependency 'kuhsaft'
    s.add_dependency 'trusty-cms'
    s.add_dependency 'omniauth-google-apps'
    s.add_dependency 'rubysl-open3'
    s.add_dependency 'sprig'
    s.add_dependency 'itaiji'
    s.add_dependency 'haml-contrib'
    s.add_dependency 'fixed_width_file_parser'
#    s.add_dependency 'rocket_cms_activerecord'
    s.add_dependency 'cloudfront-invalidator'
    s.add_dependency 'private_gem'
    s.add_dependency 'block_helpers'
    s.add_dependency 'google-cloud-redis'
    s.add_dependency 'vgs_api_client'
    s.add_dependency 'concerning'
#    s.add_dependency 'enju_biblio'
    s.add_dependency 'conjur-debify'
    s.add_dependency 'ejson_wrapper'
#    s.add_dependency 'metanorma-cli'
    s.add_dependency 'mercadopago-sdk'
    s.add_dependency 'ruby-keychain'
    s.add_dependency 'front_matter_parser'
    s.add_dependency 'relaton-iec'
    s.add_dependency 'hash_kit'
    s.add_dependency 'rt-watchman'
    s.add_dependency 'hako'
#    s.add_dependency 'kumogata'
#    s.add_dependency 'torquebox-stomp'
    s.add_dependency 'cron-parser'
    s.add_dependency 'choices'
    s.add_dependency 'redis-ick'
    s.add_dependency 'cash-addr'
#    s.add_dependency 'rubocop-junit_formatter'
    s.add_dependency 'dependor'
    s.add_dependency 'unobtainium-cucumber'
    s.add_dependency 'signalfx-rails-instrumentation'
    s.add_dependency 'lunchy'
    s.add_dependency 'uri-handler'
    s.add_dependency 'html_validation'
#    s.add_dependency 'torquebox-configure'
    s.add_dependency 'sequel_postgresql_triggers'
    s.add_dependency 'accounts_client'
    s.add_dependency 'humidifier'
    s.add_dependency 'fluent-plugin-gcs'
    s.add_dependency 'stimpack'
    s.add_dependency 'vagrant-parallels'
    s.add_dependency 'brightcove-api'
#    s.add_dependency 'torquebox-cache'
    s.add_dependency 'blocks'
    s.add_dependency 'failbot'
    s.add_dependency 'activerecord-postgres-earthdistance'
    s.add_dependency 'pulp_ostree_client'
    s.add_dependency 'hubspot_event'
#    s.add_dependency 'rocket_cms_mongoid'
    s.add_dependency 'resque-lonely_job'
    s.add_dependency 'rexec'
    s.add_dependency 'knife-zero'
    s.add_dependency 'uniqueness'
    s.add_dependency 'arachni-rpc'
    s.add_dependency 'jcompiler'
    s.add_dependency 'rake_factory'
    s.add_dependency 'walker_method'
    s.add_dependency 'pkcs11'
    s.add_dependency 'pdftotext'
    s.add_dependency 'compass_twitter_bootstrap'
    s.add_dependency 'flash_cookie_session'
    s.add_dependency 'opentelemetry-instrumentation-rake'
#    s.add_dependency 'torquebox-security'
    s.add_dependency 'eyes_capybara'
    s.add_dependency 'rails-data-migrations'
    s.add_dependency 'webpagetest'
#    s.add_dependency 'relaton-cli'
#    s.add_dependency 'sambot'
    s.add_dependency 'jquery-infinite-pages'
    s.add_dependency 'user_impersonate2'
    s.add_dependency 'cucumber-rails-training-wheels'
    s.add_dependency 'thermite'
    s.add_dependency 'google_search_results'
    s.add_dependency 'cacert'
    s.add_dependency 'jpush'
    s.add_dependency 'rmodbus'
    s.add_dependency 'restclient_with_cert'
    s.add_dependency 'lockup'
    s.add_dependency 'warden-oauth2'
    s.add_dependency 'active_record_distinct_on'
    s.add_dependency 'abanalyzer'
    s.add_dependency 'lederhosen'
    s.add_dependency 'minitest-color'
    s.add_dependency 'mms2r'
    s.add_dependency 'ovirt'
    s.add_dependency 'lolcommits'
    s.add_dependency 'fusuma'
#    s.add_dependency 'puppet-module-posix-dev-r2.7'
    s.add_dependency 'memory_buffer'
    s.add_dependency 'sequel_bitemporal'
    s.add_dependency 'rtlit'
    s.add_dependency 'sql_tracker'
    s.add_dependency 'multi_db'
    s.add_dependency 'tcr'
    s.add_dependency 'simple_spark'
    s.add_dependency 'ruby_regex'
    s.add_dependency 'gameon'
    s.add_dependency 'win32-mmap'
#    s.add_dependency 'pry-send_tweet.rb'
    s.add_dependency 'compass-susy-plugin'
    s.add_dependency 'dm-ar-finders'
    s.add_dependency 'lumber'
#    s.add_dependency 't'
    s.add_dependency 'typus'
    s.add_dependency 'evernote_oauth'
    s.add_dependency 'deprec'
    s.add_dependency 'net-ssh-session'
    s.add_dependency 'crossing'
#    s.add_dependency 'nixenvironment'
    s.add_dependency 'muck-raker'
    s.add_dependency 'image-inspector-client'
    s.add_dependency 'chef-handler-opsmatic'
    s.add_dependency 'panda'
#    s.add_dependency 'chef-expander'
    s.add_dependency 'ordered_set'

}
