
  require 'rubygems'

Gem::Specification.new {|s|
    s.name          = 'pkg37'
    s.version       = '0.0.1'
    s.author        = 'naresh'
    s.email         = 'nareshdevasani@gmail.com'
    s.homepage      = 'http://github.com/nareshdevasani'
    s.platform      = Gem::Platform::RUBY
    s.summary       = 'An empty gem that depends on every gem available'
    s.description   = s.summary

    s.add_dependency 'google-cloud-location'
    s.add_dependency 'countdownlatch'
    s.add_dependency 'cocoapods-tdfire-binary'
    s.add_dependency 'adal'
    s.add_dependency 'null_logger'
    s.add_dependency 'clickhouse-activerecord'
    s.add_dependency 'simple_xlsx_writer'
    s.add_dependency 'peek-git'
    s.add_dependency 'acl9'
#    s.add_dependency 'activeadmin-selleo-cms'
    s.add_dependency 'torquebox-rake-support'
    s.add_dependency 'xml-sitemap'
    s.add_dependency 'verse'
    s.add_dependency 'debouncer'
    s.add_dependency 'cocoapods-clean'
    s.add_dependency 'opensrs'
    s.add_dependency 'mapping'
    s.add_dependency 'redgreen'
#    s.add_dependency 'schema_plus_tables'
    s.add_dependency 'websocket-eventmachine-client'
    s.add_dependency 'rails_safe_tasks'
    s.add_dependency 'i18n_country_select'
    s.add_dependency 'tty'
    s.add_dependency 'rethinkdb'
    s.add_dependency 'has-bit-field'
    s.add_dependency 'wraith'
    s.add_dependency 'rubydora'
    s.add_dependency 'rackup'
    s.add_dependency 'factory_bot-preload'
    s.add_dependency 'daff'
    s.add_dependency 'cowtech-rails'
    s.add_dependency 'ruby-rtf'
    s.add_dependency 'browse-everything'
    s.add_dependency 'jcrop-rails-v2'
    s.add_dependency 'specgen'
    s.add_dependency 'avo'
    s.add_dependency 'grape-instrumentation'
    s.add_dependency 'delegate'
    s.add_dependency 'warden-github'
    s.add_dependency 'dynarex-blog'
    s.add_dependency 'scraperwiki'
#    s.add_dependency 'json-jruby'
#    s.add_dependency 'rubysl'
    s.add_dependency 'compare-xml'
    s.add_dependency 'discourse-ember-source'
    s.add_dependency 'schema_registry'
    s.add_dependency 'apt-spy2'
    s.add_dependency 'fiscali'
#    s.add_dependency 'coalescing_panda'
    s.add_dependency 'nested_layouts'
    s.add_dependency 'jsonrpc-client'
    s.add_dependency 'solano'
    s.add_dependency 'tbpgr_utils'
    s.add_dependency 'expressir'
    s.add_dependency 'store_attribute'
    s.add_dependency 'sass-media_query_combiner'
    s.add_dependency 'sms-spec'
    s.add_dependency 'compass-colors'
    s.add_dependency 'activeadmin-select2'
#    s.add_dependency 'rabbitmq_manager'
    s.add_dependency 'methodfinder'
    s.add_dependency 'dpl-bintray'
    s.add_dependency 'sourcemap'
    s.add_dependency 'stack_master'
    s.add_dependency 'beetle'
    s.add_dependency 'rails_failover'
    s.add_dependency 'gindex'
    s.add_dependency 'r18n-desktop'
    s.add_dependency 'forward'
    s.add_dependency 'aslakhellesoy-cucumber'
    s.add_dependency 'ebcdic_converter'
    s.add_dependency 'transactional_capybara'
    s.add_dependency 'validates_formatting_of'
    s.add_dependency 'active_campaign'
    s.add_dependency 'socialcast-git-extensions'
    s.add_dependency 'fluent-plugin-rewrite'
    s.add_dependency 'capistrano-scm-none'
#    s.add_dependency 'farscape'
    s.add_dependency 'resque-batched-job'
    s.add_dependency 'win32-event'
    s.add_dependency 'netzke-basepack'
    s.add_dependency 'fastlane-plugin-android_change_package_identifier'
    s.add_dependency 'concur'
    s.add_dependency 'fluent-plugin-genhashvalue'
    s.add_dependency 'test-unit-context'
    s.add_dependency 'klaviyo'
#    s.add_dependency 'middleman-dotenv'
    s.add_dependency 'fluent-plugin-timescaledb'
    s.add_dependency 'pil'
    s.add_dependency 'props'
    s.add_dependency 'tracer'
    s.add_dependency 'fastlane-plugin-slack_bot'
    s.add_dependency 'couchrest_model'
    s.add_dependency 'mailread'
    s.add_dependency 'readline-ext'
    s.add_dependency 'deject'
    s.add_dependency 'listjs-rails'
    s.add_dependency 'metanorma'
    s.add_dependency 'capify-ec2'
    s.add_dependency 'shrine-google_cloud_storage'
    s.add_dependency 'base91'
    s.add_dependency 'omniauth-greenhouse'
    s.add_dependency 'clickhouse'
    s.add_dependency 'simple-navigation-bootstrap'
    s.add_dependency 'praxis'
    s.add_dependency 'state_machine_rspec'
#    s.add_dependency 'ds-gui-automation'
    s.add_dependency 'bindler'
    s.add_dependency 'trocla'
    s.add_dependency 'simple_bdd'
#    s.add_dependency 'pry-debugger-jruby'
    s.add_dependency 'tmail'
    s.add_dependency 'spork-minitest'
    s.add_dependency 'rejectu'
    s.add_dependency 'method_profiler'
    s.add_dependency 'pidfile'
    s.add_dependency 'spf-query'
    s.add_dependency 'fir-cli'
    s.add_dependency 'turbolinks_render'
    s.add_dependency 'rspec-protobuf'
    s.add_dependency 'win32-taskscheduler'
    s.add_dependency 'plutus'
    s.add_dependency 'pdf417'
    s.add_dependency 'caracal-rails'
    s.add_dependency 'finite_machine'
    s.add_dependency 'texplay'
    s.add_dependency 'forestadmin-jsonapi-serializers'
    s.add_dependency 'rails-flog'
    s.add_dependency 'dm-observer'
#    s.add_dependency 'scrivito_sdk'
    s.add_dependency 'alba'
#    s.add_dependency 'logstash-output-gelf'
    s.add_dependency 'danger-checkstyle_reports'
    s.add_dependency 'rescue_unique_constraint'
    s.add_dependency 'jamespath'
    s.add_dependency 's3_uploader'
    s.add_dependency 'http-parser-lite'
    s.add_dependency 'itriagetestrail'
    s.add_dependency 'ruby-freshbooks'
    s.add_dependency 'flatpickr_rails'
    s.add_dependency 'contentful-scheduler-custom'
    s.add_dependency 'active_scaffold_sortable'
    s.add_dependency 'knife-block'
    s.add_dependency 'komachi_heartbeat'
    s.add_dependency 'puppet-lint-duplicate_class_parameters-check'
    s.add_dependency 'phoney'
    s.add_dependency 'regex'
    s.add_dependency 'bashcov'
    s.add_dependency 'testlab'
    s.add_dependency 'presto-metrics'
    s.add_dependency 'active_flag'
    s.add_dependency 'api_cache'
    s.add_dependency 'watir-rspec'
    s.add_dependency 'fluent-plugin-reemit'
    s.add_dependency 'rubydoctest'
    s.add_dependency 'wunderbar'
    s.add_dependency 'access-granted'
    s.add_dependency 'blacklight-gallery'
    s.add_dependency 'tailor'
    s.add_dependency 'fluent-mixin-plaintextformatter'
    s.add_dependency 'interactor-contracts'
    s.add_dependency 'archive'
    s.add_dependency 'danger-simplecov_json'
    s.add_dependency 'big-phoney'
    s.add_dependency 'progressrus'
    s.add_dependency 'bones'
    s.add_dependency 'paperclip-azure'
    s.add_dependency 'shex'
    s.add_dependency 'puppet-lint-manifest_whitespace-check'
    s.add_dependency 'binary_struct'
    s.add_dependency 'sprockets-coffee-react'
    s.add_dependency 'analytical'
    s.add_dependency 'flipper-rails'
    s.add_dependency 'enum_attributes_validation'
    s.add_dependency 'waz-storage'
#    s.add_dependency 'isomer-jekyll'
#    s.add_dependency 'sinatra-r18n'
    s.add_dependency 'pry-highlight'
    s.add_dependency 'videojs_rails'
    s.add_dependency 'evernote-thrift'
    s.add_dependency 'knjrbfw'
    s.add_dependency 'emblem-source'
    s.add_dependency 'guard-process'
#    s.add_dependency 'arkaan'
    s.add_dependency 'simple_roles'
    s.add_dependency 'state_of_the_nation'
    s.add_dependency 'prawn-print'
    s.add_dependency 'cassandra'
    s.add_dependency 'free_disk_space'
    s.add_dependency 'encrypted_strings'
    s.add_dependency 'pager'
    s.add_dependency 'frank-cucumber'
    s.add_dependency 'net-http-spy'
#    s.add_dependency 'jwt_sessions'
    s.add_dependency 'google_timezone'
    s.add_dependency 'tsort'
#    s.add_dependency 'infoblox'
    s.add_dependency 'awestruct-ibeams'
    s.add_dependency 'rocksdb-ruby'
    s.add_dependency 'simple_hl7'
    s.add_dependency 'activerecord-mysql2spatial-adapter'
    s.add_dependency 'caldecott-client'
    s.add_dependency 'exif'
    s.add_dependency 'rack-fiber_pool'
    s.add_dependency 'procore-sift'
    s.add_dependency 'prowly'
    s.add_dependency 'soap2r'
    s.add_dependency 'ar_mailer'
    s.add_dependency 'request_id'
    s.add_dependency 'selenium-rc'
    s.add_dependency 'sixarm_ruby_secure_token'
    s.add_dependency 'iodine'
    s.add_dependency 'airtable'
#    s.add_dependency 'knife-spork'
    s.add_dependency 'rspec-bash'
    s.add_dependency 'global_uid'
    s.add_dependency 'rscribd'
    s.add_dependency 'thread_variables'
    s.add_dependency 'nfqueue'
    s.add_dependency 'rails-bigint-primarykey'
    s.add_dependency 'activerecord-analyze'
    s.add_dependency 'softcover'
    s.add_dependency 'action_kit_api'
    s.add_dependency 'da_funk'
    s.add_dependency 'noid'
    s.add_dependency 'vagrant-bindfs'
    s.add_dependency 'acts_as_reportable'
    s.add_dependency 'dbd-odbc'
    s.add_dependency 'gdbm'
    s.add_dependency 'stackable_flash'
    s.add_dependency 'tencentcloud-sdk-common'
    s.add_dependency 'minipack'
    s.add_dependency 'simplecov-rcov-text'
    s.add_dependency 'gem-path'
    s.add_dependency 'ifttt-gdash'
    s.add_dependency 'master_manipulator'
    s.add_dependency 'log_switch'
    s.add_dependency 'time_bandits'
    s.add_dependency 'spree_promo'
    s.add_dependency 'fast_inserter'
    s.add_dependency 'mina-puma'
    s.add_dependency 'normalizr'
    s.add_dependency 'sensu-plugins-java'
    s.add_dependency 'minitest-line'
    s.add_dependency 'roman-numerals'
#    s.add_dependency 'activerecord-mysql2rgeo-adapter'
    s.add_dependency 'rspec-twirp'
    s.add_dependency 'administrate-field-nested_has_many'
    s.add_dependency 'soda-ruby'
    s.add_dependency 'compass-960-plugin'

}
