
  require 'rubygems'

Gem::Specification.new {|s|
    s.name          = 'pkg10'
    s.version       = '0.0.1'
    s.author        = 'Julio Capote'
    s.email         = 'jcapote@gmail.com'
    s.homepage      = 'http://github.com/capotej/trollface'
    s.platform      = Gem::Platform::RUBY
    s.summary       = 'An empty gem that depends on every gem available'
    s.description   = s.summary
    s.add_dependency 'foundation_emails'
#    s.add_dependency 'logstash-output-cloudwatch'
    s.add_dependency 'xmldsig'
    s.add_dependency 'xdan-datetimepicker-rails'
    s.add_dependency 'wicked'
    s.add_dependency 'protobuf-cucumber'
    s.add_dependency 'ranked-model'
    s.add_dependency 'pmckee11-redis-lock'
#    s.add_dependency 'logstash-filter-ruby'
    s.add_dependency 'eventmachine-tail'
    s.add_dependency 'google-apis-drive_v3'
    s.add_dependency 'dumb_delegator'
    s.add_dependency 'opentelemetry-sdk'
#    s.add_dependency 'logstash-filter-elasticsearch'
    s.add_dependency 'xcov'
    s.add_dependency 'omniauth-alicloud'
    s.add_dependency 'pr_geohash'
#    s.add_dependency 'logstash-output-lumberjack'
    s.add_dependency 'capistrano-harrow'
    s.add_dependency 'subexec'
#    s.add_dependency 'ruby-xz'
#    s.add_dependency 'logstash-output-http'
    s.add_dependency 'opentelemetry-common'
#    s.add_dependency 'logstash-filter-kv'
#    s.add_dependency 'logstash-input-dead_letter_queue'
    s.add_dependency 'attr_extras'
    s.add_dependency 'danger-swiftlint'
    s.add_dependency 'RubyInline'
    s.add_dependency 'aws-sdk-keyspaces'
    s.add_dependency 'git_diff_parser'
    s.add_dependency 'ruby-xz'
    s.add_dependency 'ulid'
    s.add_dependency 'english'
    s.add_dependency 'keystore'
    s.add_dependency 'elasticsearch-persistence'
    s.add_dependency 'acts_as_paranoid'
    s.add_dependency 'shopify_api'
    s.add_dependency 'Platform'
    s.add_dependency 'jrjackson'
    s.add_dependency 'disposable'
    s.add_dependency 'quantile'
    s.add_dependency 'ruby-dbus'
    s.add_dependency 'dropzonejs-rails'
    s.add_dependency 'xmlmapper'
    s.add_dependency 'warden-jwt_auth'
#    s.add_dependency 'karafka'
    s.add_dependency 'aws-sdk-chimesdkmediapipelines'
#    s.add_dependency 'breadcrumbs_on_rails'
    s.add_dependency 'facterdb'
    s.add_dependency 'kt-paperclip'
    s.add_dependency 'minitest-focus'
#    s.add_dependency 'appraisal'
#    s.add_dependency 'logstash-output-tcp'
    s.add_dependency 'rubystats'
    s.add_dependency 'fastlane-plugin-badge'
    s.add_dependency 'easy_diff'
    s.add_dependency 'enum_help'
    s.add_dependency 'syntax'
    s.add_dependency 'gitlab-triage'
#    s.add_dependency 'logstash-input-file'
    s.add_dependency 'xlsxtream'
    s.add_dependency 'spoom'
    s.add_dependency 'allure-rspec'
    s.add_dependency 'google-cloud-pubsub-v1'
    s.add_dependency 'redis-client'
    s.add_dependency 'devise-jwt'
#    s.add_dependency 'logstash-input-azure_event_hubs'
    s.add_dependency 'file-tail'
    s.add_dependency 'rjb'
    s.add_dependency 'dragonfly'
    s.add_dependency 'fivemat'
    s.add_dependency 'wkhtmltopdf-binary-edge'
    s.add_dependency 'hubspot-ruby'
    s.add_dependency 'sensu-plugins-memory-checks'
    s.add_dependency 'jar-dependencies'
    s.add_dependency 'statuscake'
    s.add_dependency 'whois-parser'
    s.add_dependency 'syslogger'
    s.add_dependency 'lob'
    s.add_dependency 'capistrano-ext'
    s.add_dependency 'ruby_dig'
    s.add_dependency 'functions_framework'
    s.add_dependency 'unicode'
    s.add_dependency 'aws-ses'
    s.add_dependency 'json_api_client'
    s.add_dependency 'minima'
    s.add_dependency 'aws-sdk-billingconductor'
    s.add_dependency 'grease'
    s.add_dependency 'cloudflare-rails'
    s.add_dependency 'concurrent-ruby-edge'
    s.add_dependency 'reform'
    s.add_dependency 'versionist'
    s.add_dependency 'wisper-rspec'
#    s.add_dependency 'logstash-codec-cef'
    s.add_dependency 'rgen'
    s.add_dependency 'license-acceptance'
    s.add_dependency 'google-id-token'
    s.add_dependency 'fluent-plugin-detect-exceptions'
    s.add_dependency 'aes'
    s.add_dependency 'jekyll-redirect-from'
    s.add_dependency 'simplecov-console'
    s.add_dependency 'webpack-rails'
#    s.add_dependency 'logstash-filter-multiline'
#    s.add_dependency 'logstash-codec-plain'
#    s.add_dependency 'logstash-filter-dns'
    s.add_dependency 'angular-rails-templates'
    s.add_dependency 'rendezvous'
    s.add_dependency 'rspec-puppet-facts'
    s.add_dependency 'circuitbox'
    s.add_dependency 'pusher-fake'
    s.add_dependency 'metriks'
    s.add_dependency 'pubnub'
    s.add_dependency 'progressbar'
    s.add_dependency 'linux-kstat'
    s.add_dependency 'sslshake'
}
