
  require 'rubygems'

Gem::Specification.new {|s|
    s.name          = 'pkg34'
    s.version       = '0.0.1'
    s.author        = 'naresh'
    s.email         = 'nareshdevasani@gmail.com'
    s.homepage      = 'http://github.com/nareshdevasani'
    s.platform      = Gem::Platform::RUBY
    s.summary       = 'An empty gem that depends on every gem available'
    s.description   = s.summary

    s.add_dependency 'schema_plus_compatibility'
    s.add_dependency 'seamless_database_pool'
    s.add_dependency 'seo_meta'
    s.add_dependency 'jshint_on_rails'
    s.add_dependency 'guard-yard'
    s.add_dependency 'sensu-plugins-nginx'
    s.add_dependency 'liquid-c'
    s.add_dependency 'inch'
#    s.add_dependency 'logstash-output-loggly'
    s.add_dependency 'refinerycms-core'
    s.add_dependency 'http-exceptions'
    s.add_dependency 'user-choices'
    s.add_dependency 'guard-rack'
#    s.add_dependency 'logstash-output-kusto'
    s.add_dependency 'gs2crmod'
    s.add_dependency 'testcentricity_web'
    s.add_dependency 'jdbc-derby'
    s.add_dependency 'quality'
    s.add_dependency 'good'
    s.add_dependency 'mailslurp_client'
    s.add_dependency 'tether-rails'
    s.add_dependency 'clamav'
    s.add_dependency 'waterfall'
    s.add_dependency 'soundcloud'
    s.add_dependency 'rest-firebase'
    s.add_dependency 'dox'
    s.add_dependency 'sensu-extensions-ruby-hash'
    s.add_dependency 'mongoid_orderable'
    s.add_dependency 'fastlane-plugin-automated_test_emulator_run'
    s.add_dependency 'maven-tools'
    s.add_dependency 'usps'
    s.add_dependency 'rack-maintenance'
    s.add_dependency 'iron_mq'
    s.add_dependency 'infrataster'
    s.add_dependency 'fhir_client'
    s.add_dependency 'buttercms-ruby'
    s.add_dependency 'rack-accept-media-types'
    s.add_dependency 'posthog-ruby'
    s.add_dependency 'tzu'
    s.add_dependency 'carrierwave-video'
    s.add_dependency 'activeadmin-async_panel'
    s.add_dependency 'fluent-plugin-fields-parser'
    s.add_dependency 'irbtools'
    s.add_dependency 'cpee'
    s.add_dependency 'braze_ruby'
    s.add_dependency 'tsubaki'
    s.add_dependency 'incrdecr_cached_counts'
    s.add_dependency 'que-web'
    s.add_dependency 'upc'
    s.add_dependency 'pronto-haml'
    s.add_dependency 'chef-handler-updated-resources'
    s.add_dependency 'authorize-net'
    s.add_dependency 'capistrano_rsync_with_remote_cache'
    s.add_dependency 'promise_pool'
    s.add_dependency 'mailfactory'
    s.add_dependency 'jekyll-multiple-languages-plugin'
    s.add_dependency 'unscoped_associations'
    s.add_dependency 'sass-css-importer'
    s.add_dependency 'lazy_columns'
    s.add_dependency 'muck-engine'
#    s.add_dependency 'sensu-plugins-graphite'
    s.add_dependency 'hanami-mailer'
    s.add_dependency 'fluent-plugin-ping-message'
    s.add_dependency 'om'
    s.add_dependency 'gravatarify'
    s.add_dependency 'shippo'
    s.add_dependency 'capistrano-secrets-yml'
    s.add_dependency 'gstore'
    s.add_dependency 'win32screenshot'
    s.add_dependency 'refinerycms-pages'
    s.add_dependency 'haml_assets'
    s.add_dependency 'capistrano-git-with-submodules'
#    s.add_dependency 'app_profiler'
    s.add_dependency 'spice'
    s.add_dependency 'coderunner'
    s.add_dependency 'geocomplete_rails'
    s.add_dependency 'sendwithus_ruby_action_mailer'
    s.add_dependency 'dato'
    s.add_dependency 'fastri'
    s.add_dependency 'keccak'
    s.add_dependency 'click_house'
    s.add_dependency 'feedzirra'
    s.add_dependency 'load_data_infile2'
    s.add_dependency 'google-cloud-tasks-v2'
    s.add_dependency 'zold'
    s.add_dependency 'http-dump'
    s.add_dependency 'parseline'
    s.add_dependency 'neo4j-rake_tasks'
    s.add_dependency 'grape-order'
    s.add_dependency 'active_admin_sidebar'
    s.add_dependency 'deb-s3'
    s.add_dependency 'isodoc'
#    s.add_dependency 'jekyll-sanity'
    s.add_dependency 'valcro'
    s.add_dependency 'sass-json-vars'
    s.add_dependency 'active_operation'
    s.add_dependency 'zinbei'
#    s.add_dependency 'logstash-output-riemann'
    s.add_dependency 'bootstrap-tagsinput-rails'
    s.add_dependency 'capistrano3-nginx'
    s.add_dependency 'grape-cancan'
    s.add_dependency 'gda'
    s.add_dependency 'refinerycms-images'
    s.add_dependency 'gcloud'
    s.add_dependency 'api-ai-ruby'
    s.add_dependency 'disqus_api'
    s.add_dependency 's4t-utils'
    s.add_dependency 'colorls'
    s.add_dependency 'refinerycms-resources'
#    s.add_dependency 'google-cloud-tasks-v2beta3'
    s.add_dependency 'brdinheiro'
    s.add_dependency 'qunit-selenium'
    s.add_dependency 'falcon'
    s.add_dependency 'apipie-bindings'
    s.add_dependency 'cli-kit'
    s.add_dependency 'certificate_authority'
    s.add_dependency 'tzu_mock'
    s.add_dependency 'embulk-input-postgresql'
    s.add_dependency 'oa-basic'
    s.add_dependency 'ezapi'
    s.add_dependency 'awesome_spawn'
    s.add_dependency 'show_for'
    s.add_dependency 'rest-builder'
    s.add_dependency 'mini_fb'
    s.add_dependency 'google-cloud-tasks-v2beta2'
    s.add_dependency 'wrong'
    s.add_dependency 'yabeda-http_requests'
    s.add_dependency 'promethee'
    s.add_dependency 'revision_plate'
    s.add_dependency 'will-paginate-i18n'
    s.add_dependency 'semver_dialects'
    s.add_dependency 'multipart_body'
#    s.add_dependency 'oa-enterprise'
    s.add_dependency 'refinerycms-i18n'
    s.add_dependency 'fluent-plugin-json-transform'
    s.add_dependency 'bootstrap-x-editable-rails'
    s.add_dependency 'dalli-rate_limiter'
    s.add_dependency 'earth'
    s.add_dependency 'griddler-mandrill'
    s.add_dependency 'dor-services'
#    s.add_dependency 'flip'
    s.add_dependency 'wongi-engine'
    s.add_dependency 'rake_shared_context'
#    s.add_dependency 'geokit-rails3'
    s.add_dependency 'actionpack-cloudfront'
    s.add_dependency 'rack-respond_to'
    s.add_dependency 'avatarly'
    s.add_dependency 'vnctools'
    s.add_dependency 'solid_assert'
    s.add_dependency 'closeio'
    s.add_dependency 'health_bit'
    s.add_dependency 'rspec-openapi'
    s.add_dependency 'flydata'
    s.add_dependency 'girl'
    s.add_dependency 'recurring_select'
    s.add_dependency 'megam_api'
    s.add_dependency 'mutex_m'
    s.add_dependency 'rack-p3p'
    s.add_dependency 'shikashi'
    s.add_dependency 'middleman-gh-pages'
    s.add_dependency 'active_admin-sortable_tree'
    s.add_dependency 'omniauth-microsoft_graph'
    s.add_dependency 'granite'
    s.add_dependency 'http-2-next'
    s.add_dependency 'apollo-tracing'
    s.add_dependency 'resque-backtrace'
    s.add_dependency 'vimeo'
    s.add_dependency 'weighted_randomizer'
    s.add_dependency 'markdown-rails'
#    s.add_dependency 'chef-handler-sns'
    s.add_dependency 'honeypot-captcha'
    s.add_dependency 'rack-google-analytics'
    s.add_dependency 'sensu-extensions-occurrences'
#    s.add_dependency 'jquery-scrollto-rails'
#    s.add_dependency 'schema_plus_views'
#    s.add_dependency 'capistrano_multiconfig_parallel'
    s.add_dependency 'futuroscope'
    s.add_dependency 'pickadate-rails'
    s.add_dependency 'useragents'
    s.add_dependency 'reportportal'
    s.add_dependency 'vagrant-proxyconf'
#    s.add_dependency 'minitest-test'
#    s.add_dependency 'chef-provisioning'
#    s.add_dependency 'danger-changelog'
    s.add_dependency 'fastlane-plugin-aws_device_farm'
    s.add_dependency 'lokalise_rails'
    s.add_dependency 'gitlab_emoji'
    s.add_dependency 'receipts'
    s.add_dependency 'sprockets-derailleur'
    s.add_dependency 'activerecord-be_readonly'
    s.add_dependency 'code_ownership'
    s.add_dependency 'gutentag'
    s.add_dependency 'stub_server'
    s.add_dependency 'rfc-822'
    s.add_dependency 'maxitest'
    s.add_dependency 'paypal_adaptive'
    s.add_dependency 'spider'
    s.add_dependency 'stove'
#    s.add_dependency 'logstash-output-exec'
#    s.add_dependency 'shenzhen'
    s.add_dependency 'tty-file'
    s.add_dependency 'conjur-cli'
    s.add_dependency 'sinatra-router'
    s.add_dependency 'vagrant-berkshelf'
    s.add_dependency 'files.com'
    s.add_dependency 'sensu-plugins-postfix'
    s.add_dependency 'order_query'
    s.add_dependency 'sensu-extensions-only-check-output'
    s.add_dependency 'dynect4r'
#    s.add_dependency 'daddy'
    s.add_dependency 'demoji'
    s.add_dependency 'tumblr_client'
    s.add_dependency 'sensu-extensions-json'
    s.add_dependency 'redisk'
    s.add_dependency 'sensu-extensions-debug'
    s.add_dependency 'autotest-standalone'
    s.add_dependency 'net-dhcp'
    s.add_dependency 'pwwka'
    s.add_dependency 'ibsciss-middleware'
    s.add_dependency 'factory_trace'
#    s.add_dependency 'desk'
    s.add_dependency 'appstats'
    s.add_dependency 'redis_locks'
    s.add_dependency 'devise_cas_authenticatable'
    s.add_dependency 'sensu-extensions-check-dependencies'
    s.add_dependency 'partialruby'
    s.add_dependency 'rdf-tabular'
    s.add_dependency 'photoswipe-rails'
    s.add_dependency 'awful'
    s.add_dependency 'ezcater_rubocop'
#    s.add_dependency 'middleman-compass'
    s.add_dependency 'handcuffs'
    s.add_dependency 'amazon_pay'
    s.add_dependency 'getsource'
    s.add_dependency 'sportradar-api'
    s.add_dependency 'jquery-colorbox-rails'
    s.add_dependency 'pagseguro-oficial'
    s.add_dependency 'sinatra-support'
    s.add_dependency 'chrome_remote'
    s.add_dependency 'sidekiq-benchmark'
    s.add_dependency 'wkhtmltopdf'
#    s.add_dependency 'ish_manager'
    s.add_dependency 'brhelper'
    s.add_dependency 'magic_encoding'
    s.add_dependency 'barista'
    s.add_dependency 'sem_version'
    s.add_dependency 'ginjo-omniauth-slack'
    s.add_dependency 'rack-brotli'
    s.add_dependency 'packet'
#    s.add_dependency 'carrierwave-google-storage'
}
