
  require 'rubygems'

Gem::Specification.new {|s|
    s.name          = 'pkg41'
    s.version       = '0.0.1'
    s.author        = 'Naresh Devasani'
    s.email         = 'naresh@endor.ai'
    s.homepage      = 'http://github.com/capotej/trollface'
    s.platform      = Gem::Platform::RUBY
    s.summary       = 'An empty gem that depends on every gem available'
    s.description   = s.summary

    s.add_dependency 'cocoapods-user-defined-build-types'
    s.add_dependency 'deep_pluck'
    s.add_dependency 'commands'
    s.add_dependency 'fluent-plugin-dd'
    s.add_dependency 'FakeWeb'
    s.add_dependency 'rack-jekyll'
    s.add_dependency 'capng_c'
    s.add_dependency 'elastic_whenever'
    s.add_dependency 'taglib-ruby'
    s.add_dependency 'six-rsync'
    s.add_dependency 'shorturl'
    s.add_dependency 'cmxl'
    s.add_dependency 'layer-ruby'
    s.add_dependency 'encryptor2'
    s.add_dependency 'capistrano-upload'
    s.add_dependency 'pry-twitter'
    s.add_dependency 'acts_as_fu'
    s.add_dependency 'rabbit_jobs'
#    s.add_dependency 'digest-sha3-patched'
    s.add_dependency 'imgproxy'
    s.add_dependency 'modalibrary'
    s.add_dependency 'stator'
    s.add_dependency 'apotomo'
#    s.add_dependency 'renalware-core'
    s.add_dependency 'killbill-client'
    s.add_dependency 'centurion'
    s.add_dependency 'rename'
    s.add_dependency 'rack-client'
    s.add_dependency 'umbrellio-sequel-plugins'
    s.add_dependency 'jquery.fileupload-rails'
    s.add_dependency 'fluent_command_builder'
    s.add_dependency 'public_uid'
    s.add_dependency 'gnip-rule'
    s.add_dependency 'active_record_encryption'
    s.add_dependency 'piggybak'
    s.add_dependency '3scale_client'
    s.add_dependency 'fastlane-plugin-google_drive'
    s.add_dependency 'emoji'
    s.add_dependency 'cobra_commander'
    s.add_dependency 'activerecord-clean-db-structure'
    s.add_dependency 'tee'
    s.add_dependency 'win32-mutex'
    s.add_dependency 'grid_table'
#    s.add_dependency 'fanforce-app-factory'
    s.add_dependency 'build-environment'
    s.add_dependency 'rspec-fire'
    s.add_dependency 'rubocop-betterment'
    s.add_dependency 'dpl-surge'
    s.add_dependency 'rfauxfactory'
    s.add_dependency 'linkedin-v2'
    s.add_dependency 'pairing_heap'
    s.add_dependency 'sym'
    s.add_dependency 'railslts-version'
    s.add_dependency 'hcl_parser'
    s.add_dependency 'pivot_table'
    s.add_dependency 'pay_with_amazon'
    s.add_dependency 'coder'
#    s.add_dependency 'mongoid-encrypted'
#    s.add_dependency 'cypress-rails'
    s.add_dependency 'second_level_cache'
    s.add_dependency 'reel'
    s.add_dependency 'smusher'
    s.add_dependency 'ruby_engine'
    s.add_dependency 'jquery-timepicker-addon-rails'
    s.add_dependency 'occams-record'
    s.add_dependency 'rspec-terraspace'
#    s.add_dependency 'sneakers_packer'
    s.add_dependency 'bookyt_salary'
    s.add_dependency 'sequel-batches'
    s.add_dependency 'logutils'
#    s.add_dependency 'rest-assured'
    s.add_dependency 'merb-assets'
    s.add_dependency 'rspec-autotest'
    s.add_dependency 'record_with_operator'
    s.add_dependency 'sinatra_more'
    s.add_dependency 'ruby-termios'
    s.add_dependency 'paperclip-aws'
    s.add_dependency 'selenium-devtools'
    s.add_dependency 'libshadow'
    s.add_dependency 'omniauth-qq-connect'
    s.add_dependency 'css-class-string'
    s.add_dependency 'jekyll-contentblocks'
    s.add_dependency 'rkelly'
    s.add_dependency 'activeadmin-ajax_filter'
#    s.add_dependency 'anvil-cli'
    s.add_dependency 'update'
#    s.add_dependency 'glimmer-dsl-swt'
    s.add_dependency 'kiji'
    s.add_dependency 'rspec-testrail'
    s.add_dependency 'rodauth'
    s.add_dependency 'basicjrpc'
    s.add_dependency 'bb-ruby'
    s.add_dependency 'remarkable_activerecord'
    s.add_dependency 'codeclimate_circle_ci_coverage'
    s.add_dependency 'rubysl-base64'
#    s.add_dependency 'google-cloud-kms-v1'
    s.add_dependency 'rack-iframe'
    s.add_dependency 'bumbleworks'
    s.add_dependency 'caze'
    s.add_dependency 'ruby_flipper'
    s.add_dependency 'copy_tuner_client'
    s.add_dependency 'wepay'
    s.add_dependency 'apollo-crawler'
    s.add_dependency 'delayed_job_heartbeat_plugin'
#    s.add_dependency 'chef-dk'
    s.add_dependency 'qiita-markdown'
    s.add_dependency 'qbxml'
    s.add_dependency 'mini_suffix'
    s.add_dependency 'sql-logging'
    s.add_dependency 'google-tag-manager-rails'
    s.add_dependency 'rubyfish'
    s.add_dependency 'rox-rollout'
    s.add_dependency 'the_sortable_tree'
    s.add_dependency 'minitest-distributed'
    s.add_dependency 'relaton-gb'
    s.add_dependency 'fukuzatsu'
    s.add_dependency 'message_block'
    s.add_dependency 'sham'
    s.add_dependency 'faktory_worker_ruby'
    s.add_dependency 'mdb'
    s.add_dependency 'druuid'
    s.add_dependency 'urlcrypt'
    s.add_dependency 'ende'
    s.add_dependency 'rakuten_web_service'
    s.add_dependency 'opendelivery'
    s.add_dependency 'eyes_images'
    s.add_dependency 'graphql-pagination'
    s.add_dependency 'sidekiq-skylight'
    s.add_dependency 'wayback_machine_downloader'
    s.add_dependency 'rumbster'
    s.add_dependency 'carrierwave-magic'
#    s.add_dependency 'introjs-rails'
    s.add_dependency 'http_accept'
    s.add_dependency 'soywiki'
    s.add_dependency 'exvo-auth'
    s.add_dependency 'boolean'
    s.add_dependency 'debugging'
    s.add_dependency 'validation_profiler'
    s.add_dependency 'google-cloud-recaptcha_enterprise-v1'
    s.add_dependency 'getopt'
    s.add_dependency 'TimezoneParser'
    s.add_dependency 'planout'
    s.add_dependency 'avm-tools'
    s.add_dependency 'embulk-output-td'
    s.add_dependency 'db_schema_checker'
    s.add_dependency 'knife-art'
    s.add_dependency 'discourse-fonts'
    s.add_dependency 'rack-unreloader'
    s.add_dependency 'heroic-sns'
    s.add_dependency 'miro'
    s.add_dependency 'punchblock'
    s.add_dependency 'carrierwave-ftp'
    s.add_dependency 'we-call'
    s.add_dependency 'sensu-plugins-cassandra'
    s.add_dependency 'zendesk2'
#    s.add_dependency 'bankserv'
#    s.add_dependency 'smashing'
    s.add_dependency 'thumbs_up'
    s.add_dependency 'zerobounce'
    s.add_dependency 'rack-active_record_status'
    s.add_dependency 'fanforce'
    s.add_dependency 'capper'
    s.add_dependency 'mailgunner'
    s.add_dependency 'bootstrap_forms'
    s.add_dependency 'sensible-cinema'
    s.add_dependency 'eventq_aws'
    s.add_dependency 'washout_builder'
    s.add_dependency 'redcar'
    s.add_dependency 'uber_config'
    s.add_dependency 'color-schemer'
#    s.add_dependency 'voxpupuli-acceptance'
#    s.add_dependency 'ruby_rabbitmq_janus'
#    s.add_dependency 'gitlab-linguist'
    s.add_dependency 'perfectqueue'
    s.add_dependency 'evil-winrm'
    s.add_dependency 'victor'
    s.add_dependency 'telegram-bot'
    s.add_dependency 'mongoid-scroll'
    s.add_dependency 'capistrano-upload-config'
    s.add_dependency 'puma-cloudwatch'
#    s.add_dependency 'ishapi'
    s.add_dependency 'appmake'
    s.add_dependency 'hosted_graphite'
    s.add_dependency 'sql-maker'
    s.add_dependency 'openid-redis-store'
    s.add_dependency 'vandamme'
    s.add_dependency 'pullreview-coverage'
    s.add_dependency 'surrealist'
    s.add_dependency 'consent'
    s.add_dependency 'rails-env-credentials'
    s.add_dependency 'shareable'
    s.add_dependency 'earlgrey'
    s.add_dependency 'omniauth-douban-oauth2'
    s.add_dependency 'mirage'
    s.add_dependency 'ampex'
    s.add_dependency 'fog-azure'
    s.add_dependency 'katex'
#    s.add_dependency 'yaml-safe_load_stream'
    s.add_dependency 'sensu-plugins-entropy-checks'
    s.add_dependency 'rack-accept-default'
    s.add_dependency 'prius'
    s.add_dependency 'simplecov-teamcity-summary'
    s.add_dependency 'community_cookbook_releaser'
    s.add_dependency 'delayed_job_worker_pool'
    s.add_dependency 'activerecord_null_object'
#    s.add_dependency 'studium'
    s.add_dependency 'MovableInkAWS'
    s.add_dependency 'json2table'
    s.add_dependency 'govuk_template'
    s.add_dependency 'magento_client'
    s.add_dependency 'linode'
    s.add_dependency 'bootsy'
    s.add_dependency 'rest-ftp-daemon'
    s.add_dependency 'qtbindings'
    s.add_dependency 'ios-devices'
    s.add_dependency 'stackup'
    s.add_dependency 'vanilla-ujs'
    s.add_dependency 'neighbor'
    s.add_dependency 'aws_lambda_ric'
    s.add_dependency 'acts_as_ferret'
    s.add_dependency 'linkscape'
    s.add_dependency 'bootstrap-navbar'
    s.add_dependency 'bibliothecary'
    s.add_dependency 'tabulo'
    s.add_dependency 'fastlane-plugin-unzip'
    s.add_dependency 'mongoid-embedded-errors'
    s.add_dependency 'dry-config'
    s.add_dependency 'ember-cli-assets'
    s.add_dependency 'dry-rails'
    s.add_dependency 'color_diff'
    s.add_dependency 'omniauth-lightspeed'
    s.add_dependency 'fastlane-plugin-google_cloud_storage'
    s.add_dependency 'ocra'
    s.add_dependency 'jekyll-attendease'
    s.add_dependency 'omniauth-intercom'
    s.add_dependency 'sql_query'
    s.add_dependency 'tty-config'
    s.add_dependency 'baja'
    s.add_dependency 'rack-zippy'
    s.add_dependency 'czmq-ffi-gen'
    s.add_dependency 'fastlane-plugin-tpa'
    s.add_dependency 'petrovich'
    s.add_dependency 'clogger'
    s.add_dependency 'material_raingular'
    s.add_dependency 'activejob_backport'
#    s.add_dependency 'awetestlib'
    s.add_dependency 'tty-logger'
#    s.add_dependency 'apiotics'
    s.add_dependency 'onering-report-plugins'
    s.add_dependency 'judge'
}
