  require 'rubygems'

Gem::Specification.new {|s|
    s.name          = 'pkg19'
    s.version       = '0.0.1'
    s.author        = 'Julio Capote'
    s.email         = 'jcapote@gmail.com'
    s.homepage      = 'http://github.com/capotej/trollface'
    s.platform      = Gem::Platform::RUBY
    s.summary       = 'An empty gem that depends on every gem available'
    s.description   = s.summary

    s.add_dependency 'fnv'
    s.add_dependency 'quickbooks-ruby'
#    s.add_dependency 'logstash-integration-kafka'
    s.add_dependency 'circleci-parallel'
    s.add_dependency 'meta_search'
    s.add_dependency 'jekyll-commonmark'
#    s.add_dependency 'civilize-number'
    s.add_dependency 'rails_config'
    s.add_dependency 'simplecov-parallel'
    s.add_dependency 'gollum-lib'
    s.add_dependency 'metasploit-credential'
    s.add_dependency 'multi_exiftool'
    s.add_dependency 'opentelemetry-instrumentation-sinatra'
    s.add_dependency 'heroku-deflater'
    s.add_dependency 'dropbox_api'
    s.add_dependency 'aws-sdk-resourceexplorer2'
    s.add_dependency 'sidekiq-superworker'
#    s.add_dependency 'google-cloud-firestore'
    s.add_dependency 'valvat'
    s.add_dependency 'm'
    s.add_dependency 'ruby_event_store-rspec'
    s.add_dependency 'azure_mgmt_network'
    s.add_dependency 'shared-mime-info'
    s.add_dependency 'nexpose'
    s.add_dependency 'rex-core'
    s.add_dependency 'librato-rack'
    s.add_dependency 'honeycomb-beeline'
    s.add_dependency 'loofah-activerecord'
    s.add_dependency 'fluent-plugin-parser-cri'
    s.add_dependency 'lograge-sql'
    s.add_dependency 'ruby-debug'
    s.add_dependency 'rcov'
    s.add_dependency 'azure'
#    s.add_dependency 'logstash-input-jms'
    s.add_dependency 'rubocop-changes'
    s.add_dependency 'jdbc-mysql'
    s.add_dependency 'mcollective-client'
    s.add_dependency 'rufus-lru'
    s.add_dependency 'td-client'
    s.add_dependency 'jquery-slick-rails'
    s.add_dependency 'therubyrhino'
    s.add_dependency 'librato-rails'
    s.add_dependency 'sinatra-cross_origin'
    s.add_dependency 'gist'
    s.add_dependency 'activerecord-compatible_legacy_migration'
    s.add_dependency 'ahoy_email'
    s.add_dependency 'filewatch'
#    s.add_dependency 'logstash-codec-protobuf'
    s.add_dependency 'createsend'
    s.add_dependency 'slim_lint'
    s.add_dependency 'committee-rails'
    s.add_dependency 'aws-sdk-sts'
    s.add_dependency 'delorean'
    s.add_dependency 'lockfile'
    s.add_dependency 'bot_framework'
    s.add_dependency 'sidetiq'
    s.add_dependency 'aws-sdk-scheduler'
    s.add_dependency 'deepsort'
    s.add_dependency 'pluck_to_hash'
    s.add_dependency 'rex-powershell'
    s.add_dependency 'chef-telemetry'
    s.add_dependency 'phashion'
    s.add_dependency 'metasploit-model'
    s.add_dependency 'nprogress-rails'
    s.add_dependency 'rack-dev-mark'
    s.add_dependency 'validates_overlap'
    s.add_dependency 'puppet-lint-trailing_comma-check'
    s.add_dependency 'codemirror-rails'
    s.add_dependency 'google-cloud-trace-v1'
    s.add_dependency 'docker_registry2'
    s.add_dependency 'strongbox'
    s.add_dependency 'arproxy'
    s.add_dependency 'prawn-icon'
    s.add_dependency 'dry-cli'
    s.add_dependency 'rspec-parameterized-core'
    s.add_dependency 'http_connection'
    s.add_dependency 'requirejs-rails'
    s.add_dependency 'fauxhai'
    s.add_dependency 'paypal-sdk-merchant'
    s.add_dependency 'rspec-parameterized-table_syntax'
    s.add_dependency 'money-open-exchange-rates'
    s.add_dependency 'fluent-plugin-grafana-loki-licence-fix'
    s.add_dependency 'opentelemetry-instrumentation-active_model_serializers'
    s.add_dependency 'jsonapi-rb'
#    s.add_dependency 'caboose-cms'
    s.add_dependency 'jazzy'
    s.add_dependency 'rails_autoscale_agent'
    s.add_dependency 'instagram'
    s.add_dependency 'opentelemetry-instrumentation-aws_sdk'
    s.add_dependency 'beaker-answers'
    s.add_dependency 'activeadmin_json_editor'
    s.add_dependency 'metasploit-concern'
    s.add_dependency 'application_insights'
#    s.add_dependency 'kitchen-inspec'
    s.add_dependency 'opencensus'
    s.add_dependency 'faraday_middleware-parse_oj'
    s.add_dependency 'opentelemetry-instrumentation-mongo'
    s.add_dependency 'pronto-brakeman'
    s.add_dependency 'jquery-minicolors-rails'
    s.add_dependency 'aws-sdk-chimesdkvoice'
    s.add_dependency 'aws-sdk-ssmsap'
    s.add_dependency 'lefthook'
    s.add_dependency 'null-logger'
    s.add_dependency 'gruf'
#=begin 
    s.add_dependency 'pronto-reek'
    s.add_dependency 'gcm'
    s.add_dependency 'opentelemetry-instrumentation-excon'
    s.add_dependency 'resque-web'
    s.add_dependency 'jsonapi-deserializable'
    s.add_dependency 'html_to_plain_text'
    s.add_dependency 'opentelemetry-instrumentation-bunny'
    s.add_dependency 'sensu-plugins-sensu'
#    s.add_dependency 'dependabot-terraform'
#    s.add_dependency 'audited-activerecord'
    s.add_dependency 'in-parallel'
    s.add_dependency 'xdr'
    s.add_dependency 'net_http_unix'
    s.add_dependency 'ronn'
    s.add_dependency 'puppet-lint-variable_contains_upcase'
    s.add_dependency 'active_shipping'
#    s.add_dependency 'dependabot-omnibus'
    s.add_dependency 'escape_code'
    s.add_dependency 'rex-exploitation'
    s.add_dependency 'yarjuf'
    s.add_dependency 'unix-crypt'
#    s.add_dependency 'dependabot-docker'
    s.add_dependency 'sysvmq'
    s.add_dependency 'fast_stack'
    s.add_dependency 'healthy_rack'
    s.add_dependency 'zipruby'
    s.add_dependency 'active_type'
    s.add_dependency 'sham_rack'
    s.add_dependency 'gruff'
    s.add_dependency 'smtpapi'
    s.add_dependency 'therubyrhino_jar'
    s.add_dependency 'dm-validations'
    s.add_dependency 'sidekiq_alive'
    s.add_dependency 'combustion'
#    s.add_dependency 'dependabot-python'
    s.add_dependency 'mousetrap-rails'
#    s.add_dependency 'dependabot-git_submodules'
    s.add_dependency 'jsonb_accessor'
    s.add_dependency 'OptionParser'
#    s.add_dependency 'dependabot-nuget'
#    s.add_dependency 'dependabot-cargo'
    s.add_dependency 'discordrb'
    s.add_dependency 'rgeo-shapefile'
    s.add_dependency 'tool'
    s.add_dependency 'teaspoon-mocha'
#    s.add_dependency 'dependabot-elm'
    s.add_dependency 'closure-compiler'
    s.add_dependency 'statistics2'
    s.add_dependency 'blue-daemons'
    s.add_dependency 'numo-narray'
    s.add_dependency 'couchrest'
#    s.add_dependency 'dependabot-gradle'
    s.add_dependency 'onebox'
    s.add_dependency 'grit'
    s.add_dependency 'scanf'
    s.add_dependency 'zeroclipboard-rails'
    s.add_dependency 'axlsx_styler'
    s.add_dependency 'vagrant-vbguest'
    s.add_dependency 'micromachine'
#    s.add_dependency 'dependabot-maven'
    s.add_dependency 'aws-sdk-iotroborunner'
    s.add_dependency 'pluginator'
    s.add_dependency 'postgresql_cursor'
    s.add_dependency 'rails-reverse-proxy'
    s.add_dependency 'syck'
    s.add_dependency 'resque-sentry'
    s.add_dependency 'trailblazer'
    s.add_dependency 'opentelemetry-instrumentation-all'
    s.add_dependency 'fantaskspec'
    s.add_dependency 'gollum-grit_adapter'
    s.add_dependency 'glib2'
    s.add_dependency 'activerecord-postgres_enum'
    s.add_dependency 'rack-reverse-proxy'
    s.add_dependency 'licensed'
    s.add_dependency 'omniauth-shopify-oauth2'
    s.add_dependency 'devise_security_extension'
    s.add_dependency 'droplet_kit'
#    s.add_dependency 'middleman-autoprefixer'
    s.add_dependency 'fluent-mixin-config-placeholders'
    s.add_dependency 'POpen4'
    s.add_dependency 'dm-serializer'
    s.add_dependency 'opentelemetry-instrumentation-koala'
    s.add_dependency 'dm-aggregates'
    s.add_dependency 'opentelemetry-instrumentation-lmdb'
    s.add_dependency 'metainspector'
    s.add_dependency 'resource_kit'
    s.add_dependency 'ratelimit'
    s.add_dependency 'gitlab-pg_query'
    s.add_dependency 'capistrano-composer'
    s.add_dependency 'clavius'
    s.add_dependency 'dm-timestamps'
    s.add_dependency 'windows-pr'
    s.add_dependency 'jruby-jms'
    s.add_dependency 'opus-ruby'
    s.add_dependency 'immigrant'
#    s.add_dependency 'dependabot-go_modules'
}
