
  require 'rubygems'

Gem::Specification.new {|s|
    s.name          = 'pkg30'
    s.version       = '0.0.1'
    s.author        = 'naresh'
    s.email         = 'nareshdevasani@gmail.com'
    s.homepage      = 'http://github.com/nareshdevasani'
    s.platform      = Gem::Platform::RUBY
    s.summary       = 'An empty gem that depends on every gem available'
    s.description   = s.summary

    s.add_dependency 'mailman'
    s.add_dependency 'call-me'
    s.add_dependency 'wavefile'
    s.add_dependency 'rollbar_helper'
    s.add_dependency 'luhn'
    s.add_dependency 'guard-teaspoon'
    s.add_dependency 'trix'
    s.add_dependency 'ruby-saml-idp'
    s.add_dependency 'apns'
    s.add_dependency 'sidekiq-rate-limiter'
    s.add_dependency 'xml-fu'
    s.add_dependency 'dataloader'
    s.add_dependency 'membrane'
    s.add_dependency 'nokogiri-pretty'
    s.add_dependency 'dedup'
    s.add_dependency 'activerecord-native_db_types_override'
    s.add_dependency 'shell'
    s.add_dependency 'ripl-rack'
    s.add_dependency 'asciimath'
    s.add_dependency 'spice-html5-rails'
    s.add_dependency 'jsonseq'
    s.add_dependency 'ffi-extra'
    s.add_dependency 'agent_orange'
    s.add_dependency 'cloudflair'
    s.add_dependency 'lingua'
    s.add_dependency 'rdf-aggregate-repo'
    s.add_dependency 'pronto-rails_schema'
    s.add_dependency 'ffi-inline'
    s.add_dependency 'bundler-inject'
    s.add_dependency 'chef_handler_foreman'
    s.add_dependency 'statsample'
    s.add_dependency 'it'
    s.add_dependency 'testrailtagging'
    s.add_dependency 'saxerator'
    s.add_dependency 'dwolla_v2'
    s.add_dependency 'hub'
    s.add_dependency 'opt_parse_validator'
    s.add_dependency 'ya_kansuji'
    s.add_dependency 'sha3'
    s.add_dependency 'awestruct'
    s.add_dependency 'sparkr'
    s.add_dependency 'riemann-tools'
    s.add_dependency 'activeldap'
    s.add_dependency 'rdf-normalize'
    s.add_dependency 'activerecord-pedantmysql2-adapter'
    s.add_dependency 'extendmatrix'
    s.add_dependency 'queue-bus'
    s.add_dependency 'akamai-edgegrid'
    s.add_dependency 'rake_terraform'
    s.add_dependency 'vero'
    s.add_dependency 'morrisjs-rails'
    s.add_dependency 'server_metrics'
    s.add_dependency 'sensu-plugins-vmstats'
    s.add_dependency 'nuggets'
    s.add_dependency 'tag_helper'
    s.add_dependency 'safe_target_blank'
    s.add_dependency 'travis-lint'
    s.add_dependency 'reportbuilder'
    s.add_dependency 'puppeteer-ruby'
    s.add_dependency 'openapi3_parser'
    s.add_dependency 'tesseract-ocr'
    s.add_dependency 'mmap2'
    s.add_dependency 'transpec'
    s.add_dependency 'beaker-aws'
    s.add_dependency 'prawn-emoji'
    s.add_dependency 'dawnscanner'
    s.add_dependency 'jquery-ui-sass-rails'
    s.add_dependency 'rb_heap'
    s.add_dependency 'rspec_sequel_matchers'
    s.add_dependency 'couchbase'
    s.add_dependency 'fluent-plugin-vmware-log-intelligence'
    s.add_dependency 'canvas_webex'
    s.add_dependency 'hanami-controller'
    s.add_dependency 'vmfloaty'
    s.add_dependency 'acts_as_archival'
    s.add_dependency 'sensu-plugins-uptime-checks'
    s.add_dependency 'fustigit'
    s.add_dependency 'cb-api'
    s.add_dependency 'sensu-redis'
    s.add_dependency 'unobtainium'
    s.add_dependency 'minimization'
    s.add_dependency 'logidze'
    s.add_dependency 'i18n-spec'
    s.add_dependency 'omniauth-bitbucket'
    s.add_dependency 'sinon-rails'
    s.add_dependency 'appium_console'
    s.add_dependency 'crypt'
    s.add_dependency 'cql-rb'
    s.add_dependency 'rails_multisite'
    s.add_dependency 'unique_by'
#    s.add_dependency 'sensu-plugins-aws'
    s.add_dependency 'fake_stripe'
    s.add_dependency 'fastlane-plugin-brew'
    s.add_dependency 'sparql'
    s.add_dependency 'redis-queue'
#    s.add_dependency 'fluent-plugin-azurestorage-gen2'
    s.add_dependency 'red-arrow'
    s.add_dependency 'splunk-sdk-ruby'
    s.add_dependency 'exceptional'
    s.add_dependency 'contentful_model'
    s.add_dependency 'circuitry'
    s.add_dependency 'health-monitor-rails'
    s.add_dependency 'validatable'
    s.add_dependency 'active_model-better_errors'
    s.add_dependency 'cssmin'
    s.add_dependency 'faraday-digestauth'
    s.add_dependency 'rebase_attr'
    s.add_dependency 'nats'
    s.add_dependency 'rack-flash3'
    s.add_dependency 'marc'
    s.add_dependency 'sensu-extension'
    s.add_dependency 'rails_apps_composer'
    s.add_dependency 'rchardet19'
    s.add_dependency 'ruby-audio'
    s.add_dependency 'schema_plus_columns'
    s.add_dependency 'urss'
    s.add_dependency 'soap4r-middleware'
    s.add_dependency 'handsoap'
    s.add_dependency 'activevalidators'
    s.add_dependency 'promise'
#    s.add_dependency 'chefstyle'
    s.add_dependency 'json5'
    s.add_dependency 'benchmark_driver'
    s.add_dependency 'searchlogic'
    s.add_dependency 'schash'
    s.add_dependency 'rainbows'
#    s.add_dependency 'logstash-output-kinesis'
    s.add_dependency 'otr-activerecord'
    s.add_dependency 'googl'
#    s.add_dependency 'middleman-s3_sync'
    s.add_dependency 'rdf-isomorphic'
    s.add_dependency 'fig_newton'
#    s.add_dependency 'jenkins_pipeline_builder'
    s.add_dependency 'mini_cache'
    s.add_dependency 'cloudwatchlogger'
#    s.add_dependency 'rspec-any_of'
    s.add_dependency 'ritex'
    s.add_dependency 'rabbitmq_http_api_client'
    s.add_dependency 'backport_new_renderer'
#    s.add_dependency 'bolognese'
    s.add_dependency 'money-currencylayer-bank'
    s.add_dependency 'cocoapods-binary'
    s.add_dependency 'by_star'
    s.add_dependency 'swagger-ui_rails'
    s.add_dependency 'generator'
    s.add_dependency 'browsernizer'
    s.add_dependency 'oa-oauth'
    s.add_dependency 'ruby-thumbor'
    s.add_dependency 'omniauth-line'
    s.add_dependency 'google-apis-secretmanager_v1'
    s.add_dependency 'messagebird-rest'
    s.add_dependency 'rabl-rails'
    s.add_dependency 'sidekiq-transaction_guard'
    s.add_dependency 'sidekiq-bulk'
    s.add_dependency 'qrio'
    s.add_dependency 'hash_symbolizer'
    s.add_dependency 'activejob-status'
    s.add_dependency 'guard-test'
    s.add_dependency 'guard-ctags-bundler'
    s.add_dependency 'rumouse'
    s.add_dependency 'json-api-vanilla'
    s.add_dependency 'resque-pause'
    s.add_dependency 'jekyll-asciidoc'
#    s.add_dependency 'gitlab-default_value_for'
    s.add_dependency 'haikunator'
    s.add_dependency 'server_log_parser'
#    s.add_dependency 'logstash-filter-age'
    s.add_dependency 'rails-healthcheck'
    s.add_dependency 'google-cloud-monitoring-v3'
    s.add_dependency 'busser-rspec_datadog'
    s.add_dependency 'foundation-icons-sass-rails'
    s.add_dependency 'invoker'
    s.add_dependency 'extensions'
    s.add_dependency 'stream-chat-ruby'
    s.add_dependency 'parallelized_specs'
    s.add_dependency 'active_decorator-rspec'
    s.add_dependency 'sensu-plugins-ssl'
    s.add_dependency 'beaker-openstack'
    s.add_dependency 'dirty-memoize'
    s.add_dependency 'cocoapods-blocklist'
    s.add_dependency 'puppet_facts'
    s.add_dependency 'dry-monads-sorbet'
    s.add_dependency 'sensu-extensions'
#    s.add_dependency 'fake_sqs'
    s.add_dependency 'gtk2'
    s.add_dependency 'redirect_safely'
    s.add_dependency 'activerecord-tableless'
    s.add_dependency 'bootstrap-editable-rails'
    s.add_dependency 'vagrant-reload'
    s.add_dependency 'grim'
    s.add_dependency 'folio-pagination'
    s.add_dependency 'bake-toolkit'
    s.add_dependency 'rubber'
    s.add_dependency 'nexmo-jwt'
    s.add_dependency 'omniauth-ultraauth'
    s.add_dependency 'testrail_client'
    s.add_dependency 'guess'
    s.add_dependency 'rest-core'
#    s.add_dependency 'activerecord_any_of'
    s.add_dependency 'delayed-web'
    s.add_dependency 'rdf-n3'
    s.add_dependency 'gmo'
    s.add_dependency 'rake_dependencies'
    s.add_dependency 'sunspot_matchers'
    s.add_dependency 'win32-eventlog'
    s.add_dependency 'cf-app-utils'
    s.add_dependency 'rake_fly'
    s.add_dependency 'socket.io-rails'
    s.add_dependency 'iso639'
    s.add_dependency 'pincers'
    s.add_dependency 'htauth'
#    s.add_dependency 'rocket_pants'
    s.add_dependency 'humanize_boolean'
    s.add_dependency 'capistrano-newrelic'
    s.add_dependency 'rcodetools'
    s.add_dependency 'fastlane-plugin-teams'
    s.add_dependency 'geoip2'
    s.add_dependency 'fastlane-plugin-lizard'
    s.add_dependency 'turnip_formatter'
    s.add_dependency 'nhtsa_vin'
#    s.add_dependency 'beaker-vmware'
    s.add_dependency 'karafka-sidekiq-backend'
    s.add_dependency 'gitversion'
    s.add_dependency 'wisper-activerecord'
    s.add_dependency 'beaker-google'
    s.add_dependency 'grpc_mock'
    s.add_dependency 'vanity'
#    s.add_dependency 'apivore'
    s.add_dependency 'activerecord-postgresql-adapter'
    s.add_dependency 'mailkick'
    s.add_dependency 'keepass-password-generator'
    s.add_dependency 'razorpay'
    s.add_dependency 'google-cloud-bigtable'
#    s.add_dependency 'refile-s3'
    s.add_dependency 'rom-core'
    s.add_dependency 'csv_shaper'
    s.add_dependency 'hydra-access-controls'
    s.add_dependency 'eligible'
    s.add_dependency 'link_thumbnailer'
    s.add_dependency 'fastlane-plugin-rome'
#    s.add_dependency 'refile-mini_magick'
#    s.add_dependency 'wikidata-client'
    s.add_dependency 'routo'
    s.add_dependency 'omnibus'
    s.add_dependency 'garb'
    s.add_dependency 'require_reloader'
    s.add_dependency 'fluent-plugin-filter_typecast'
    s.add_dependency 'ga_cookie_parser'
    s.add_dependency 'crocodoc-ruby'
    s.add_dependency 'standby'
}
