
  require 'rubygems'

Gem::Specification.new {|s|
    s.name          = 'pkg36'
    s.version       = '0.0.1'
    s.author        = 'naresh'
    s.email         = 'nareshdevasani@gmail.com'
    s.homepage      = 'http://github.com/nareshdevasani'
    s.platform      = Gem::Platform::RUBY
    s.summary       = 'An empty gem that depends on every gem available'
    s.description   = s.summary

    s.add_dependency 'rollout-ui'
    s.add_dependency 'attributor'
    s.add_dependency 'jipcode'
    s.add_dependency 'pronto-erb_lint'
    s.add_dependency 'get_pomo'
    s.add_dependency 'rails_db_dump_restore'
#    s.add_dependency 'lalala-development'
    s.add_dependency 'gc_stats'
#    s.add_dependency 'lalala-test'
    s.add_dependency 'fluent-plugin-redis-store'
    s.add_dependency 'unobtainium-multifind'
    s.add_dependency 'utopia'
    s.add_dependency 'active_admin_importable'
    s.add_dependency 'doc_raptor'
    s.add_dependency 'jekyll-twitter-plugin'
    s.add_dependency 'ZURB-foundation'
    s.add_dependency 'chef-handler-profiler'
    s.add_dependency 'pygmentize'
    s.add_dependency 'redphone'
    s.add_dependency 'relaton'
    s.add_dependency 'embulk-output-redshift'
    s.add_dependency 'postageapp'
    s.add_dependency 'selenium-proxy'
    s.add_dependency 'hiera-vault'
    s.add_dependency 'exonio'
#    s.add_dependency 'torquebox-core'
    s.add_dependency 'carthage_cache'
    s.add_dependency 'mini_backtrace'
#    s.add_dependency 'inst-jobs-statsd'
#    s.add_dependency 'tinymce-rails-imageupload'
    s.add_dependency 'ruby_rncryptor'
    s.add_dependency 'make_resourceful'
    s.add_dependency 'polyrex'
#    s.add_dependency 'origen'
    s.add_dependency 'redis-reconnect_with_readonly'
    s.add_dependency 'litecable'
#    s.add_dependency 'logstash-output-datadog_metrics'
    s.add_dependency 'activerecord-mysql-unsigned'
    s.add_dependency 'validators'
    s.add_dependency 'slackr'
    s.add_dependency 'j2119'
    s.add_dependency 'sidekiq-symbols'
    s.add_dependency 'samovar'
#    s.add_dependency 'woople-theme'
    s.add_dependency 'rye'
    s.add_dependency 'clocale'
    s.add_dependency 'guard-sass'
    s.add_dependency 'calendar_helper'
    s.add_dependency 'blurhash'
    s.add_dependency 'multiparty'
    s.add_dependency 'sinatra-assetpack'
#    s.add_dependency 'hive-messages'
    s.add_dependency 'bootstrap-timepicker-rails'
    s.add_dependency 'puppet-lint-topscope-variable-check'
    s.add_dependency 'localhost'
    s.add_dependency 'crono'
    s.add_dependency 'activerecord-jdbchsqldb-adapter'
    s.add_dependency 'shortcode'
#    s.add_dependency 'omniauth-campus'
    s.add_dependency 'maskmoney-rails'
    s.add_dependency 'active-campaign-rails'
    s.add_dependency 'rutabaga'
    s.add_dependency 'erector'
    s.add_dependency 'faraday-tracer'
    s.add_dependency 'rspotify'
    s.add_dependency 'em-eventsource'
    s.add_dependency 'luhn-ruby'
    s.add_dependency 'tupalo-kdtree'
    s.add_dependency 'capistrano-pending'
    s.add_dependency 'win32-ipc'
    s.add_dependency 'nethttp-instrumentation'
    s.add_dependency 'rspec_candy'
    s.add_dependency 'ibanizator'
    s.add_dependency 'currency-in-words'
    s.add_dependency 'fluent-plugin-azure-storage-append-blob'
    s.add_dependency 'puppet-lint-no_symbolic_file_modes-check'
    s.add_dependency 'websocket-eventmachine-base'
    s.add_dependency 'kafo'
    s.add_dependency 'user-agent-randomizer'
    s.add_dependency 'catarse_pagarme'
#    s.add_dependency 'air18n'
    s.add_dependency 'narou'
    s.add_dependency 'twitter-bootstrap-rails-confirm'
    s.add_dependency 'vagrant-disksize'
    s.add_dependency 'fluent-plugin-buffer-lightening'
    s.add_dependency 'naturalsort'
    s.add_dependency 'iruby'
    s.add_dependency 'simp-rake-helpers'
    s.add_dependency 'solarwinds-itsm-api-definitions'
    s.add_dependency 'rbt'
#    s.add_dependency 'xamarin-test-cloud'
    s.add_dependency 'vault-rails'
    s.add_dependency 'graticule'
    s.add_dependency 'searchlight'
    s.add_dependency 'influxdb-rails'
    s.add_dependency 'dpl-firebase'
    s.add_dependency 'pager_api'
    s.add_dependency 'smart_listing'
#    s.add_dependency 'volt'
#    s.add_dependency 'as_deprecation_tracker'
#    s.add_dependency 'sprockets-redirect'
    s.add_dependency 'hobo'
    s.add_dependency 'require_relative'
    s.add_dependency 'phantomjs_polyfill-rails'
    s.add_dependency 'dicks'
    s.add_dependency 'acts_as_audited'
#    s.add_dependency 'govuk_content_models'
    s.add_dependency 'json-minify'
    s.add_dependency 'autosize-rails'
    s.add_dependency 'capistrano-platform-resources'
    s.add_dependency 'mongo_mapper-unstable'
    s.add_dependency 'tiddle'
    s.add_dependency 'historyjs-rails'
    s.add_dependency 'paperclip-ffmpeg'
#    s.add_dependency 'inspec-core-bin'
#    s.add_dependency 'akamai_api'
    s.add_dependency 'sisimai'
    s.add_dependency 'open_exchange_rates'
    s.add_dependency 'glob'
    s.add_dependency 'pry-sorbet'
    s.add_dependency 'passbook'
    s.add_dependency 'meta_programming'
    s.add_dependency 'pdfjs_viewer-rails'
    s.add_dependency 'task_list'
    s.add_dependency 'rubypress'
    s.add_dependency 'csv-mapper'
#    s.add_dependency 'test_rail-api'
    s.add_dependency 'http_signatures'
    s.add_dependency 'puppet-lint-anchor-check'
#    s.add_dependency 'logstash-output-opensearch'
#    s.add_dependency 'omniauth-etsy-oauth2'
    s.add_dependency 'gdk3'
    s.add_dependency 'fear'
    s.add_dependency 'rails_cookie_overflow'
    s.add_dependency 'requisite'
    s.add_dependency 'kontena-cli'
    s.add_dependency 'timeout-extensions'
    s.add_dependency 'activerecord-jdbcderby-adapter'
    s.add_dependency 'sequel_polymorphic'
    s.add_dependency 'tax_cloud'
    s.add_dependency 'a9n'
#    s.add_dependency 'bearcat'
    s.add_dependency 'mario-redis-lock'
    s.add_dependency 'minimal-mistakes-jekyll'
    s.add_dependency 'master_lock'
    s.add_dependency 'mongoid-observers'
    s.add_dependency 'active_record_host_pool'
    s.add_dependency 'predicated'
    s.add_dependency 'glib-web'
    s.add_dependency 'lookup_by'
    s.add_dependency 'glyphicons'
    s.add_dependency 'biggs'
    s.add_dependency 'gtk3'
    s.add_dependency 'gqtp'
    s.add_dependency 'kitchen-verifier-serverspec'
    s.add_dependency 'hive_geoip2'
    s.add_dependency 'puma-rails'
    s.add_dependency 'printnode'
    s.add_dependency 'vagrant-cachier'
    s.add_dependency 'tracksperanto'
    s.add_dependency 'ruby-lint'
    s.add_dependency 'applicious_utils'
    s.add_dependency 'fridge'
#    s.add_dependency 'refinerycms-dashboard'
    s.add_dependency 'utils'
    s.add_dependency 'swagger-diff'
    s.add_dependency 'wikisnakker'
    s.add_dependency 'fcntl'
    s.add_dependency 'rake-performance'
    s.add_dependency 'mbsy'
#    s.add_dependency 'gitlab-elasticsearch-git'
#    s.add_dependency 'bwapi'
    s.add_dependency 'brock'
    s.add_dependency 'vagrant-triggers'
    s.add_dependency 'age_calculator'
    s.add_dependency 'bitly-oauth'
    s.add_dependency 'acpc_poker_types'
    s.add_dependency 'every_day_irb'
    s.add_dependency 'nitlink'
    s.add_dependency 'prometheus-api-client'
    s.add_dependency 'scallop'
    s.add_dependency 'flapjack'
    s.add_dependency 'chargehound'
    s.add_dependency 'craftbelt'
    s.add_dependency 'arrest'
    s.add_dependency 'lockdown'
    s.add_dependency 'reverse_coverage'
    s.add_dependency 'database_plumber'
    s.add_dependency 'bootstrap-modal-rails'
    s.add_dependency 'sweetalert-rails'
    s.add_dependency 'ionicons-rails'
    s.add_dependency 'has_barcode'
    s.add_dependency 'capistrano-chef'
    s.add_dependency 'embulk-input-s3'
    s.add_dependency 'piwik_analytics'
    s.add_dependency 'ld-patch'
#    s.add_dependency 'crocodoc'
    s.add_dependency 'terraspace'
    s.add_dependency 'attr_json'
    s.add_dependency 'urlmatch'
    s.add_dependency 'zeus-parallel_tests'
    s.add_dependency 'effective_bootstrap'
    s.add_dependency 'onlyoffice_documentserver_testing_framework'
    s.add_dependency 'ably'
    s.add_dependency 'sidekiq-lock'
#    s.add_dependency 'schema_plus_db_default'
    s.add_dependency 'ably-rest'
    s.add_dependency 'mongoid_slug'
    s.add_dependency 'betterplace-content'
    s.add_dependency 'backbone-support'
#    s.add_dependency 'waterfall_bourbon_neat_rails'
    s.add_dependency 'mogli'
#    s.add_dependency 'gitlab-grack'
    s.add_dependency 'GeoRuby'
    s.add_dependency 'rack-cas'
    s.add_dependency 'unimidi'
    s.add_dependency 'attributes'
    s.add_dependency 'git_remote_branch'
    s.add_dependency 'hanami-model'
    s.add_dependency 'rescue_registry'
    s.add_dependency 'adhearsion'
#    s.add_dependency 'active_record_replica'
    s.add_dependency 'mux_ruby'
    s.add_dependency 'govuk-lint'
    s.add_dependency 'remote_table'
    s.add_dependency 'google-apis-admin_directory_v1'
    s.add_dependency 'activerecord-delay_touching'
    s.add_dependency 'json_translate'
    s.add_dependency 'foundation_rails_helper'
    s.add_dependency 'pdd'
    s.add_dependency 'sys-admin'
    s.add_dependency 'soft_deletion'
    s.add_dependency 'masonry-rails'
    s.add_dependency 'sensu-transport-snssqs'
    s.add_dependency 'touch_action'
    s.add_dependency 'jsonapi_errorable'
    s.add_dependency 'rservicebus'
    s.add_dependency 'wiselinks'
    s.add_dependency 'postcodes_io'
    s.add_dependency 'classnames-rails'
#    s.add_dependency 'refinerycms-authentication'
    s.add_dependency 'gir_ffi'
    s.add_dependency 'clean_pagination'
    s.add_dependency 'jbundler'
    s.add_dependency 'should_not'
    s.add_dependency 'server_timing'
    s.add_dependency 'active-model-adapter-source'
    s.add_dependency 'tramway-admin'
    s.add_dependency 'actionview-component'
    s.add_dependency 'buttercms-rails'
}
