  require 'rubygems'

Gem::Specification.new {|s|
    s.name          = 'pkg21'
    s.version       = '0.0.1'
    s.author        = 'Julio Capote'
    s.email         = 'jcapote@gmail.com'
    s.homepage      = 'http://github.com/capotej/trollface'
    s.platform      = Gem::Platform::RUBY
    s.summary       = 'An empty gem that depends on every gem available'
    s.description   = s.summary

    s.add_dependency 'authorizenet'
    s.add_dependency 'em_pessimistic'
    s.add_dependency 'graphql-schema_comparator'
    s.add_dependency 'fluent-plugin-bigquery'
    s.add_dependency 'mongoid_rails_migrations'
    s.add_dependency 'train-habitat'
    s.add_dependency 'aws-sdk-sagemakermetrics'
    s.add_dependency 'time'
    s.add_dependency 'ruby-maven-libs'
    s.add_dependency 'beaker-hiera'
    s.add_dependency 'yaml'
#    s.add_dependency 'logstash-input-couchdb_changes'
    s.add_dependency 'google-apis-cloudresourcemanager_v1'
    s.add_dependency 'excon-middleware-aws-exponential_backoff'
    s.add_dependency 'browsermob-proxy'
    s.add_dependency 'gem_plugin'
    s.add_dependency 'autodoc'
    s.add_dependency 'elasticsearch-xpack'
    s.add_dependency 'engtagger'
    s.add_dependency 'axe-core-rspec'
    s.add_dependency 'delayed_job_mongoid'
    s.add_dependency 'whenever-test'
    s.add_dependency 'w3c_validators'
    s.add_dependency 'fluent-plugin-geoip'
    s.add_dependency 'active_record_doctor'
    s.add_dependency 'cf-uaac'
    s.add_dependency 'fastlane-plugin-trainer'
    s.add_dependency 'percy-capybara'
    s.add_dependency 'que'
    s.add_dependency 'cuke_sniffer'
    s.add_dependency 'fresolv'
    s.add_dependency 'spinach-rails'
    s.add_dependency 'danger-rubocop'
    s.add_dependency 'onnxruntime'
    s.add_dependency 'yaml_db'
    s.add_dependency 'plucky'
    s.add_dependency 'fluent-plugin-anonymizer'
    s.add_dependency 'spree_sample'
    s.add_dependency 'gooddata'
    s.add_dependency 'fast_xs'
    s.add_dependency 'interpolator'
    s.add_dependency 'griddler-sendgrid'
    s.add_dependency 'danger-checkstyle_format'
#    s.add_dependency 'logstash-input-google_pubsub'
    s.add_dependency 'ruby-libvirt'
    s.add_dependency 'libddprof'
    s.add_dependency 'rspec-legacy_formatters'
    s.add_dependency 'activejob-retry'
    s.add_dependency 'blind_index'
    s.add_dependency 'gollum-rugged_adapter'
    s.add_dependency 'zxcvbn-ruby'
    s.add_dependency 'hanami-utils'
    s.add_dependency 'rack-mobile-detect'
    s.add_dependency 'dnsimple'
    s.add_dependency 'metric_fu'
    s.add_dependency 'xeroizer'
#    s.add_dependency 'terraform_landscape'
    s.add_dependency 'ziptz'
    s.add_dependency 'aws-sdk-kinesisvideowebrtcstorage'
    s.add_dependency 'fastlane-plugin-bundletool'
    s.add_dependency 'fontcustom'
    s.add_dependency 'rspec-sorbet'
    s.add_dependency 'blingfire'
    s.add_dependency 'resolv'
    s.add_dependency 'vpim'
    s.add_dependency 'ri_cal'
    s.add_dependency 'less-rails-bootstrap'
    s.add_dependency 'xml-mapping'
    s.add_dependency 'anima'
    s.add_dependency 'holiday_jp'
    s.add_dependency 'mpxj'
    s.add_dependency 'apollo-federation'
    s.add_dependency 'levenshtein'
    s.add_dependency 'joiner'
    s.add_dependency 'password_strength'
    s.add_dependency 'mailboxer'
    s.add_dependency 'arvados'
    s.add_dependency 'native-package-installer'
    s.add_dependency 'capistrano-maintenance'
    s.add_dependency 'orderedhash'
    s.add_dependency 'cfndsl'
    s.add_dependency 'embedly'
    s.add_dependency 'rails_param'
    s.add_dependency 'fluent-plugin-logzio'
    s.add_dependency 'active_record_shards'
    s.add_dependency 'discourse_api'
    s.add_dependency 'fog-cloudstack'
    s.add_dependency 'pry-debugger'
    s.add_dependency 'tracking_number'
    s.add_dependency 'mobility'
#    s.add_dependency 'karafka-core'
    s.add_dependency 'grape_on_rails_routes'
    s.add_dependency 'sql_enum'
    s.add_dependency 'coveralls-lcov'
    s.add_dependency 'guid'
    s.add_dependency 'sinatra-param'
    s.add_dependency 'fauxhai-ng'
    s.add_dependency 'georuby'
    s.add_dependency 'aws-sdk-licensemanagerlinuxsubscriptions'
    s.add_dependency 'pickle'
    s.add_dependency 'i18n-active_record'
    s.add_dependency 'ruby-jmeter'
    s.add_dependency 'bosh_common'
    s.add_dependency 'grocer'
    s.add_dependency 'informers'
    s.add_dependency 'activerecord-jdbcmysql-adapter'
    s.add_dependency 'allocations'
    s.add_dependency 'opencensus-stackdriver'
    s.add_dependency 'fastly'
    s.add_dependency 'geoip2_c'
    s.add_dependency 'zstd-ruby'
    s.add_dependency 'mailjet'
    s.add_dependency 'russian'
    s.add_dependency 'render_async'
    s.add_dependency 'rufo'
    s.add_dependency 'rack-user_agent'
    s.add_dependency 'active_record_extended'
    s.add_dependency 'jdbc-postgres'
    s.add_dependency 'breakpoint'
    s.add_dependency 'activerecord-oracle_enhanced-adapter'
    s.add_dependency 'sensu-plugins-ntp'
    s.add_dependency 'solidus_api'
    s.add_dependency 'fb_graph2'
    s.add_dependency 'spree_cmd'
    s.add_dependency 'smstools'
    s.add_dependency 'solidus_core'
    s.add_dependency 'puppet-lint-param-docs'
    s.add_dependency 'apple_id'
    s.add_dependency 'standalone_migrations'
    s.add_dependency 'sinatra-flash'
    s.add_dependency 'solidus_backend'
    s.add_dependency 'querystring'
    s.add_dependency 'logging-rails'
    s.add_dependency 'beaneater'
    s.add_dependency 'prawn-security'
    s.add_dependency 'i18n-country-translations'
    s.add_dependency 'numbers_in_words'
    s.add_dependency 'machinist'
    s.add_dependency 'fluent-plugin-tag-normaliser'
    s.add_dependency 'contentful-management'
    s.add_dependency 'ledermann-rails-settings'
    s.add_dependency 'capistrano-yarn'
    s.add_dependency 'rack_csrf'
    s.add_dependency 'capistrano-rails-console'
    s.add_dependency 'awspec'
    s.add_dependency 'migration_data'
    s.add_dependency 'gobject-introspection'
    s.add_dependency 'rbhive'
    s.add_dependency 'nats-pure'
#    s.add_dependency 'dependabot-dep'
    s.add_dependency 'enumerate_it'
    s.add_dependency 'frozen_record'
#    s.add_dependency 'github_changelog_generator'
    s.add_dependency 'descriptive-statistics'
#    s.add_dependency 'kitchen-ec2'
    s.add_dependency 'cpf_faker'
#    s.add_dependency 'bosh_cli'
    s.add_dependency 'guard-rake'
    s.add_dependency 'simple_uuid'
    s.add_dependency 'guard-spring'
    s.add_dependency 'gio2'
    s.add_dependency 'resque-loner'
    s.add_dependency 'rails-properties'
    s.add_dependency 'tty-progressbar'
    s.add_dependency 'spring-commands-spinach'
    s.add_dependency 'brass'
    s.add_dependency 'tire'
    s.add_dependency 'damerau-levenshtein'
    s.add_dependency 'rbbt-util'
    s.add_dependency 'raygun4ruby'
    s.add_dependency 'pagarme'
    s.add_dependency 'async-dns'
    s.add_dependency 'tinify'
    s.add_dependency 'geminabox'
    s.add_dependency 'textacular'
    s.add_dependency 'paperclip_database'
    s.add_dependency 'squasher'
    s.add_dependency 'rrule'
    s.add_dependency 'rspec-activejob'
#    s.add_dependency 'gitlab-pry-byebug'
    s.add_dependency 'fastlane-plugin-load_json'
#    s.add_dependency 'spree_backend'
    s.add_dependency 'backticks'
    s.add_dependency 'sq_mini_racer'
    s.add_dependency 'kaminari-bootstrap'
    s.add_dependency 'solidus_support'
    s.add_dependency 'puppet-lint-version_comparison-check'
    s.add_dependency 'ach'
    s.add_dependency 'jpmobile'
    s.add_dependency 'run_loop'
    s.add_dependency 'rails_email_validator'
    s.add_dependency 'activerecord-mysql-reconnect'
    s.add_dependency 'strong_password'
    s.add_dependency 'solidus_sample'
    s.add_dependency 'active_admin_datetimepicker'
    s.add_dependency 'transaction_retry'
    s.add_dependency 'cocoapods-keys'
    s.add_dependency 'switch_user'
    s.add_dependency 'fb_graph'
    s.add_dependency 'mail_safe'
}
