
  require 'rubygems'

Gem::Specification.new {|s|
    s.name          = 'pkg13'
    s.version       = '0.0.1'
    s.author        = 'Julio Capote'
    s.email         = 'jcapote@gmail.com'
    s.homepage      = 'http://github.com/capotej/trollface'
    s.platform      = Gem::Platform::RUBY
    s.summary       = 'An empty gem that depends on every gem available'
    s.description   = s.summary

    s.add_dependency 'roar'
    s.add_dependency 'foreigner'
    s.add_dependency 'fast-stemmer'
#    s.add_dependency 'logstash-output-redis'
#    s.add_dependency 'logstash-codec-msgpack'
    s.add_dependency 'travis'
#    s.add_dependency 'logstash-codec-edn_lines'
    s.add_dependency 'fileutils'
#    s.add_dependency 'logstash-codec-edn'
    s.add_dependency 'importmap-rails'
#    s.add_dependency 'logstash-input-heartbeat'
    s.add_dependency 'after_commit_action'
    s.add_dependency 'memcachier'
#    s.add_dependency 'logstash-codec-graphite'
#    s.add_dependency 'canonical-rails'
#    s.add_dependency 'jruby-stdin-channel'
#    s.add_dependency 'logstash-filter-metrics'
    s.add_dependency 'brpoplpush-redis_script'
#    s.add_dependency 'file_validators'
    s.add_dependency 'google-apis-bigquery_v2'
#    s.add_dependency 'logstash-filter-drop'
#    s.add_dependency 'logstash-filter-sleep'
#    s.add_dependency 'logstash-output-stdout'
#    s.add_dependency 'cnvrg'
    s.add_dependency 'moped'
    s.add_dependency 'algorithms'
#    s.add_dependency 'postmark-rails'
#    s.add_dependency 'middleman'
    s.add_dependency 'libsaml'
#    s.add_dependency 'logstash-filter-split'
#    s.add_dependency 'logstash-output-null'
    s.add_dependency 'airborne'
    s.add_dependency 'sprite-factory'
#    s.add_dependency 'lodash-rails'
    s.add_dependency 'pusher-client'
    s.add_dependency 'voight_kampff'
#    s.add_dependency 'logstash-filter-throttle'
#    s.add_dependency 'logstash-filter-urldecode'
    s.add_dependency 'hash_validator'
    s.add_dependency 'namae'
    s.add_dependency 'fakefs'
    s.add_dependency 'dry-matcher'
#    s.add_dependency 'logstash-output-csv'
    s.add_dependency 'local_time'
    s.add_dependency 'jls-lumberjack'
#    s.add_dependency 'logstash-codec-dots'
#    s.add_dependency 'logstash-output-graphite'
    s.add_dependency 'seed_dump'
    s.add_dependency 'yard-sorbet'
    s.add_dependency 'opentelemetry-instrumentation-faraday'
#    s.add_dependency 'logstash-input-ganglia'
    s.add_dependency 'paquet'
    s.add_dependency 'map'
#    s.add_dependency 'logstash-output-pipe'
    s.add_dependency 'fluent-plugin-datadog'
    s.add_dependency 'gooddata_datawarehouse'
    s.add_dependency 'geckodriver-helper'
#    s.add_dependency 'logstash-output-nagios'
#    s.add_dependency 'snappy-jars'
#    s.add_dependency 'committee'
#    s.add_dependency 'logstash-input-graphite'
    s.add_dependency 'ruby-mp3info'
#    s.add_dependency 'logstash-output-webhdfs'
    s.add_dependency 'sensu-plugins-cpu-checks'
    s.add_dependency 'forgery'
    s.add_dependency 'rgeo-geojson'
#    s.add_dependency 'capistrano-passenger'
#    s.add_dependency 'sorbet-coerce'
#    s.add_dependency 'padrino-support'
#    s.add_dependency 'opentelemetry-instrumentation-redis'
#    s.add_dependency 'activeadmin_addons'
    s.add_dependency 'cells'
#    s.add_dependency 'kaminari-mongoid'
#    s.add_dependency 'double-bag-ftps'
#    s.add_dependency 'sidekiq-throttled'
#    s.add_dependency 'rbi'
#    s.add_dependency 'array_stats'
#    s.add_dependency 'amatch'
    s.add_dependency 'tee_simple'
#    s.add_dependency 'logstash-output-kafka'
#    s.add_dependency 'github-pages'
    s.add_dependency 'java-properties'
    s.add_dependency 'certified'
    s.add_dependency 'event_emitter'
    s.add_dependency 'net-http-pipeline'
    s.add_dependency 'record_tag_helper'
    s.add_dependency 'omniauth-linkedin-oauth2'
}
