
  require 'rubygems'

Gem::Specification.new {|s|
    s.name          = 'pkg14'
    s.version       = '0.0.1'
    s.author        = 'naresh'
    s.email         = 'nareshdevasani@gmail.com'
    s.homepage      = 'http://github.com/nareshdevasani'
    s.platform      = Gem::Platform::RUBY
    s.summary       = 'An empty gem that depends on every gem available'
    s.description   = s.summary

    s.add_dependency 'aws-sdk-rolesanywhere'
    s.add_dependency 'graphql-metrics'
    s.add_dependency 'jekyll-coffeescript'
    s.add_dependency 'mime'
    s.add_dependency 'json_matchers'
    s.add_dependency 'xcresult'
    s.add_dependency 'openapi_parser'
    s.add_dependency 'trainer'
    s.add_dependency 'google-ads-googleads'
    s.add_dependency 'opentelemetry-exporter-otlp'
    s.add_dependency 'pdf-forms'
    s.add_dependency 'rspec-repeat'
    s.add_dependency 'hodel_3000_compliant_logger'
    s.add_dependency 'opentelemetry-instrumentation-net_http'
    s.add_dependency 'bitly'
    s.add_dependency 'polyfill'
    s.add_dependency 'fluent-plugin-route'
    s.add_dependency 'chargebee'
    s.add_dependency 'opentelemetry-instrumentation-sidekiq'
    s.add_dependency 'nakayoshi_fork'
#    s.add_dependency 'logstash-filter-truncate'
    s.add_dependency 'di-ruby-lvm-attrib'
    s.add_dependency 'cityhash'
    s.add_dependency 'logstasher'
    s.add_dependency 'ruby-lsp'
    s.add_dependency 'bulk_insert'
    s.add_dependency 'feedjira'
    s.add_dependency 'enumerable-statistics'
    s.add_dependency 'sensu-plugins-load-checks'
    s.add_dependency 'html-proofer'
    s.add_dependency 'equivalent-xml'
    s.add_dependency 'apartment'
    s.add_dependency 'pundit-matchers'
    s.add_dependency 'email_reply_parser'
    s.add_dependency 'activerecord_sane_schema_dumper'
    s.add_dependency 'fluent-plugin-multi-format-parser'
    s.add_dependency 'yell'
    s.add_dependency 'paypal-sdk-rest'
    s.add_dependency 'jsonapi'
    s.add_dependency 'highcharts-rails'
    s.add_dependency 'aws-sdk-licensemanagerusersubscriptions'
    s.add_dependency 'watir-webdriver'
    s.add_dependency 'semian'
    s.add_dependency 'shotgun'
    s.add_dependency 'envyable'
    s.add_dependency 'rkelly-remix'
    s.add_dependency 'desk_api'
    s.add_dependency 'unicode_plot'
    s.add_dependency 'google-apis-dns_v1'
    s.add_dependency 'bundle-audit'
    s.add_dependency 'goldiloader'
    s.add_dependency 'auto_strip_attributes'
#    s.add_dependency 'logstash-input-kafka'
    s.add_dependency 'datadog_api_client'
    s.add_dependency 'bower-rails'
    s.add_dependency 'exception_handling'
    s.add_dependency 'safe_type'
    s.add_dependency 'gh'
    s.add_dependency 'dry-monitor'
    s.add_dependency 'rack-parser'
    s.add_dependency 'safe_shell'
    s.add_dependency 'data_uri'
    s.add_dependency 'azure_mgmt_key_vault'
    s.add_dependency 'invoca-utils'
    s.add_dependency 'contextual_logger'
    s.add_dependency 'sunspot'
    s.add_dependency 'mongoid-history'
    s.add_dependency 'aws-sdk-privatenetworks'
    s.add_dependency 'sqlite3-ruby'
#    s.add_dependency 'jruby-launcher'
    s.add_dependency 'resque_spec'
    s.add_dependency 'salesforce_bulk_api'
    s.add_dependency 'cmdparse'
    s.add_dependency 'monotonic_tick_count'
    s.add_dependency 'rswag'
    s.add_dependency 'referer-parser'
    s.add_dependency 'fakeweb'
    s.add_dependency 'fluent-plugin-google-cloud'
    s.add_dependency 'middleman-core'
    s.add_dependency 'mailchimp-api'
    s.add_dependency 'librarianp'
    s.add_dependency 'rss'
    s.add_dependency 'amoeba'
    s.add_dependency 'sequel_pg'
    s.add_dependency 'discordrb-webhooks-blackst0ne'
    s.add_dependency 'cgi'
    s.add_dependency 'ruby-filemagic'
    s.add_dependency 's3'
    s.add_dependency 'rbs'
    s.add_dependency 'faye'
    s.add_dependency 'pg_array_parser'
    s.add_dependency 'process_settings'
    s.add_dependency 'sendgrid'
    s.add_dependency 'resque-status'
    s.add_dependency 'jenkins_api_client'
    s.add_dependency 'spring-commands-rubocop'
    s.add_dependency 'rufus-lua'
    s.add_dependency 'opentelemetry-instrumentation-rails'
    s.add_dependency 'bootstrap-kaminari-views'
    s.add_dependency 'specific_install'
    s.add_dependency 'mongoid_paranoia'
    s.add_dependency 'protected_attributes_continued'
    s.add_dependency 'mjml-rails'
    s.add_dependency 'delayed_job_web'
#    s.add_dependency 'logstash-input-rabbitmq'
}
