
  require 'rubygems'

Gem::Specification.new {|s|
    s.name          = 'pkg44'
    s.version       = '0.0.1'
    s.author        = 'naresh'
    s.email         = 'nareshdevasani@gmail.com'
    s.homepage      = 'http://github.com/nareshdevasani'
    s.platform      = Gem::Platform::RUBY
    s.summary       = 'An empty gem that depends on every gem available'
    s.description   = s.summary

    s.add_dependency 'flareon'
    s.add_dependency 'readline'
#    s.add_dependency 'phcscriptcdn'
    s.add_dependency 'zillabyte-cli'
    s.add_dependency 'Avatax_TaxService'
    s.add_dependency 'ddplugin'
    s.add_dependency 'executable'
    s.add_dependency 'text2svg'
    s.add_dependency 'fastlane-plugin-simctl'
    s.add_dependency 'i18n_rails_helpers'
#    s.add_dependency 'logstash-codec-cloudwatch_logs'
    s.add_dependency 'safe_timeout'
    s.add_dependency 'json_schema_tools'
    s.add_dependency 'longurl'
    s.add_dependency 'CloudyScripts'
    s.add_dependency 'af'
    s.add_dependency 'saneitized'
    s.add_dependency 'everypolitician-popolo'
    s.add_dependency 'redis-script_manager'
    s.add_dependency 'sensu-plugins-mongodb'
    s.add_dependency 'cztop'
    s.add_dependency 'capistrano-slack-notify'
    s.add_dependency 'clickatell'
    s.add_dependency 'synvert-core'
    s.add_dependency 'animation'
    s.add_dependency 'ezclient'
    s.add_dependency 'activerecord-reputation-system'
#    s.add_dependency 'spatial_features'
    s.add_dependency 'response_code_matchers'
#    s.add_dependency 'cosmos'
    s.add_dependency 'fluent-plugin-td-monitoring'
    s.add_dependency 'boxen'
    s.add_dependency 'dslh'
    s.add_dependency 'puppet-lint-roles_and_profiles-check'
    s.add_dependency 'restpack-web'
    s.add_dependency 'unification_assertion'
    s.add_dependency 'observer'
    s.add_dependency 'kaui'
    s.add_dependency 'actionmailer-with-request'
    s.add_dependency 'oboe'
    s.add_dependency 'browsercms'
    s.add_dependency 'hypdf'
    s.add_dependency 'lhc'
    s.add_dependency 'recog-intrigue'
    s.add_dependency 'mediaelement_rails'
    s.add_dependency 'redis_cluster'
    s.add_dependency 'indentation'
    s.add_dependency 'xlogin'
    s.add_dependency 'dependabot-core'
    s.add_dependency 'tapsoob'
#    s.add_dependency 'lograge_activejob'
    s.add_dependency 'turbot-runner'
    s.add_dependency 'embulk-input-gcs'
    s.add_dependency 'zsteg'
    s.add_dependency 'http2'
#    s.add_dependency 'protractor-rails'
#    s.add_dependency 'graphwerk'
    s.add_dependency 'livetext'
    s.add_dependency 'orbit_activities'
    s.add_dependency 'rufus-dollar'
    s.add_dependency 'yard-rspec'
    s.add_dependency 'evt-messaging'
#    s.add_dependency 'gotransverse-tract-api'
    s.add_dependency 'lock_jar'
    s.add_dependency 'dm-persevere-adapter'
    s.add_dependency 'environs'
    s.add_dependency 'merb-helpers'
    s.add_dependency 'heavens_door'
    s.add_dependency 'sinatra-websocket'
    s.add_dependency 'eco-helpers'
    s.add_dependency 'scraping'
#    s.add_dependency 'apirunner'
    s.add_dependency 'EICAR'
    s.add_dependency 'couch_potato'
#    s.add_dependency 'manageiq-api-client'
#    s.add_dependency 'logstash-input-jmx'
    s.add_dependency 'cake'
    s.add_dependency 'request_queue'
    s.add_dependency 'relaton-calconnect'
    s.add_dependency 'name_splitter'
    s.add_dependency 'restify'
    s.add_dependency 'valium'
#    s.add_dependency 'unpoly-rails'
    s.add_dependency 'srt'
    s.add_dependency 'as-notifications'
    s.add_dependency 'fastlane-plugin-setup_fragile_tests_for_rescan'
#    s.add_dependency 'partially_useful'
    s.add_dependency 'mediainfo'
#    s.add_dependency 'attributor-flatpack'
    s.add_dependency 'killbill'
    s.add_dependency 'sprockets-media_query_combiner'
    s.add_dependency 'bosh_warden_cpi'
    s.add_dependency 'kender'
#    s.add_dependency 'entypo-rails'
#    s.add_dependency 'activerecord-postgres_pub_sub'
    s.add_dependency 'rapns'
    s.add_dependency 'active_directory'
#    s.add_dependency 'eav_hashes'
    s.add_dependency 'n_one'
    s.add_dependency 'capistrano-spec'
    s.add_dependency 'googlestaticmap'
    s.add_dependency 'inline_styles'
    s.add_dependency 'esvg'
    s.add_dependency 'cassandra-cql'
    s.add_dependency 'metric_fu-roodi'
#    s.add_dependency 'jquery-dotdotdot-rails'
    s.add_dependency 'domino'
#    s.add_dependency 'maestrano-connector-rails'
    s.add_dependency 'footrest'
    s.add_dependency 'interactive-logger'
    s.add_dependency 'memcache'
#    s.add_dependency 'google-cloud-container-v1beta1'
    s.add_dependency 'patir'
    s.add_dependency 'mizuno'
    s.add_dependency 'class_inheritable_attributes'
    s.add_dependency 'graphql-map'
    s.add_dependency 'yabeda-prometheus-mmap'
    s.add_dependency 'compass-blend-modes'
    s.add_dependency 'puppet-module-posix-default-r2.1'
    s.add_dependency 'kaltura-client'
#    s.add_dependency 'blacklight_range_limit'
    s.add_dependency 'around_the_world'
#    s.add_dependency 'soaspec'
    s.add_dependency 'ruby-haml-js'
#    s.add_dependency 'adminpanel'
    s.add_dependency 'biodiversity'
    s.add_dependency 'rspec-system-puppet'
#    s.add_dependency 'maily'
    s.add_dependency 'sk_api_schema'
    s.add_dependency 'api_resource'
    s.add_dependency 'puppet-catalog-test'
    s.add_dependency 'resqutils'
    s.add_dependency 'beaker-i18n_helper'
#    s.add_dependency 'coffeebeans'
    s.add_dependency 'oxidized'
    s.add_dependency 'safely'
    s.add_dependency 'parity'
    s.add_dependency 'pt'
    s.add_dependency 'rails-assets-tether'
#    s.add_dependency 'octicons_v2'
    s.add_dependency 'lazy_model'
    s.add_dependency 'ftpfxp'
    s.add_dependency 'accept_language'
    s.add_dependency 'knife-essentials'
    s.add_dependency 'social_security_number'
    s.add_dependency 'pdf_meta'
#    s.add_dependency 'mediawiki_selenium'
    s.add_dependency 'rspec_n'
    s.add_dependency 'hydra-pcdm'
    s.add_dependency 'fluent-plugin-string-scrub'
#    s.add_dependency 'qunit-rails'
#    s.add_dependency 'decidim-core'
    s.add_dependency 'barge'
    s.add_dependency 'fcrepo_wrapper'
    s.add_dependency 'aws4'
    s.add_dependency 'tml'
    s.add_dependency 'bing_translator'
#    s.add_dependency 'decidim'
#    s.add_dependency 'reactive_shipping'
    s.add_dependency 'lrucache'
    s.add_dependency 'fastlane-plugin-instabug_official'
#    s.add_dependency 'cul_scv_hydra'
    s.add_dependency 'whiskey_disk'
    s.add_dependency 'conjoin'
    s.add_dependency 'rspec-timecop'
    s.add_dependency 'pdftoimage'
    s.add_dependency 'hen'
    s.add_dependency 'octopress'
    s.add_dependency 'netconf'
    s.add_dependency 'spork-testunit'
    s.add_dependency 'tramway-event'
    s.add_dependency 'ayadn'
    s.add_dependency 'mercadolibre'
    s.add_dependency 'trackerific'
    s.add_dependency 'fastlane-plugin-download_github_release_asset'
    s.add_dependency 'yard-coderay'
    s.add_dependency 'dpl-cloud_files'
    s.add_dependency 'ramaze'
    s.add_dependency 'ae'
#    s.add_dependency 'social_stream-presence'
#    s.add_dependency 'capistrano-magento2'
#    s.add_dependency 'capistrano-rails-collection'
    s.add_dependency 'newrelic-middleware'
    s.add_dependency 'sassy-strings'
    s.add_dependency 'spicerack'
#    s.add_dependency 'mongrel2'
    s.add_dependency 'jwt_signed_request'
    s.add_dependency 'maccman-mash'
    s.add_dependency 'garage_client'
    s.add_dependency 'class_kit'
#    s.add_dependency 'capistrano-bower'
#    s.add_dependency 'phccontactorpro'
#    s.add_dependency 'rcfiles'
    s.add_dependency 'smooch-api'
    s.add_dependency 'raspell'
    s.add_dependency 'url_escape'
    s.add_dependency 'http_stub'
    s.add_dependency 'trackman'
#    s.add_dependency 'smalruby-editor'
#    s.add_dependency 'mi'
    s.add_dependency 'fresh_redis'
#    s.add_dependency 'fontello_rails_converter'
    s.add_dependency 'mongo_ext'
    s.add_dependency 'imagesize'
    s.add_dependency 'xcprofiler'
    s.add_dependency 'sidekiq-gelf'
    s.add_dependency 'kaminari-mongo_mapper'
#    s.add_dependency 'administrate-field-image'
    s.add_dependency 'graphiti_spec_helpers'
#    s.add_dependency 'apidae'
    s.add_dependency 'deepstruct'
    s.add_dependency 'sane_patch'
    s.add_dependency 'rom-support'
    s.add_dependency 'postgres'
    s.add_dependency 'standup'
    s.add_dependency 'modularity'
    s.add_dependency 'oliver'
    s.add_dependency 'lemmatizer'
    s.add_dependency 'rake-notes'
#    s.add_dependency 'capistrano-gulp'
    s.add_dependency 'app_config'
#    s.add_dependency 'beyond-rails'
#    s.add_dependency 'tweetkit'
    s.add_dependency 'slyphon-zookeeper_jar'
    s.add_dependency 'pismo'
#    s.add_dependency 'stellar-sdk'
    s.add_dependency 'api_client'
    s.add_dependency 'mini_exiftool_vendored'
    s.add_dependency 'i18n_routing'
    s.add_dependency 'twitter-ads'
    s.add_dependency 'azure_mgmt_subscriptions'
    s.add_dependency 'rspec-multi-mock'
    s.add_dependency 'capybara-puma'
    s.add_dependency 'svn2git'
    s.add_dependency 'mutter'
#=begin
    s.add_dependency 'rack-json_schema'
    s.add_dependency 'deterministic'
    s.add_dependency 'shell-spinner'
#    s.add_dependency 'ocean-dynamo'
#    s.add_dependency 'fonemas'
#    s.add_dependency 'rails_amp'
#    s.add_dependency 'thredded'
#    s.add_dependency 'google-cloud-container-v1'
#=begin
    s.add_dependency 'test_notifier'
    s.add_dependency 'generamba'
    s.add_dependency 'surveyor'
    s.add_dependency 'rationalist'
    s.add_dependency 'telegraf'
    s.add_dependency 'oauth2-aptible'
    s.add_dependency 'jruby-kafka'

#=end
}
