
  require 'rubygems'

Gem::Specification.new {|s|
    s.name          = 'pkg47'
    s.version       = '0.0.1'
    s.author        = 'naresh'
    s.email         = 'nareshdevasani@gmail.com'
    s.homepage      = 'http://github.com/nareshdevasani'
    s.platform      = Gem::Platform::RUBY
    s.summary       = 'An empty gem that depends on every gem available'
    s.description   = s.summary

    s.add_dependency 'event-calendar'
    s.add_dependency 'inum'
    s.add_dependency 'jqcloud-rails'
    s.add_dependency 'hoe-git'
    s.add_dependency 'jekyll-rdf'
    s.add_dependency 'foreman_maintain'
    s.add_dependency 'convergence'
#    s.add_dependency 'encrypted-cookie-store'
    s.add_dependency 'paypal-payouts-sdk'
    s.add_dependency 'pp_sql'
    s.add_dependency 'cucumber-api'
    s.add_dependency 'muck-services'
    s.add_dependency 'xml-kit'
    s.add_dependency 'ruby-next'
    s.add_dependency 'kstrano'
    s.add_dependency 'bootstrap3-rails'
    s.add_dependency 'cucumber-nagios'
    s.add_dependency 'executrix'
    s.add_dependency 'ey_services_api'
    s.add_dependency 'codeclimate-parallel-test-reporter'
    s.add_dependency 'skeptick'
    s.add_dependency 'cucumber_lint'
    s.add_dependency 'libxslt-ruby'
    s.add_dependency 'voucherify'
    s.add_dependency 'slackdown'
    s.add_dependency 'mimic'
    s.add_dependency 'emitter'
    s.add_dependency 'telegramAPI'
    s.add_dependency 'compass-h5bp'
    s.add_dependency 'hey'
    s.add_dependency 'technologic'
    s.add_dependency 'reality-generators'
    s.add_dependency 'rails-patterns'
    s.add_dependency 'hermod'
    s.add_dependency 'newrelic_resque_agent'
    s.add_dependency 'allowy'
    s.add_dependency 'async-rspec'
    s.add_dependency 'sidekiq_prometheus'
    s.add_dependency 'cmath'
    s.add_dependency 'heroku_hatchet'
    s.add_dependency 'unicode2latex'
    s.add_dependency 'rails_admin_tag_list'
    s.add_dependency 'soapy_cake'
    s.add_dependency 'ip2location_ruby'
    s.add_dependency 'promoter'
    s.add_dependency 'hooch'
    s.add_dependency 'tripod'
    s.add_dependency 'fluent-plugin-kv-parser'
#    s.add_dependency 'capistrano-logrotate'
    s.add_dependency 'crypt19-rb'
    s.add_dependency 'polyblock'
    s.add_dependency 'capistrano-shoryuken'
    s.add_dependency 'duration'
    s.add_dependency 'kuzushi'
    s.add_dependency 'rubyipmi'
    s.add_dependency 'soda'
    s.add_dependency 'swaggard'
    s.add_dependency 'sauce-cucumber'
    s.add_dependency 'awsome'
    s.add_dependency 'rickshaw_rails'
    s.add_dependency 'mails_viewer'
    s.add_dependency 'acts_as_cleo'
    s.add_dependency 'learn-test'
    s.add_dependency 'ddmetrics'
    s.add_dependency 'rspec-rcv'
    s.add_dependency 'rspec-sonarqube-formatter'
    s.add_dependency 'relaton-un'
#    s.add_dependency 'soar_sc_core'
    s.add_dependency 'eye-patch'
    s.add_dependency 'qpid_proton'
    s.add_dependency 'titlecase'
    s.add_dependency 'kount_complete'
    s.add_dependency 'swiftype'
    s.add_dependency 'html5_validators'
    s.add_dependency 'google-cloud-spanner-admin-database-v1'
    s.add_dependency 'worker_scoreboard'
    s.add_dependency 'rspec-buildkite-analytics'
    s.add_dependency 'jasmine_junitxml_formatter'
    s.add_dependency 'draftjs_exporter'
    s.add_dependency 'aws-sdk-osis'
    s.add_dependency 'tokyocabinet'
    s.add_dependency 'mapbox-gl-rails'
#    s.add_dependency 'fastlane-plugin-firebase_test_lab'
#    s.add_dependency 'rspec-hive'
    s.add_dependency 'galakei'
    s.add_dependency 'evertils'
    s.add_dependency 'jekyll-theme-consulting'
    s.add_dependency 'awsborn'
    s.add_dependency 'geolite2_city'
    s.add_dependency 'guard-jasmine-headless-webkit'
    s.add_dependency 'rspec-sequencing'
    s.add_dependency 'activerecord-after-transaction'
    s.add_dependency 'n1_loader'
#    s.add_dependency 'health-data-standards'
#    s.add_dependency 'acmcommits'
#    s.add_dependency 'flowcommerce_spree'
    s.add_dependency 'fastlane-plugin-flutter'
#    s.add_dependency 'kitchen-azurerm'
    s.add_dependency 'dm-is-tree'
    s.add_dependency 'polyrex-objects'
    s.add_dependency 'consul-templaterb'
    s.add_dependency 'validated_object'
#    s.add_dependency 'hamburgerstore'
    s.add_dependency 'rack-revision'
    s.add_dependency 'tiny_mce'
#    s.add_dependency 'liquid-rails'
    s.add_dependency 'spicerack-styleguide'
    s.add_dependency 'tabularize'
    s.add_dependency 'swagger_yard-rails'
    s.add_dependency 'fluent-plugin-tail-ex'
    s.add_dependency 'milkode'
    s.add_dependency 'hebrew_date'
    s.add_dependency 'ar_mysql_flexmaster'
    s.add_dependency 'qb'
    s.add_dependency 'ryodo'
    s.add_dependency 'forking_test_runner'
    s.add_dependency 'process_exists'
    s.add_dependency 'sensu-em'
    s.add_dependency 'formatos-febraban'
    s.add_dependency 'capistrano-slack'
    s.add_dependency 'swagger_engine'
    s.add_dependency 'trigram'
    s.add_dependency 'cavalry'
    s.add_dependency 'once'
    s.add_dependency 'in_place_editing'
    s.add_dependency 'avatars_for_rails'
    s.add_dependency 'jekyll-diagrams'
    s.add_dependency 'amee'
    s.add_dependency 'rails_bootstrap_navbar'
    s.add_dependency 'testbot'
    s.add_dependency 'fluent-plugin-notifier'
    s.add_dependency 'fastlane-plugin-prepare_build_resources'
    s.add_dependency 'problem_details-rails'
    s.add_dependency 'method_locator'
    s.add_dependency 'rails_admin_nestable'
    s.add_dependency 'celluloid-redis'
#    s.add_dependency 'decidim-dev'
#    s.add_dependency 'moonshot'
    s.add_dependency 'mongrel_cluster'
    s.add_dependency 'roauth'
#    s.add_dependency 'refinerycms-testing'
    s.add_dependency 'has_accounts'
    s.add_dependency 'fluent-plugin-retag'
    s.add_dependency 'constructor-core'
    s.add_dependency 'ruby_android'
    s.add_dependency 'ivy4r'
    s.add_dependency 'rubinius-ast'
    s.add_dependency 'github'
    s.add_dependency 'kookaburra'
#    s.add_dependency 'clc-chef-metal-vsphere'
    s.add_dependency 'hash-utils'
    s.add_dependency 'baza'
    s.add_dependency 'reality-facets'
    s.add_dependency 'iiif_manifest'
    s.add_dependency 'crypt-isaac'
    s.add_dependency 'tcell_agent'
#    s.add_dependency 'dictionaries'
    s.add_dependency 'representative'
    s.add_dependency 'excel_rails'
    s.add_dependency 'proc-wait3'
    s.add_dependency 'onchain'
    s.add_dependency 'eyes_universal'
    s.add_dependency 'google-cloud-spanner-v1'
    s.add_dependency 'grb'
    s.add_dependency 'terraformer'
    s.add_dependency 'restful_resource'
    s.add_dependency 'test-unit-rails'
    s.add_dependency 'weel'
    s.add_dependency 'dimples'
    s.add_dependency 'simple_pid'
    s.add_dependency 'mongoid_magic_counter_cache'
    s.add_dependency 'rsec'
    s.add_dependency 'ruby_ami'
#    s.add_dependency 'boxgrinder-build'
#    s.add_dependency 'chef-provisioning-ssh'
    s.add_dependency 'short_circu_it'
    s.add_dependency 'git-review'
    s.add_dependency 'ruby-atmos-pure'
    s.add_dependency 'activerdf'
    s.add_dependency 'email_preview'
#    s.add_dependency 'dirigible'
    s.add_dependency 'stimulus_reflex_testing'
    s.add_dependency 'nestive'
    s.add_dependency 'rspec-stripe'
    s.add_dependency 'bool'
    s.add_dependency 'attempt'
    s.add_dependency 'google_holiday_calendar'
    s.add_dependency 'opennebula-cli'
    s.add_dependency 'radix'
    s.add_dependency 'ruby-fann'
    s.add_dependency 'rack-flash'
    s.add_dependency 'logrotate'
    s.add_dependency 'forgery_ja'
    s.add_dependency 'ruby_expect'
    s.add_dependency 'etherpad-lite'
    s.add_dependency 'fastlane-plugin-codecov_reporter'
#    s.add_dependency 'minke'
    s.add_dependency 'suretax'
    s.add_dependency 'hsluv'
    s.add_dependency 'hotdog'
    s.add_dependency 'strum-service'
    s.add_dependency 'pimpmychangelog'
    s.add_dependency 'timespan'
    s.add_dependency 'manageiq-password'
    s.add_dependency 'pagy_cursor'
    s.add_dependency 'rudder_analytics_sync'
    s.add_dependency 'libusb'
    s.add_dependency 'vagrant-hosts'
    s.add_dependency 'paypal'
    s.add_dependency 'octopoller'
    s.add_dependency 'activefacts'
    s.add_dependency 'mailgun'
    s.add_dependency 'konf'
    s.add_dependency 'rdstation-ruby-client'
    s.add_dependency 'newrelic-typhoeus'
    s.add_dependency 'recordselect'
    s.add_dependency 'predictionio'
    s.add_dependency 'microscope'
    s.add_dependency 'secret_config'
    s.add_dependency 'fluent-plugin-hostname'
    s.add_dependency 'lense'
#    s.add_dependency 'activerecord-id_regions'
#    s.add_dependency 'cloudstack-nagios'
    s.add_dependency 'fluent-plugin-scribe'
    s.add_dependency 'rubinius-compiler'
    s.add_dependency 'transactd'
    s.add_dependency 'pronto-yamllint'
    s.add_dependency 'paul_revere'
    s.add_dependency 'blank_empty_nil_filters'
    s.add_dependency 'google-cloud-spanner-admin-instance-v1'
    s.add_dependency 'okuribito'
    s.add_dependency 'geoblacklight'
    s.add_dependency 'world-flags'
    s.add_dependency 'fluent-plugin-http-healthcheck'
    s.add_dependency 'haml_parser'
    s.add_dependency 'logical_model'
    s.add_dependency 'generate-puppetfile'
    s.add_dependency 'lorem'
#    s.add_dependency 'falkorlib'
    s.add_dependency 'dynamini'
#    s.add_dependency 'social_stream-events'
#    s.add_dependency 'ns_settings_ui'
    s.add_dependency 'activerecord-belongs_to_if'
    s.add_dependency 'google-cloud-automl-v1'
    s.add_dependency 'rack-server_status'
    s.add_dependency 'jsonapi_parameters'
    s.add_dependency 'vagrantup'
    s.add_dependency 'hu'
    s.add_dependency 'ar-uuid'
    s.add_dependency 'mongoid_taggable'

}
