
  require 'rubygems'

Gem::Specification.new {|s|
    s.name          = 'pkg16'
    s.version       = '0.0.1'
    s.author        = 'naresh'
    s.email         = 'nareshdevasani@gmail.com'
    s.homepage      = 'http://github.com/nareshdevasani'
    s.platform      = Gem::Platform::RUBY
    s.summary       = 'An empty gem that depends on every gem available'
    s.description   = s.summary

    s.add_dependency 'rails-api'
    s.add_dependency 'redmine_extensions'
    s.add_dependency 'woothee'
    s.add_dependency 'appium_lib'
    s.add_dependency 'opentelemetry-instrumentation-action_view'
    s.add_dependency 'puppet-lint-unquoted_string-check'
    s.add_dependency 'workflow'
    s.add_dependency 'super_diff'
    s.add_dependency 'opentelemetry-instrumentation-mysql2'
    s.add_dependency 'rate_throttle_client'
    s.add_dependency 'htmlcompressor'
    s.add_dependency 'bond'
    s.add_dependency 'resque-pool'
    s.add_dependency 'simple_token_authentication'
    s.add_dependency 'turbo-sprockets-rails3'
    s.add_dependency 'minitest-rg'
    s.add_dependency 'vcard'
#    s.add_dependency 'logstash-output-email'
    s.add_dependency 'httplog'
    s.add_dependency 'net-ftp'
    s.add_dependency 'acts_as_votable'
    s.add_dependency 'api-auth'
    s.add_dependency 'twirp'
#    s.add_dependency 'logstash-filter-anonymize'
    s.add_dependency 'oktakit'
    s.add_dependency 'growl'
    s.add_dependency 'aruba'
    s.add_dependency 'tod'
    s.add_dependency 'resque_mailer'
    s.add_dependency 'jquery-validation-rails'
    s.add_dependency 'fluent-plugin-systemd'
    s.add_dependency 'puppet-strings'
    s.add_dependency 'simple_command'
    s.add_dependency 'readthis'
    s.add_dependency 'devise_saml_authenticatable'
    s.add_dependency 'active_model_otp'
    s.add_dependency 'ruby-mysql'
    s.add_dependency 'fluent-plugin-script'
    s.add_dependency 'fx'
    s.add_dependency 'hologram'
    s.add_dependency 'websocket-client-simple'
    s.add_dependency 'text-table'
    s.add_dependency 'bump'
    s.add_dependency 'database_rewinder'
    s.add_dependency 'indefinite_article'
    s.add_dependency 'github-pages-health-check'
    s.add_dependency 'ipynbdiff'
    s.add_dependency 'chef-ruby-lvm-attrib'
    s.add_dependency 'envlogic'
    s.add_dependency 'aws-sdk-controltower'
    s.add_dependency 'jasmine-rails'
    s.add_dependency 'jwe'
    s.add_dependency 'sniffer'
    s.add_dependency 'rb-kqueue'
#    s.add_dependency 'logstash-filter-memcached'
    s.add_dependency 'invoca-metrics'
    s.add_dependency 'faraday-detailed_logger'
    s.add_dependency 'certifi'
    s.add_dependency 'recurly'
    s.add_dependency 'carrot-top'
    s.add_dependency 'patience_diff'
    s.add_dependency 'packwerk'
    s.add_dependency 'flt'
    s.add_dependency 'lhm'
    s.add_dependency 'looker-sdk'
    s.add_dependency 'dynamoid'
    s.add_dependency 'closure_tree'
    s.add_dependency 'opentelemetry-instrumentation-dalli'
    s.add_dependency 'interactor-rails'
    s.add_dependency 'ruby-odbc'
    s.add_dependency 'url_mount'
    s.add_dependency 'chefspec'
    s.add_dependency 'bluepill'
    s.add_dependency 'nest'
    s.add_dependency 'azure_mgmt_storage'
    s.add_dependency 'data_objects'
    s.add_dependency 'yard-doctest'
    s.add_dependency 'allure-ruby-adaptor-api'
    s.add_dependency 'font_assets'
    s.add_dependency 'json_expressions'
    s.add_dependency 'rack-raw-upload'
    s.add_dependency 'apnotic'
    s.add_dependency 'attribute_normalizer'
    s.add_dependency 'prawn-templates'
    s.add_dependency 'reform-rails'
    s.add_dependency 'metasploit-payloads'
    s.add_dependency 'maxmind-db'
    s.add_dependency 'client_side_validations'
    s.add_dependency 'optimizely-sdk'
    s.add_dependency 'manpages'
    s.add_dependency 'turnout'
    s.add_dependency 'net-dns'
    s.add_dependency 'cvss-suite'
    s.add_dependency 'blockenspiel'
    s.add_dependency 'opentelemetry-instrumentation-active_support'
    s.add_dependency 'twitter-text'
    s.add_dependency 'racksh'
    s.add_dependency 'metro_2'
    s.add_dependency 'guard-rails'
    s.add_dependency 'mini_exiftool'
    s.add_dependency 'redis-rack-cache'
    s.add_dependency 'axe-matchers'
    s.add_dependency 'dm-core'
    s.add_dependency 'staccato'
    s.add_dependency 'jekyll-mentions'
#=begin
    s.add_dependency 'jekyll-github-metadata'
    s.add_dependency 'fakes3'
    s.add_dependency 'signature'
#    s.add_dependency 'splitclient-rb'
    s.add_dependency 'arkency-command_bus'
    s.add_dependency 'coolline'
    s.add_dependency 'busser-rspec'
    s.add_dependency 'nesty'
    s.add_dependency 'clearbit'
    s.add_dependency 'webrat'
    s.add_dependency 'language'
    s.add_dependency 'firebase'
    s.add_dependency 'lolcat'
    s.add_dependency 'git-version-bump'
    s.add_dependency 'statesman'
    s.add_dependency 'emailage'
    s.add_dependency 'levenshtein-ffi'
}
